feat(sweeps): basic docs for Optuna scheduler
wandb/docs pull request #273
Opened 2023-06-06 15:29 UTC by gtarpenning

## Description

Adds information about the optuna scheduler

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-06-06 16:14 UTC, ngrayluna requested changes
Nice. No major stuff, just minor word smithing.

2023-06-06 16:14 UTC, ngrayluna commented on docs/guides/launch/sweeps-on-launch.md
> +  Create a launch sweep using Optuna's scheduling logic with a Job. Either create your own, steps in the [`wandb/launch-jobs`](https://github.com/wandb/launch-jobs/jobs/sweep_schedulers/optuna_schedu
QQ on this: "Either create your own, steps in the [`wandb/launch-jobs`](https://github.com/wandb/launch-jobs/jobs/sweep_schedulers/optuna_scheduler) repo, or use the pre-built `Optuna Scheduler Image Job` in the `wandb/jobs` project." 

Would it make sense to rewrite this as:

You can either create your own job or use a pre-built Optuna shedular image job. 

See the [`wandb/launch-jobs`](https://github.com/wandb/launch-jobs/jobs/sweep_schedulers/optuna_scheduler) repo for examples on how to create your own job. Pull the `'wandb/jobs/Optuna Sweep Scheduler:latest'` job from `wandb/jobs` project to use the pre-built  Optuna shedular image job.

2023-06-06 16:14 UTC, ngrayluna commented on docs/guides/launch/sweeps-on-launch.md
> +  Now, we can create a sweep configuration that uses this job. Include a `scheduler` block that with a `job` key pointing to the Optuna scheduler job (example below).
"Now, we can create a sweep configuration that uses this job...." -> "After you create a job, you can now create a sweep...."

2023-06-06 16:14 UTC, ngrayluna commented on docs/guides/launch/sweeps-on-launch.md
> +  Finally, we can launch the sweep to a an active queue with the launch-sweep command:
Finally, we can launch the sweep to a an active queue with the launch-sweep command -> Lastly, launch the sweep to a an active queue with the launch-sweep command:

2023-06-06 16:14 UTC, ngrayluna commented on docs/guides/launch/sweeps-on-launch.md
> +  Optuna is a hyperparameter optimization framework that uses a variety of algorithms to find the best hyperparameters for a given model (similar to Wandb). In addition to the [sampling algorithms](h
Wandb -> W&B

2023-06-06 16:48 UTC, ngrayluna approved these changes

2023-06-08 18:44 UTC, ngrayluna commented
Looks good to me. Is it safe to merge?

2023-06-08 23:36 UTC, gtarpenning commented
Yep, those jobs have now had their guts relocated, rebuilding and will merge this when the jobs are out of the ICU and on their feet. Probably tn @ngrayluna

2023-06-09 17:08 UTC, merged