Added new env var
wandb/docs pull request #282
Opened 2023-06-12 20:18 UTC by ngrayluna

## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here: https://wandb.atlassian.net/browse/DOCS-719

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-06-15 15:52 UTC, tristan-spaulding2 commented
Sounds like this ended up getting named GORILLA_DATA_RETENTION_PERIOD and it is in hours.  Default is 168.  Sound right @ramit-wandb ?

2023-06-15 15:55 UTC, ramit-wandb commented
> Sounds like this ended up getting named GORILLA_DATA_RETENTION_PERIOD and it is in hours. Default is 168. Sound right @ramit-wandb ?

Yes, that's correct.

2023-06-26 22:09 UTC, ngrayluna commented
Duplicate: https://github.com/wandb/docodile/pull/317

2023-07-14 17:04 UTC, ramit-wandb requested changes

2023-07-14 17:04 UTC, ramit-wandb commented on docs/guides/hosting/env-vars.md
> +| GORILLA_DATA_RETENTION_PERIOD   | The number of hours before the data from deleted runs will be permanently deleted and unrecoverable. |
We would want to mention the format in which this variable would need to be set for users to know how to invoke this method. We need to specify the number of hours with an `h` suffixed to the end of it. So, something like:

```
export GORILLA_DATA_RETENTION_PERIOD="168h"
```

is valid, but

```
export GORILLA_DATA_RETENTION_PERIOD="168"
```
is not.

2023-07-14 17:04 UTC, ramit-wandb commented on docs/guides/hosting/env-vars.md
This feature starts up a cron job that goes ahead and starts clearing up deleted and unused data, and checks for it every minute. So we should also mention that users should be very cautious when they use this environment variable since their data will start getting cleaned up effective immediately. 

We probably also want to recommend taking a bucket and database backup before enabling this flag.

2023-07-14 18:00 UTC, ngrayluna commented on docs/guides/hosting/env-vars.md
@ramit-wandb QQ: This one minute cadence of clearing and deleting data happens after the time specified? e.g. If I specify 2hours, it'll start clearing out data AFTER two hours?

2023-07-14 20:19 UTC, merged