Add documentation for the Ultralytics integration
wandb/docs pull request #354
Opened 2023-07-24 11:34 UTC by soumik12345

## Description

Add documentation for the Ultralytics integration

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [x] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [x] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-07-24 15:27 UTC, ngrayluna requested changes
Did an edit pass. 

Change request: replace the .gifs with a smaller file size. We are moving towards limiting the .gif size to less than 10MB (the smaller the better though).

2023-07-28 08:14 UTC, soumik12345 commented
Hi @ngrayluna 
I was able to build locally, although its failing in the CI.

2023-07-28 16:32 UTC, ngrayluna commented
Ah, yeah. We have this annoying bug where  relative markdown links breaks the japanese docs if you don't change those as well. 

I went ahead and fixed it. CI works now.

2023-07-28 16:32 UTC, ngrayluna approved these changes

2023-07-28 16:33 UTC, merged