Artifact add project level Automations 764
wandb/docs pull request #435
Opened 2023-09-28 16:30 UTC by ngrayluna

## Description

Adds a page on how to make an automation for artifacts.

## Ticket

https://wandb.atlassian.net/jira/software/projects/DOCS/boards/28?selectedIssue=DOCS-764

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-09-28 16:33 UTC, ngrayluna commented
Draft preview: [Artifact automations _ Weights & Biases Documentation.pdf](https://github.com/wandb/docodile/files/12751888/Artifact.automations._.Weights.Biases.Documentation.pdf)

Where the page is in the table of contents (left navbar)
<img width="224" alt="Screen Shot 2023-09-28 at 9 33 01 AM" src="https://github.com/wandb/docodile/assets/15202580/fed583d7-d527-4543-a132-85df12bf0cfe">

2023-09-28 16:35 UTC, ngrayluna commented on docs/guides/artifacts/artifact-automation.md
> +Use the [INSERT].
@noaleetz What is a common use case that customers use "an artifact alias is created"?  This tip box will call out when to use one or the other event types like we do in the Model Reg docs 
<img width="592" alt="Screen Shot 2023-09-28 at 9 34 59 AM" src="https://github.com/wandb/docodile/assets/15202580/752ff593-036e-4f3e-8e2d-9afc588f6a83">

2023-09-28 21:44 UTC, kenleejr commented on docs/guides/artifacts/artifact-automation.md
> +Use the [INSERT].
I guess we could say:

Use the **Linking a new artifact to a collection** event type to kick off a workflow step when a new dataset snapshot gets logged as an artifact, such as retraining a core model. Use the **Adding a new alias to a version of an artifact" to specify an alias that identifies a dataset version, like `golden`, and triggers downstream processing or quality reporting on that dataset. 

Honestly not sure if people use aliases in this way for artifacts.

2023-09-28 23:49 UTC, ibindlish commented on docs/guides/artifacts/artifact-automation.md
> +Use the [INSERT].
We don't show the "linking a new artifact to a reg model" event from the project page anymore - https://wandb.atlassian.net/browse/WB-15044

2023-09-28 23:49 UTC, ibindlish commented on docs/guides/artifacts/artifact-automation.md
> +Use the [INSERT].
cc. @noaleetz

2023-09-29 05:16 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
> +An *event* is a change that takes place in the W&B ecosystem. You can define two different event types: **A new version of an artifact is added in a collection** and **An artifact alias is created**.
Change to: An *event* is a change that takes place in the W&B ecosystem. For automations that apply to artifacts in a project, the event types are for changes applied to an artifact collection. You can define two different event types for artifact collections in your project: **A new version of an artifact is added in a collection** and **An artifact alias is created**.

2023-09-29 05:19 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
> +An *event* is a change that takes place in the W&B ecosystem. You can define two different event types: **A new version of an artifact is added in a collection** and **An artifact alias is created**.
can we add a screenshot of the automations slider in a project which shows where users will select from the possible event types? 

<img width="1379" alt="Screenshot 2023-09-28 at 10 18 59 PM" src="https://github.com/wandb/docodile/assets/40642416/89ff3582-3546-4963-9479-0331e84d0606">

2023-09-29 05:21 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
@ngrayluna for any screenshots or assets feel free to use [this](https://wandb.ai/reviewco/Autocompletion/automations) link - it pulls up the automations tab for a project which has existing automations set up.

2023-09-29 05:23 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
I think it would be useful to guide the user to where they can add automations (how to navigate to the project automations tab) if they are in their artifacts page - we should add a gif of how they can get to the New Automation slider

2023-09-29 05:26 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
> +description: Use an Automation to retrain models as new data comes in
change description to: Use an Automation on artifacts in your project to trigger actions when aliases or versions in an artifact collection are created or changed. For example, you can trigger a launch job whenever a new version is added to a dataset artifact to automatically retrain a model.

2023-09-29 05:29 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
Lets add a sentence clarifying how automations at the project scope are different from automations at the Model Registry scope. We often see confusion around why adding an alias to artifact doesn't kick off a MR autonation or vice versa so we should clarify that Automations also exist at registry level (and maybe link docs) and should not be confused w project automations.

2023-09-29 05:38 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
> +Use the [INSERT].
@ngrayluna here are the 2 scenarios I think we should showcase for each of the 2 events as a tip so that the users have examples of when they might use 1 or the other:

- new version: model re-training - automation is applied to a dataset artifact and it kicks off a retraining job when fresh data comes in (a new version is added to the dataset artifact)
- alias is added: model evaluation - like Ken suggested when an alias 'golden-dataset', or thinking out loud 'test-set' is added then model evaluation job is triggered and an evaluation report is produced showing model results on this dataset version. The alias 'test-set' is listened for b/c only a version w this alias has a balanced test set for example.

2023-09-29 05:40 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
> +An action is a responsive mutation (internal or external) that occurs as a result of some trigger. There are two types of actions you can create for artifacts: webhooks and [W&B Launch Jobs](../launc
There are two types of actions you can create for artifacts: -> change to: _There are two types of actions you can trigger in response to events on artifact collections in your project:_

2023-09-29 05:45 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
> +2. (Optional) If you selected **A new version of an artifacts is created in a collection** event, provide the name of a registered model from the **Artifact collection** dropdown.
<img width="575" alt="Screenshot 2023-09-28 at 10 42 34 PM" src="https://github.com/wandb/docodile/assets/40642416/dde22666-c87e-45c0-bf3f-6242cb1586ce">

This is actually not an optional field - the artifact collection you want to apply this automation needs to be selected from the dropdown to proceed to next step. 

@ibindlish - to confirm there is no way to add an automation that applies to ALL artifact collections in a project? As you must populate the artifact collection filter.

2023-09-29 05:51 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
> +2. (Optional) If you selected **A new version of an artifacts is created in a collection** event, provide the name of a registered model from the **Artifact collection** dropdown.
We should change the text to remove any references to registered model as this is not relevant for project level automations. 

If you selected **A new version of an artifacts is created in a collection** event, provide the name of a registered model from the **Artifact collection** dropdown. -> change to: _If you selected **A new version of an artifacts is created in a collection** event, provide the name of the artifact collection that the automation should listen to changes to from the **Artifact collection** dropdown. For example, if your automation should trigger the retraining of a model when new data comes in, you might have an artifact collection named "labeled-datasets" - whenever a new version is added to this specific collection, the automation should trigger. When creating this automation, in the artifact collection dropdown you would select "labeled-datasets" _

2023-09-29 05:51 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
> +10. Click on the **Create automation** button.
can we add a step which shows user where to see the completed automation and include an image?

2023-09-29 05:54 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
> +<Tabs
Hey @ibindlish @kenleejr  - should any of these sample payloads be revised for the project level automations workflow? For ex [link artifact](types: LINK_ARTIFACT) is defined for github payload below but linking is not relevant for project level automations.

2023-09-29 05:55 UTC, noaleetz commented on sidebars.js
> +            'guides/artifacts/artifact-automation',
lets call this guide something that will definitely not be confused with model registry automations - maybe "project-scoped-automations".

2023-09-29 05:57 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
Can we add a gif of start to finish creating an automation workflow in project view (we can use a pre-configured webhook, no need to show that workflow).

2023-09-29 06:00 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
We should add a note that clarifies that project level automations will only trigger if an event, such as adding an alias, is done to a project level artifact version. Model Reg automations will only trigger if an event, such as adding an alias, is done to a linked artifact version inside the Model Registry. Users should make sure they are performing the event in the correct scope and creating the automations in the right place. 

Here is 1 [example](https://weightsandbiases.slack.com/archives/C04QJ7LJGHE/p1694794445751629?thread_ts=1694629120.105229&cid=C04QJ7LJGHE) of a user being confused because the automation and event occurred in different scopes

2023-09-29 16:16 UTC, ibindlish commented on docs/guides/artifacts/artifact-automation.md
> +2. (Optional) If you selected **A new version of an artifacts is created in a collection** event, provide the name of a registered model from the **Artifact collection** dropdown.
@noaleetz Actually, from the project view, you _can_ create automations at the project level - specifically only for the `ADD_ARTIFACT_ALIAS` type.

2023-09-29 16:16 UTC, ibindlish commented on docs/guides/artifacts/artifact-automation.md
> +<Tabs
I agree with your example. Basically I think the payloads just need to be updated to remove the LINK_ARTIFACT event

2023-10-02 23:17 UTC, ngrayluna commented on docs/guides/artifacts/artifact-automation.md
@noaleetz How's this? 
<img width="662" alt="Screen Shot 2023-10-02 at 4 17 06 PM" src="https://github.com/wandb/docodile/assets/15202580/c0b47e87-4d7f-4e7e-acd6-999b7375b380">

2023-10-02 23:18 UTC, ngrayluna commented on docs/guides/artifacts/artifact-automation.md
And then we create something similar in the Model Reg page?

2023-10-03 17:55 UTC, ngrayluna commented on docs/guides/artifacts/artifact-automation.md
> +<Tabs
Is this correct?

<img width="684" alt="Screen Shot 2023-10-03 at 10 54 51 AM" src="https://github.com/wandb/docodile/assets/15202580/a800e325-c30f-42ff-ae29-90f4a050032b">

2023-10-03 18:59 UTC, ngrayluna commented on docs/guides/artifacts/artifact-automation.md
> +Use the [INSERT].
How's this?
<img width="653" alt="Screen Shot 2023-10-03 at 11 59 40 AM" src="https://github.com/wandb/docodile/assets/15202580/a64ccda2-0a6d-44a2-b3ab-2cf4806a0d70">

2023-10-03 21:51 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +Use the **A new version of an artifact is added in a collection** event type for applying reoccurring actions to each version of an artifact. For example, you can create an automation that automatica
Is reoccuring a word? I think it might be recurring :)

2023-10-03 21:54 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +Use the **A new version of an artifact is added in a collection** event type for applying reoccurring actions to each version of an artifact. For example, you can create an automation that automatica
I think the language to each version of an artifact can be confusing / makes it seem like something happens to each version. Would recommend something more along the lines - "... event type to trigger an event whenever a new version is added to an artifact..."

Let use the language added rather than created for version to make it clear it is trigger when a new version is added to a collection (rather than a new artifact collection being created): "...automatically starts a training job when a new dataset artifact version is added to an artifact in your project."

2023-10-03 21:56 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +Use the **A new version of an artifact is added in a collection** event type for applying reoccurring actions to each version of an artifact. For example, you can create an automation that automatica
Lets make sure we're adding clarifications where we can that (generally for whole guide) that specifies language around 'project' - i.e artifact in your project, etc. The reason for this is because there will be similarities b/w model registry automations and this doc and i want to make sure we're dropping reminders that we're focused on the project context

2023-10-03 22:01 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
Yes I like how this is looking! I would just tweak use of the word 'models'. 

_This is in contrast to Automations that listen for events inside the W&B Model Registry. Automations created in the W&B Model Registry are at the **Model Registry scope** rather than **project scope** - they are triggered when events are performed on model versions linked to the Model Registry, rather than versions in the Artifacts tab of your project page. For information on how to add Automations for model versions published to your team's Model Registry, see...."_

2023-10-03 22:02 UTC, noaleetz commented on docs/guides/artifacts/artifact-automation.md
> +<Tabs
Hey @ibindlish @kenleejr would you be able to quickly review the new payload examples for PROJECT scoped automations?

2023-10-03 22:06 UTC, ibindlish commented on docs/guides/artifacts/artifact-automation.md
> +<Tabs
@ngrayluna Could you please change the `types` here to ADD_ARTIFACT_ALIAS?

<img width="439" alt="image" src="https://github.com/wandb/docodile/assets/14353406/68e86dd7-e68e-4177-963e-6252211bcc84">

2023-10-03 22:06 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +Create an automation on artifacts to trigger actions when aliases or versions in an artifact collection are created or changed. For example, you can trigger a launch job whenever a new version is add
Artifact automations have project-level scope. -> Artifact automations are at the scope of a project.

2023-10-03 22:08 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +This is in contrast to model automations created in the W&B Model Registry. Automations created in the W&B Model Registry are scoped to the Model Registry. For information on how to create an automat
Yes I like how this is looking! I would just tweak use of the word 'models'.

This is in contrast to Automations that listen for events inside the W&B Model Registry. Automations created in the W&B Model Registry are at the Model Registry scope rather than project scope - they are triggered when events are performed on model versions linked to the Model Registry, rather than versions in the Artifacts tab of your project page. For information on how to add Automations for model versions published to your team's Model Registry, see...."

2023-10-03 22:10 UTC, ibindlish commented on docs/guides/artifacts/artifact-automation.md
> +  ${event_type} --> "LINK_ARTIFACT" or "ADD_ARTIFACT_ALIAS"
Not sure if the `LINK_ARTIFACT` text here will show up in the page that is rendered as I didn't see it in your screenshot. But just wanted to point it out here so that we don't miss it! :) The rest of the examples lgtm.

2023-10-03 22:11 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +Use the **An artifact alias is added** event type to create an automation that applies to a specific dataset version. For example, you could create an automation that triggers an action when someone
Note that we should refrain from calling out a artifact type (i.e dataset) unless we're in the context of an example and explicitly say "for example, if you have an artifact of type dataset". Artifact automations can apply to any artifact type, unlike in model registry where they are only for type=model

Above - that means we should change "create an automation that applies to a specific dataset version" to "create an automation that listens for a specific alias being added to an artifact version", or applies to an artifact version that is labeled with a specific alias (tweaked so it is clear that the alias is what is marking the version as unique)

2023-10-03 22:15 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
>  View automations associated to an artifact from the W&B App UI.
are planning on adding instructions on where to look at automations in the project UI and attach a screenshot?

2023-10-03 22:17 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
>  title: Artifact automations
suggesting that we should call this project scoped automations since model reg artifacts are also applied to artifact versions so it could cause confusion if we're not prescriptive as to what scope we're referring to

2023-10-03 22:18 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
Can we add a full E2E gif of the process of starting from artifacts tab, navigating to an automation, and creating a new one?

2023-10-03 22:20 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
Can we add a line helping users understand in what scenarios they should use project-scoped automations vs. model registry scoped automations? Something like: "You should consider using project-scoped automations when wanting to automated downstream actions for versioning of a non-model type, such as a dataset or prompt. Check out XXX if you are working with artifacts of type model to learn how to add automations that apply to your model registry.

2023-10-03 23:05 UTC, ngrayluna commented on docs/guides/artifacts/project-scoped-automations.md
> +This is in contrast to model automations created in the W&B Model Registry. Automations created in the W&B Model Registry are scoped to the Model Registry. For information on how to create an automat
QQ: When talking about the term "scope" (outside of W&B), we normally say something like, "The variable is in scope of the function definition." 

Do we want to stick with this convention? Or do want to say "...at the Model Registry scope"?

2023-10-04 00:15 UTC, ngrayluna commented
* Ready for review.  See attached PDF
* To dos:
   * Decide "scope" usage in doc.  
   * [Note] To do: Add "E2E gif of the process of starting from artifacts tab, navigating to an automation, and creating a new one".

[v4Artifact automations _ Weights & Biases Documentation.pdf](https://github.com/wandb/docodile/files/12797977/v4Artifact.automations._.Weights.Biases.Documentation.pdf)

2023-10-06 01:07 UTC, noaleetz commented
Hey @ngrayluna - 1 thing to discuss - what should we call the name of the guide? And how do we make sure to distinguish this from model reg automations? Currently we have:

the docs for model reg automations
- name in sidebar: Automations
- guide title: Automations for Model CI/CD

the docs for artifacts automations (this doc)
- name in sidebar: Artifact automations
- guide title: Artifact automations

We should make sure these are consistent - maybe:

the docs for model reg automations
- name in sidebar: Model registry automations
- guide title: Triggering CI/CD events via model registry changes

the docs for artifacts automations (this doc)
- name in sidebar: Artifact automations
- guide title: Triggering CI/CD events via artifact changes

2023-10-06 01:10 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +To create an automation, define the [action](#action-types) you want to occur based on an [event type](#event-types). For example, you can create a trigger that automatically retrains a model when a
Do you think it is more clear to just say an automation is an event, action pair where performing an event triggers a downstream action (with the same hyperlinks linked above)

2023-10-06 01:11 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +Create an automation on artifacts to trigger actions when aliases or versions in an artifact collection are created or changed. For example, you can trigger a launch job whenever a new version is add
Maybe we can change to - Artifact automations belong to a project, just like artifact collections in your project.

2023-10-06 01:12 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +Artifact automations are project-scope. This means that only events within a project will trigger an artifact automation.
are scoped to your project? of project-scope?

2023-10-06 01:14 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +This is in contrast to automations created in the W&B Model Registry. Automations created in the model registry have Model Registry scope; they are triggered when events are performed on model versio
automations for model versions (instead of models versions)

2023-10-06 01:15 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +An *event* is a change that takes place in the W&B ecosystem. For automations that apply to artifacts in a project, the event types are for changes applied to an artifact collection.
maybe instead of saying project-scoped across this doc we just say what is written here - automations that apply to artifacts in a project. Though it is a bit wordier

2023-10-06 01:16 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +Define a team secret to ensure the authenticity and integrity of data transmitted from payloads.
can we add a gif for secret creation

2023-10-06 01:16 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +### Add a webhook
can we add a gif for webhook creation

2023-10-06 01:17 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +2. (Optional) If you selected **A new version of an artifact is created in a collection** event, provide the name of the artifact collection that the automation should respond to from the **Artifact
btw I think i left a comment on this before but this is not optional, you cant proceed w/o selecting

2023-10-06 01:19 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +![](/images/artifacts/automations_sidebar.gif)
in the pdf this is not the automations side bar - it is workspace screenshot
<img width="960" alt="Screenshot 2023-10-05 at 6 19 27 PM" src="https://github.com/wandb/docodile/assets/40642416/727ca77f-65dc-41dd-9211-6bffedc8b533">

2023-10-06 01:22 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +3. From the list, select the name of the automation you want to view.
hmmm what do you mean by this? You can't actually select an automation, only view the properties in the table. see [here](https://wandb.ai/reviewco/Autocompletion/automations) - it is just a view only table where you see the full list of automations

2023-10-16 20:50 UTC, noaleetz commented
Hey @ngrayluna are we ready to make this live soon :)

2023-10-17 20:44 UTC, ngrayluna commented on docs/guides/artifacts/project-scoped-automations.md
> +To create an automation, define the [action](#action-types) you want to occur based on an [event type](#event-types). For example, you can create a trigger that automatically retrains a model when a
Changed to:

<img width="557" alt="Screen Shot 2023-10-17 at 1 44 15 PM" src="https://github.com/wandb/docodile/assets/15202580/b56c330a-2271-46dc-bcc3-23b2319541e8">

2023-10-17 20:50 UTC, ngrayluna commented on docs/guides/artifacts/project-scoped-automations.md
> +![](/images/artifacts/automations_sidebar.gif)
Ah. The PDF doesn't show the .gif it looks like
![automations_sidebar copy](https://github.com/wandb/docodile/assets/15202580/7d132a49-c7ae-4f05-a50a-e2dd9b872dbd)

2023-10-17 20:58 UTC, ngrayluna commented on docs/guides/artifacts/project-scoped-automations.md
> +Define a team secret to ensure the authenticity and integrity of data transmitted from payloads.
Holding off making edits to this section as it will need to be updated once we ship these changes in Model Reg" https://github.com/wandb/docodile/pull/446

2023-10-17 21:00 UTC, ngrayluna commented on docs/guides/artifacts/project-scoped-automations.md
> +### Add a webhook
@noaleetz Can you provide said .gif? Or direct me to a project w/ a webhook specific for artifacts? Re: these seem to be more of a Model Reg use cases: https://wandb.ai/reviewco/Autocompletion/automations?workspace=user-noahluna

2023-10-17 21:01 UTC, ngrayluna commented
@noaleetz  New draft ready for review: 
[Artifact automations _ Weights & Biases Documentation.pdf](https://github.com/wandb/docodile/files/12958358/Artifact.automations._.Weights.Biases.Documentation.pdf)

2023-10-19 05:57 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +An *event* is a change that takes place in the W&B ecosystem. You can define two different event types for artifact collections in your project: **A new version of an artifact is added in a collectio
We should make sure the event types match the exact thing written in the dropdown - in this case a new version of an artifact is CREATED and An artifact alias is ADDED (verbs are mixed up here)
<img width="583" alt="Screenshot 2023-10-18 at 10 56 09 PM" src="https://github.com/wandb/docodile/assets/40642416/c9b009cf-058b-49ff-91a1-93b9ade2e0bb">
n

2023-10-19 05:59 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +![](/images/artifacts/automations_sidebar.gif)
A gotcha - I think we are missing in both the gif and instructions a prompt to click on New Automation

2023-10-19 06:01 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +Create an automation that triggers when an artifact is changed. Use artifact automations when you want to automate downstream actions for versioning artifacts that are not of type "model".
ok I am actually gonna backtrack on this - lets remove the specifics about not being of type model since that might cause confusion and you technically still can version models in artifacts and have that trigger an automation, we just recommend that you handle model versioning automations in Model Reg instead. 

Lets just say:

> Create an automation that triggers when an artifact is changed. Use artifact automations when you want to automate downstream actions for versioning artifacts

2023-10-19 06:03 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +For example, you can create an automation that triggers a [launch job](../launch/intro.md) when a new artifact version is added.
I lost the thread, maybe I said this elsewhere but I think we should give a concrete example of a workflow where this is relevant like re-training a model whenever a fresh version of a dataset comes in. It is hard to contextualize why this is related to CI/CD without rooting it in a concrete CI/CD example

2023-10-19 06:04 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +For example, you can create an automation that triggers a [launch job](../launch/intro.md) when a new artifact version is added.
lets specify launch job or webhook - webhook can open the door to a lot of options to connect w external ci/cd so we should suggestion it early on

2023-10-19 06:05 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +### Add a webhook
webhook creation will be the same for both cases - it happens in the team settings both for a webhook used in MR automation and artifact automation.

2023-10-19 06:07 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +Delete an automation associated with a artifact. Actions in progress are not affected if you delete that automation before the action completes.
hey @ibindlish - would this be a good place to advise that deleting a launch queue will delete all associated automations?

2023-10-19 06:08 UTC, noaleetz requested changes
feedback left as comments in latest commit

2023-10-19 17:09 UTC, ngrayluna commented on docs/guides/artifacts/project-scoped-automations.md
> +For example, you can create an automation that triggers a [launch job](../launch/intro.md) when a new artifact version is added.
Sure! Based on your talks with customers, what examples come to mind?

2023-10-19 17:13 UTC, ngrayluna commented on docs/guides/artifacts/project-scoped-automations.md
> +An *event* is a change that takes place in the W&B ecosystem. You can define two different event types for artifact collections in your project: **A new version of an artifact is added in a collectio
Good eye.

2023-10-19 20:14 UTC, ngrayluna commented on docs/guides/artifacts/project-scoped-automations.md
> +For example, you can create an automation that triggers a [launch job](../launch/intro.md) when a new artifact version is added.
Added this for now" "For example, you can trigger a launch job whenever a new version is added to a dataset artifact to automatically retrain a model"

2023-10-19 20:16 UTC, ngrayluna commented
@noaleetz Added feedback. Can we merge and do a follow up on .gifs and/or mention this: 

> hey @ibindlish - would this be a good place to advise that deleting a launch queue will delete all associated automations?

If we don't get a response soon? Re: Today is the last day of the week to publish docs. (No build Fridays)

2023-10-19 20:18 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +For example, you can create an automation that triggers a [launch job](../launch/intro.md) when a new artifact version is added.
I am going to start a thread w Hoff+Ken to get some more specific example ideas we can use here

2023-10-19 20:47 UTC, ibindlish commented on docs/guides/artifacts/project-scoped-automations.md
> +Delete an automation associated with a artifact. Actions in progress are not affected if you delete that automation before the action completes.
Yeah, I think we could mention it here. Should we also mention it in the queue  section of launch docs? Or is that scope-creep?

2023-10-19 20:54 UTC, ngrayluna commented on docs/guides/artifacts/project-scoped-automations.md
> +Delete an automation associated with a artifact. Actions in progress are not affected if you delete that automation before the action completes.
@noaleetz Is this line OK? "Automations are deleted if you delete a launch queue that is associated to an automation."

We should def. mention it in the launch docs, too. But that should be a follow up because we are about to ship an entirely new "Set up Launch" section (and that's where we mention creating and deleting queues).

2023-10-19 21:40 UTC, ngrayluna commented on docs/guides/artifacts/project-scoped-automations.md
> +For example, you can create an automation that triggers a [launch job](../launch/intro.md) when a new artifact version is added.
@noaleetz  Which of Hoff's comments do you suggest? Perhaps, we can add one for both webhooks and for launch automations?

2023-10-23 23:23 UTC, merged