feat: add custom callback example and reference colab
wandb/docs pull request #442
Opened 2023-10-06 08:43 UTC by parambharat

## Description

This PR adds details to the huggingface documentation related to custom logging and callbacks. Additionally, we also fix the description of the `WANDB_LOG_MODEL` env var to reflect the new changes in the HF integration.

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-10-06 09:38 UTC, morganmcg1 requested changes

2023-10-06 09:38 UTC, morganmcg1 commented on docs/guides/integrations/huggingface.md
> +For instance here's how you could modify the callback to log predictions to a Weights & Biases table after each evaluation
1. Can you add a header to this section: “View evaluation samples during training”
2. Can you complete the code example to show the callback being added to the Trainer
3. Show how to set an optional logging frequency if they don’t want to log every eval_steps
4. A bit more explanation of what is going on in this code

2023-10-06 11:16 UTC, parambharat commented on docs/guides/integrations/huggingface.md
> +For instance here's how you could modify the callback to log predictions to a Weights & Biases table after each evaluation
@morganmcg1 , Thanks for the detailed review comments. I have addressed all of them. Please let me know what you think and resolve the conversation if you are satisfied.

2023-10-06 16:50 UTC, morganmcg1 approved these changes
LGTM, thanks for the changes!

2023-10-06 16:51 UTC, morganmcg1 commented
@ngrayluna would love a merge on this whenever you get a chance, as lukas has been asking for it

2023-10-06 16:55 UTC, morganmcg1 commented
fixed merge conflicts

2023-10-13 17:51 UTC, ngrayluna requested changes
Build failing. Markdown format needs fix.

2023-10-16 16:45 UTC, merged