How to debug webhook
wandb/docs pull request #446
Opened 2023-10-16 20:29 UTC by ngrayluna

## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

https://wandb.atlassian.net/browse/DOCS-784?atlOrigin=eyJpIjoiZmFhYjAwZGYxZjkzNGIwYzg0MDhmNmUxYmI2MzQ1ZTQiLCJwIjoiaiJ9

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-10-17 17:11 UTC, ibindlish commented on docs/guides/model_registry/automation.md
> +
We should probably add `PAYLOAD` to this list too

2023-10-17 17:11 UTC, ibindlish commented on docs/guides/model_registry/automation.md
> +  https://api.example.com/endpoint
Maybe replace 'https://api.example.com/endpoint' with `API_ENDPOINT` since that's what you wrote at the top?

2023-10-17 17:41 UTC, ngrayluna commented
Latest preview:  
[Automations _ Weights & Biases Documentation.pdf](https://github.com/wandb/docodile/files/12937577/Automations._.Weights.Biases.Documentation.pdf)

2023-10-18 20:42 UTC, noaleetz commented on docs/guides/model_registry/automation.md
> +Secrets are team-level variables that let you obfuscate private strings such as credentials, API keys, passwords, tokens, and more. W&B considers secrets as any string that you want to protect its pl
you want to protect its plain text content. -> maybe I am overthinking but this wording is confusing a bit. Maybe: "W&B recommends you use secrets to store any string that you want to protect the plain text content of".

2023-10-18 20:47 UTC, noaleetz commented on docs/guides/model_registry/automation.md
> +Secrets are team-level variables that let you obfuscate private strings such as credentials, API keys, passwords, tokens, and more. W&B considers secrets as any string that you want to protect its pl
[Here](https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/GitHub-Actions-Secrets-Example-Token-Tutorial) is a good resource for how github actions explains secrets, we are doing something similar w W&B secrets.

_One of the ongoing challenges DevOps professionals face when [developing continuous integration workflows](https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/examples-GitHub-Actions-workflows) that integrate with disparate systems is how to protect that passwords, secret keys and tokens required to authenticate against them. That’s where the GitHub Actions (W&B Secrets) secret comes in. It provides a secure vault to store your confidential information, and a simple mechanism to access those secret tokens in your GitHub Actions scripts. (in your webhooks)_

2023-10-18 21:08 UTC, noaleetz commented on docs/guides/model_registry/automation.md
> +7. (Optional) Repeat steps 5 and 6 to create another secret (such as an access token).
_Repeat steps 5 and 6 to create another secret (such as an access token) if your webhook requires any such additional secret keys or tokens to authenticate a webhook. 

Note - you can use any secrets populated in the secret manager as an access token while configuring a webhook. To use an access token in your webhook it must be added as a secret._ 

note to @ngrayluna - feel free to make less wordy. I'm trying to emphasize here that access tokens should be added as secrets.

2023-10-18 21:08 UTC, noaleetz commented on docs/guides/model_registry/automation.md
> +9. (Optional) From the **Access token** dropdown menu, select the access token you want to use to authorize the sender.
(Optional) From the **Access token** dropdown menu select any additional secret keys or tokens required to authenticate a webhook that have been added as a W&B Secret, such as an access token. 

Note - to see where in the POST request the secret and access token will be passed in, check out the Troubleshoot your webhook [insert link to this section] section.

2023-10-18 21:08 UTC, noaleetz requested changes
added changes!! @ngrayluna

2023-10-19 02:51 UTC, merged