add nvidia info to launch docker setup
wandb/docs pull request #456
Opened 2023-10-27 02:45 UTC by bcsherma

## Description

In the launch docs overhaul we accidentally lost the section dedicated to setting up the nvidia container toolkit.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-10-27 02:50 UTC, zacharyblasczyk approved these changes

2023-10-27 05:09 UTC, KyleGoyette commented on docs/guides/launch/setup-launch-docker.md
> +
errant new line?

2023-10-27 05:09 UTC, KyleGoyette commented on docs/guides/launch/setup-launch-docker.md
> +
errant new line?

2023-10-27 05:09 UTC, KyleGoyette commented on docs/guides/launch/setup-launch-docker.md
> +## Configure a launch agent on a local machine
errant deleted line?

2023-10-27 05:09 UTC, KyleGoyette commented on docs/guides/launch/setup-launch-docker.md
> +  "rm": true
ahk missed this in my spacing check

2023-10-27 05:10 UTC, KyleGoyette commented on docs/guides/launch/setup-launch-docker.md
> +  "gpus": "all"
We should really add the accelerator image here as well :( . A user today just immediately ran into this.

2023-10-27 05:11 UTC, KyleGoyette reviewed
Overall looks good, I'm wondering if some formatting was autoapplied though

2023-10-27 18:05 UTC, ngrayluna requested changes

2023-10-27 18:05 UTC, ngrayluna commented on docs/guides/launch/setup-launch-docker.md
> +### Nvidia GPU
Let's make the title an action. E.g. "Enable launch agent to use GPU" (or something)

2023-10-27 18:05 UTC, ngrayluna commented on docs/guides/launch/setup-launch-docker.md
> +Use the `gpus` key in the launch queue configuration to specify the value that will be passed to `--gpus` when the agent runs your job on Docker. See [configure a Docker queue](#configure-a-docker-qu
Debating if this content should be moved up into the launch queue config section? since it is in relation to the launch queue's target environment?

Or rather, is there a way to specify to use GPUs in a launch agent's config? 

TL;DR let's make it clear if using GPUs is a part of a launch queue's target environment config vs. setting up an agent to be allowed to execute jobs on a local machine?   i.e. Let's make it clear the logic of what and where to specify parameters (launch queue vs launch agent config).

2023-10-31 23:21 UTC, bcsherma commented on docs/guides/launch/setup-launch-docker.md
> +Use the `gpus` key in the launch queue configuration to specify the value that will be passed to `--gpus` when the agent runs your job on Docker. See [configure a Docker queue](#configure-a-docker-qu
Yeah there are really two steps to enable GPU:
- make sure you are setting `--gpus` in your queue config
- make sure you have the nvidia container toolkit setup properly

I would propose the following compromise: include the `--gpus` argument in the example docker queue config where we demonstrate how the config is mapped to docker run arguments.

2023-10-31 23:22 UTC, bcsherma commented on docs/guides/launch/setup-launch-docker.md
> +
this is done automatically by prettier in my vscode. I wouldn't say errant, just motivated by style.

2023-10-31 23:24 UTC, bcsherma commented on docs/guides/launch/setup-launch-docker.md
> +  "gpus": "all"
I've added in just below in the same tip

2023-10-31 23:24 UTC, bcsherma commented on docs/guides/launch/setup-launch-docker.md
> +
prettier

2023-10-31 23:24 UTC, bcsherma commented on docs/guides/launch/setup-launch-docker.md
> +## Configure a launch agent on a local machine
prettier

2023-11-01 21:45 UTC, KyleGoyette approved these changes

2023-11-06 18:52 UTC, ngrayluna commented
> Yeah there are really two steps to enable GPU:
> 
> * make sure you are setting `--gpus` in your queue config
> * make sure you have the nvidia container toolkit setup properly
> 
> I would propose the following compromise: include the `--gpus` argument in the example docker queue config where we demonstrate how the config is mapped to docker run arguments.



@bcsherma @KyleGoyette Incorporated said changes to queue section of this page. Let me know if this works. Preview of how this looks included int his PDF
[Set up for Docker _ Weights & Biases Documentation.pdf](https://github.com/wandb/docodile/files/13271421/Set.up.for.Docker._.Weights.Biases.Documentation.pdf)

2023-11-07 22:09 UTC, KyleGoyette approved these changes

2023-11-07 23:57 UTC, ngrayluna approved these changes

2023-11-07 23:58 UTC, merged