Update artifact deletion guide to add soft-deletion vs hard-deletion info and how to enable garbage collection
wandb/docs pull request #462
Opened 2023-10-30 21:31 UTC by ngrayluna

## Description

Adds soft delete and hard delete info to artifact deletion guide, including how to enable garbage collection for W&B server and BYOB

## Ticket

https://wandb.atlassian.net/browse/DOCS-794

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-10-30 21:32 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +<!-- You can delete aliases before you delete an artifact or you can delete an artifact and pass an additional flag to the API call. -->
QQ: What flag do we use? Sort of vague.

2023-10-30 21:33 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +Garbage collection is not automatically enabled for W&B Server. Contact your INSERT for more information.
@noaleetz Would you rather we call out Server here, or have htem talk directly to their support person?

2023-10-30 21:50 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +Garbage collection is not automatically enabled for W&B Server. Contact your INSERT for more information.
They can do this themselves! There are 2 things they need to do to enable artifact garbage collection for server (including dedicated cloud if they have BYOB):

- setting an environment variable: GORILLA_ARTIFACT_GC_ENABLED=true
- enable bucket versioning: each provider has their own docs: enabling versioning (for [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/manage-versioning-examples.html), [GCP](https://cloud.google.com/storage/docs/object-versioning)) or soft deletion (for [AZ](https://learn.microsoft.com/en-us/azure/storage/blobs/soft-delete-blob-overview)) on their storage bucket

2023-10-30 21:51 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +Garbage collection is not automatically enabled for W&B Server. Contact your INSERT for more information.
note that for this specific case you can think of enabling bucket versioning == enabling soft-deletion **for Azure**. 

bucket versioning and soft deletion (in azure) is referring to essentially the same thing. it is just azure has a slightly different implementation.

2023-10-30 21:53 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +<!-- You can delete aliases before you delete an artifact or you can delete an artifact and pass an additional flag to the API call. -->
in the code snippets below there is are examples of this:
`artifact.delete(delete_aliases=True)`

2023-10-30 22:04 UTC, noaleetz commented
Adding a note that at the end of the section on enabling garbage collection, we can optionally add a [note](https://weightsandbiases.slack.com/archives/C02CXJ3RSBA/p1698703216566989?thread_ts=1698698101.973919&cid=C02CXJ3RSBA) on the recommendation keeping the copies to 1

2023-10-30 22:32 UTC, noaleetz requested changes
I added comments in response! Changed the PR title also

2023-10-31 01:02 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +:::
@ngrayluna do you know why we reccommed this?
" It is recommended that you remove aliases associated to the artifact you want to delete before you delete the artifact."

I see you added it in gitblame but maybe I did not look further in history.

2023-10-31 01:05 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +Delete artifacts interactively with the App UI or programmatically with the W&B SDK. The sections in this page describe how to delete
this would be a good place to mention soft-deletion vs hard-deletion (and that all the instructions for how to delete are soft-deletion, if you go to section XYZ you can learn more about how to enable hard-deletion via garbage collection, the underlying job that runs regularly to review all soft-deleted artifacts garbage collect the associated files / delete bytes from storage safely.

2023-10-31 01:06 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +Delete artifacts interactively with the App UI or programmatically with the W&B SDK. The sections in this page describe how to delete
I see this context is added below so my suggestion would be to couple it more closely w the first line when describing the section (or mention in section description that we will cover garbage collection)

2023-10-31 01:11 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +:::note
We should call out that GC is enabled by default for public cloud. For any users bringing their own storage bucket (BYOB) on wandb.ai - they also need to enable bucket versioning (step #2). This cohort might technically be on cloud, but if they have their own bucket they need to own enabling versioning as well.

2023-10-31 01:14 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +specific artifact versions, how to delete an artifact collection, how to delete artifacts with and without aliases, and more.
Can we add a plug here for TTL? If you want to schedule deletion of an artifact, visit [ttl docs]. 

We should also add a note inside TTL that points to this doc and mentions that TTL also is a soft-delete (it acts the same as calling.delete() just at a specific time). 

specify that both TTL (time-based scheduled deletion) and on-demand deletion of artifacts marks an artifact for deletion - or ‘soft-deletes’ an artifact

2023-10-31 01:17 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +When you delete an artifact, W&B marks that artifact as a *soft-delete*. The artifact remains as a soft-delete internally until it passes a garbage collection algorithm. The garbage collection consis
Let's specify what soft-delete means: it means the artifact has been marked for deletion in the DB and is pending deletion, but files/bytes have not been deleted from storage. 

Lets word the GC algo as follows: The artifact contents will remain in a soft-deletion, or pending deletion state, until a regularly run Garbage Collection job does the following:

2023-10-31 01:20 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +3. Lastly, if the artifact satisfies the conditions stated in the second step, W&B will conduct a *hard delete*.
What GC actually does it determines which files are safe to be deleted. So it checks the artifact and one by one reviews all files. The ones that are safe to delete that have no dependencies (don't exist in other artifacts) will be deleted, the remaining files will not be deleted (from storage), but the version itself will always be deleted and no longer appear in UI. "safe to delete" applies at the file level, not artifact version level

2023-10-31 04:09 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +:::note
And as you mentioned already - anyone on server requires both of those steps

2023-10-31 04:14 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +3. Lastly, if the artifact satisfies the conditions stated in the second step, W&B will conduct a *hard delete*.
I am not convinced we need to explain the GC algorithm to the user. I think we can just say:
"The artifact contents will remain in a soft-deletion, or pending deletion state, until a regularly run Garbage Collection job reviews all artifacts marked for deletion and deletes the associated files from storage if it is safe to do so.

2023-10-31 04:18 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +* [Enable soft delete for blobs if you use Azure](https://learn.microsoft.com/en-us/azure/storage/blobs/soft-delete-blob-overview).
Note that bucket versioning (used in AWS and GCP) and soft deletion (used in Azure) perform effectively the same thing and are programmatically enforced to ensure data loss prevention.

2023-10-31 04:21 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +* [Enable soft delete for blobs if you use Azure](https://learn.microsoft.com/en-us/azure/storage/blobs/soft-delete-blob-overview).
At the end of the instructions for enabling GC we should add [this](https://weightsandbiases.slack.com/archives/C02CXJ3RSBA/p1698699152160839?thread_ts=1698698101.973919&cid=C02CXJ3RSBA) recommendation - we recommend 
 setting copies to 1 to avoid keeping any extra data or incurring extra costs.

2023-10-31 04:22 UTC, noaleetz requested changes
sending it back for review! After this pass will share it with @szymon-piechowicz-wandb to get his eyes on it.

2023-10-31 18:31 UTC, ngrayluna reviewed
@noaleetz Quick question, wondering if this info blurb should exist in the secure storage container pages? And instead we leave a small banner here that says: "For W&B Server users, see these docs" (or something like that)?

2023-10-31 18:31 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +:::
@noaleetz No idea. It's in the docs (see second paragraph) https://docs.wandb.ai/guides/artifacts/delete-artifacts

2023-11-01 23:38 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +It is recommended that you remove aliases associated to the artifact you want to delete before you delete that artifact. See the [Update an artifact](./update-an-artifact.md) documentation for inform
I actually learned that we enforce this (it is not a recommendation)

<img width="374" alt="Screenshot 2023-11-01 at 4 37 14 PM" src="https://github.com/wandb/docodile/assets/40642416/82e910a0-a289-4506-936c-35bebdb9b818">

2023-11-01 23:40 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +* [Enable soft delete for blobs if you use Azure](https://learn.microsoft.com/en-us/azure/storage/blobs/soft-delete-blob-overview).
@ngrayluna note to address the above!

2023-11-01 23:42 UTC, ngrayluna commented
New preview: 
[Delete W&B Artifacts.pdf](https://github.com/wandb/docodile/files/13232659/Delete.W.B.Artifacts.pdf)

2023-11-01 23:42 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +:::note
@ngrayluna note to also call out enabling versioning for BYOB folks (and including recommending setting to copies to 1 as below). 

[Here](https://weightsandbiases.slack.com/archives/C05KFRM1Y78/p1698700135834349) is how Hoff explained to his customer

2023-11-01 23:42 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +The contents of the artifact remain as a soft-delete, or pending deletion state, until a regularly run garbage collection job reviews all artifacts marked for deletion. The garbage collection algorit
i would advise we use the term job > algorithm

2023-11-01 23:47 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +W&B suggests that you set the number of bucket version copies to 1 because it helps reduce storage costs and can help recover accidentally deleted data.
i don't think this helps w recovering deleted data. We actually don't have a way to do that now. its mostly for storage and cost purposes

2023-11-01 23:53 UTC, noaleetz commented
Lastly - can we also add a pointers in server + byob docs? thread - https://weightsandbiases.slack.com/archives/C02CXJ3RSBA/p1698779613762289?thread_ts=1698698101.973919&cid=C02CXJ3RSBA

- in BYOB docs (users using BYOB w/ [wandb.ai](http://wandb.ai/) must enable versioning)
- in W&B Server docs (users on server must both set the env var and enable versioning)

for the pointers, we can say something like: "To learn how to enable permanent deletion of files when artifacts are deleted if you are on ____ deployment types, visit the artifact deletion guuide"

2023-11-02 00:08 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +The contents of the artifact remain as a soft-delete, or pending deletion state, until a regularly run garbage collection job reviews all artifacts marked for deletion. The garbage collection algorit
I was thinking of job, but wasn't sure if people familiar with Launch would think of "job" as "launch job"...

2023-11-02 00:09 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +W&B suggests that you set the number of bucket version copies to 1 because it helps reduce storage costs and can help recover accidentally deleted data.
@noaleetz Noted. Wasn't sure because  of Jason's comment here. Do you know what he means?: https://weightsandbiases.slack.com/archives/C02CXJ3RSBA/p1698699189137479?thread_ts=1698698101.973919&cid=C02CXJ3RSBA

2023-11-02 00:15 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +The contents of the artifact remain as a soft-delete, or pending deletion state, until a regularly run garbage collection job reviews all artifacts marked for deletion. The garbage collection algorit
Changing to "garbage collection process" ?

2023-11-02 00:22 UTC, ngrayluna commented
@noaleetz Embarrassing question, where are our BYOB docs? 😅

2023-11-02 19:47 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +W&B suggests that you set the number of bucket version copies to 1 because it helps reduce storage costs and can help recover accidentally deleted data.
Yikes ok I am reviewing, I started a thread here to clarify [this](https://weightsandbiases.slack.com/archives/CT4901KC5/p1698954422803609)

2023-11-02 19:56 UTC, noaleetz commented
> @noaleetz Embarrassing question, where are our BYOB docs? 😅

Oh not embarrassing at all 

> @noaleetz Embarrassing question, where are our BYOB docs? 😅

Not embarrassing at all - secure storage connector is our public friendly name for BYOB :). So [here](https://docs.wandb.ai/guides/hosting/secure-storage-connector) is the BYOB docs, actually under the more official name of Secure Storage Connector :).

2023-11-02 20:01 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +W&B suggests that you set the number of bucket version copies to 1 because it helps reduce storage costs and can help recover accidentally deleted data.
Alright - new plot twist - some customers have been asking for docs for how to set copies to 1 for different cloud providers, so we might want to consider offering these instructions in advance alongside the rec:
- AWS - s3 - [thread](https://weightsandbiases.slack.com/archives/C02CXJ3RSBA/p1698954505201239?thread_ts=1698698101.973919&cid=C02CXJ3RSBA)
- GCP - [thread](https://weightsandbiases.slack.com/archives/C02CXJ3RSBA/p1698954780087209?thread_ts=1698698101.973919&cid=C02CXJ3RSBA)
- Azure - [thread](https://weightsandbiases.slack.com/archives/C02CXJ3RSBA/p1698954865643569?thread_ts=1698698101.973919&cid=C02CXJ3RSBA)

One thing we should consider - maybe we should pull out 'set copies to 1' recommendation into a different PR since it is a recommendation and I don't want it to block shipping the docs for actual requirements - what do you think?

2023-11-02 20:04 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +W&B suggests that you set the number of bucket version copies to 1 because it helps reduce storage costs and can help recover accidentally deleted data.
@noaleetz I agree. Let me remove that recommendation for now. That'll let me wrap my brain around the new plot twists. 😅

2023-11-02 20:38 UTC, merged

2023-11-02 21:45 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +:::note
Ok so as discussed - we will remove the recommendation of setting copies to 1.

2023-11-02 21:46 UTC, noaleetz commented
oh wait this was merged?

2023-11-02 21:47 UTC, noaleetz commented
1. We need @szymon-piechowicz-wandb to review
2. Folks on SSC need to also enable versioning
3. Add a note in SSC docs to point to instructions here

2023-11-02 23:21 UTC, ngrayluna commented
@szymon-piechowicz-wandb Here is what I merged in.  Does this get your seal of approval?
<img width="601" alt="Screen Shot 2023-11-02 at 4 20 33 PM" src="https://github.com/wandb/docodile/assets/15202580/750e997f-fb12-40d7-8384-20502ee86cac">