Add disclaimer that storing secrets via k8s delegates security to customer
wandb/docs pull request #463
Opened 2023-10-31 00:10 UTC by ngrayluna

## Description

First draft of note about delegating responsibility to customers for managing secrets.

## Ticket

https://wandb.atlassian.net/browse/DOCS-795?atlOrigin=eyJpIjoiNDM0NDNjODYyOWViNGU4YTlmOWNmOGI5ODUzZWE4YWMiLCJwIjoiaiJ9

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-11-01 23:25 UTC, noaleetz commented on docs/guides/model_registry/automation.md
> +You are responsible for configuring security measures that satisfy your security needs. W&B strongly recommends that you use a secrets manager provided by AWS, GCP, or Azure. Secret managers provided
The very last thing I would specify: a user cannot bring their own secret store (for example their own instance of Azure Key Vault). We store secrets in a **W&B** **instance** of the cloud provider's respective secrets manager. The user cannot bring their own secret store ([thread](https://weightsandbiases.slack.com/archives/C05GS5F8TNU/p1698690405841979?thread_ts=1698422606.394809&cid=C05GS5F8TNU))

2023-11-01 23:27 UTC, noaleetz commented on docs/guides/model_registry/automation.md
> +You are responsible for configuring security measures that satisfy your security needs. W&B strongly recommends that you use a secrets manager provided by AWS, GCP, or Azure. Secret managers provided
Maybe we should throw out k8s as an option in this line: 
Before - W&B strongly recommends that you use a secrets manager provided by AWS, GCP, or Azure

After -  W&B strongly recommends that you use a secrets manager provided by AWS, GCP, or Azure, though Kubernetes is offered as a fallback to server as a secrets backend.

2023-11-01 23:28 UTC, noaleetz requested changes
last round of changes! I will also ask @andrewtruong for a review!

2023-11-02 01:17 UTC, ngrayluna commented
Preview here: 


<img width="561" alt="Screen Shot 2023-11-01 at 6 16 17 PM" src="https://github.com/wandb/docodile/assets/15202580/569b4cd5-ca35-481d-b516-dd16b19c06f4">

2023-11-02 04:38 UTC, noaleetz approved these changes
lgtm!!! Lets just got a review from @gls4 @andrewtruong and we should be good to go :). 

Note that AWS integration will be coming soon - so in a few weeks might have to update

2023-11-02 13:43 UTC, andrewtruong approved these changes

2023-11-02 19:29 UTC, noaleetz commented
Got sign-offs from security: @rilwansogbesan and @wandb-kc - [thread](https://weightsandbiases.slack.com/archives/C05754EPT26/p1698948110903129?thread_ts=1696275892.199469&cid=C05754EPT26)

2023-11-02 19:30 UTC, wandb-kc approved these changes

2023-11-02 19:31 UTC, rilwansogbesan approved these changes

2023-11-02 19:42 UTC, merged