Add note to SSC+Server about garbage collection
wandb/docs pull request #470
Opened 2023-11-06 16:46 UTC by ngrayluna

## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-11-06 16:46 UTC, ngrayluna commented
Preview:
<img width="553" alt="Screen Shot 2023-11-06 at 8 45 25 AM" src="https://github.com/wandb/docodile/assets/15202580/381209e6-d964-4dec-97fb-a8c697b42309">

2023-11-06 19:38 UTC, noaleetz commented on docs/guides/hosting/secure-storage-connector.md
> +:::
Hey @ngrayluna - we need to add a section in the actual GC/deletion docs explaining how to enable GC for SSC (BYOB) - this different than for W&B Server. For dedicated cloud w/ SSC/BYOB - versioning needs to be enabled (no env variable needs to be set). 

Can we add this into this PR? This is re the comment I left [here](https://github.com/wandb/docodile/pull/462#issuecomment-1789846969). Then, the section above needs to be edited to link to that section (enabling GC for dedicated cloud on BYOB). 

TLDR 
- cloud and dedicated cloud (without BYOB) - GC is enabled by default
- dedicated cloud WITH BYOB - no env variable to set, **only** enabling versioning
- server - set env var AND enable versioning (both required)
we need to distinguish the requirements for dedicated w BYOB and Server in the GC docs and then link to relevant section

2023-11-06 19:50 UTC, noaleetz requested changes
left a comment re distinguishing requirements for GC for byob and server

2023-11-06 23:34 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +<!-- :::note
Note: This is commented out. Does not show up on docs.

2023-11-06 23:35 UTC, ngrayluna commented
Preview of "Delete artifact" page w/ GC section: 
[Delete W&B Artifacts.pdf](https://github.com/wandb/docodile/files/13273556/Delete.W.B.Artifacts.pdf)

2023-11-08 01:18 UTC, abhinavg6 requested changes
Added some comments and requested a few edits.

2023-11-08 01:18 UTC, abhinavg6 commented on docs/guides/artifacts/delete-artifacts.md
> +| Dedicated cloud with secure storage container  |                      | X                 |
For dedicated, the customer should ask their account team to enable the environment variable, and then configure the bucket versioning / soft deletion in their bucket (only for AWS/Azure). We should reflect that, so customer doesn't think that they could somehow edit that env variable themselves.

2023-11-08 01:18 UTC, abhinavg6 commented on docs/guides/artifacts/delete-artifacts.md
> +* Enable bucket versioning if you use [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/manage-versioning-examples.html), [GCP](https://cloud.google.com/storage/docs/object-versioning) or a
Should probably indicate that there's no secure storage connector with Azure, so it doesn't apply to dedicated cloud. Maybe as a note.

2023-11-08 01:18 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +A cloud storage bucket can be configured only once for a team at the time of team creation. To provision a bucket, W&B recommends that you use a Terraform configuration managed by W&B for [AWS](https
```suggestion
A cloud storage bucket can be configured only once for a team at the time of team creation. To provision a bucket, W&B recommends that you use a Terraform module managed by W&B for [AWS](https://github.com/wandb/terraform-aws-wandb/tree/main/modules/secure_storage_connector) or [GCP](https://github.com/wandb/terraform-google-wandb/tree/main/modules/secure_storage_connector).
```

2023-11-08 01:18 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +:::
I added one comment related to that table in the other file.

2023-11-08 01:18 UTC, abhinavg6 commented on docs/guides/artifacts/delete-artifacts.md
> +## How to enable garbage collection based on how you host W&B
```suggestion
## How to enable garbage collection based on how W&B is hosted
```

2023-11-08 01:18 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
>  Select **External Storage** when you create a team tp configure a cloud storage bucket. Select your provider and fill out your bucket name and storage encryption key ID, if applicable, and select **C
```suggestion
Select **External Storage** when you create a team to configure a cloud storage bucket. Select your provider and fill out your bucket name and storage encryption key ID, if applicable, and select **Create Team**.
```

2023-11-08 01:18 UTC, abhinavg6 commented on docs/guides/artifacts/delete-artifacts.md
> +* Enable bucket versioning if you use [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/manage-versioning-examples.html), [GCP](https://cloud.google.com/storage/docs/object-versioning) or a
Basically it would apply for Azure only with Customer managed cloud and for the deployment-level bucket (there are no team-level Azure buckets yet).

2023-11-08 19:18 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +* Enable bucket versioning if you use [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/manage-versioning-examples.html), [GCP](https://cloud.google.com/storage/docs/object-versioning) or a
We have a note at the top of the secure storage connector page: https://docs.wandb.ai/guides/hosting/secure-storage-connector Does that suffice? 
<img width="609" alt="Screen Shot 2023-11-08 at 11 17 27 AM" src="https://github.com/wandb/docodile/assets/15202580/9df03cb9-d371-4609-85c1-a160795d6565">

2023-11-08 19:35 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +| Dedicated cloud with secure storage container  |                      | X                 |
Added: 

"By default, dedicated cloud with secure storage connector can not edit the `GORILLA_ARTIFACT_GC_ENABLED` environment variable. Ask your account team to enable the environment variable. 

In addition, W&B encourages dedicated cloud users (with secure storage connector) to ask their account team to enable the environment variable before you enable bucket versioning (AWS, GCP, and so on) or soft deletion (Azure).
"

2023-11-08 19:57 UTC, abhinavg6 requested changes
Sorry, added a few more comments requesting changes.

2023-11-08 19:57 UTC, abhinavg6 commented on docs/guides/artifacts/delete-artifacts.md
> +* Enable bucket versioning if you use [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/manage-versioning-examples.html), [GCP](https://cloud.google.com/storage/docs/object-versioning) or a
Yeah I had seen that, but I feel we should add a simple note here as well since we're talking about enabling stuff on that cloud. Just so that if anyone just reads this page and doesn't go to the W&B hosting page, they can know right here itself.

2023-11-08 19:57 UTC, abhinavg6 commented on docs/guides/artifacts/delete-artifacts.md
> +By default, dedicated cloud with secure storage connector can not edit the `GORILLA_ARTIFACT_GC_ENABLED` environment variable. Ask your account team to enable the environment variable.
```suggestion
By default,  `GORILLA_ARTIFACT_GC_ENABLED` environment variable is not enabled on dedicated cloud with secure storage connector. Ask your account team to enable the environment variable, preferably before you enable versioning for your bucket. 
```

2023-11-08 19:57 UTC, abhinavg6 commented on docs/guides/artifacts/delete-artifacts.md
> +In addition, W&B encourages dedicated cloud users (with secure storage connector) to ask their account team to enable the environment variable before you enable bucket versioning (AWS, GCP, and so on
I think we could remove this, if you accept the above suggestion,

2023-11-08 19:57 UTC, abhinavg6 commented on docs/guides/artifacts/delete-artifacts.md
> +| Dedicated cloud with secure storage connector  |                      | X                 |
Actually enable versioning should be X for dedicated cloud with secure storage connector too, right?

2023-11-08 19:57 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +W&B uses a garbage collection process to delete W&B artifacts. For more information on how W&B deletes artifacts, and for information on how to enable garbage collection for secure storage container
```suggestion
W&B uses a garbage collection process to delete W&B artifacts. For more information on how W&B deletes artifacts, and for information on how to enable garbage collection for secure storage container see the [How to enable garbage collection based on how you host W&B](../artifacts/delete-artifacts.md#how-to-enable-garbage-collection-based-on-how-wb-is-hosted) page.
```

2023-11-08 20:17 UTC, noaleetz commented on docs/guides/hosting/secure-storage-connector.md
> +W&B uses a garbage collection process to delete W&B artifacts. For more information on how W&B deletes artifacts, and for information on how to enable garbage collection for secure storage container
we should specify that this is how to hard-deletion (not delete in general via. delete() in API or delete in UI) since deletion guides focuses on soft delete. This

2023-11-08 20:17 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +| Dedicated cloud with secure storage container  |                      | X                 |
@szymon-piechowicz-wandb @jlzhao27 I had understood this isn't something the user needs to do and that we by default turn on this env variable for dedicated, no? If not, I think we should enable it by default. It is going to introduce a lot of friction if they need to go to their account team and the account team has to figure out how to do this, etc. Is there a reason not to enable it by default for all dedicated cloud instances?

2023-11-08 20:17 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +* Enable bucket versioning if you use [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/manage-versioning-examples.html), [GCP](https://cloud.google.com/storage/docs/object-versioning) or a
Gotcha - good point - @ngrayluna should we add a note in the table or at the end that if you're on Azure the row dedicated cloud with SSC is not relevant for you - dedicated cloud with SSC is not an option for Azure buckets

2023-11-08 21:43 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +| Dedicated cloud with secure storage connector  |                      | X                 |
It is:
<img width="544" alt="Screen Shot 2023-11-08 at 1 42 28 PM" src="https://github.com/wandb/docodile/assets/15202580/991c0fe1-a467-490e-b26d-348ce687eac8">

2023-11-08 22:29 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +By default, dedicated cloud with [secure storage connector](../hosting/secure-storage-connector.md) can not edit the `GORILLA_ARTIFACT_GC_ENABLED` environment variable. Ask your account team to enabl
this can be removed. we will be turning it on for those we can set the var for (we be on by default after terraform changes go through)

2023-11-08 22:31 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +| Customer managed on-prem                       | X                       | X                 |
I am not sure if this is the best place for this table - this needs to go in the same place we show people the instructions for enabling versioning and setting the environment variable. This should likely be in the section where we talk about enabling GC on different hosting types.

2023-11-08 22:33 UTC, noaleetz commented on docs/guides/hosting/secure-storage-connector.md
> +W&B uses a garbage collection process to delete W&B artifacts. For more information on how W&B deletes artifacts, and for information on how to enable garbage collection for secure storage container
for secure storage container OR on customer-managed deployment types

2023-11-08 22:35 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +| Customer managed on-prem                       | X                       | X                 |
We should note in these docs - if you are on saas/shared cloud or dedicated cloud - garbage collection is enabled by default (you do not have to do anything). Unless you use SSC, in that case, learn more in this section (how to enable gc based on how you host gc section, containing the matrix)

2023-11-08 22:36 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +:::
since we are removing any note of ssc in this guide - this should be moved into where we mention enabling GC for SSC

2023-11-08 22:37 UTC, noaleetz commented on docs/guides/hosting/secure-storage-connector.md
> +W&B uses a garbage collection process to delete W&B artifacts. For more information on how W&B deletes artifacts, and for information on how to enable garbage collection for secure storage container
the doc linked should have the table which covers both SSC and customer-managed / local deployments

2023-11-08 22:37 UTC, noaleetz requested changes
left comments

2023-11-08 22:46 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +| Customer managed on-prem                       | X                       | X                 |
I agree that this section, nor this table,  should not exist here. It should go in a separate page in Server. E.g. [See this thread](https://weightsandbiases.slack.com/archives/C064WHTC6L9/p1699316278423919).

My thinking is that we leave it here for now and make a note to remove it .

2023-11-08 22:50 UTC, ngrayluna commented on docs/guides/hosting/secure-storage-connector.md
> +W&B uses a garbage collection process to delete W&B artifacts. For more information on how W&B deletes artifacts, and for information on how to enable garbage collection for secure storage container
Can't link to a table directly, unfortunately. Only section titles

2023-11-08 22:52 UTC, ngrayluna commented on docs/guides/artifacts/delete-artifacts.md
> +:::
This is a to do for the future. Right now I am not creating another page for this PR

2023-11-08 22:57 UTC, ngrayluna commented
Updated:
[Delete W&B Artifacts.pdf](https://github.com/wandb/docodile/files/13302089/Delete.W.B.Artifacts.pdf)

Note: we are leaving how to enable GC in artifacts docs for now. This will be removed to Server in the future.

2023-11-09 04:26 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
>  The sections in this page describe how to delete specific artifact versions, how to delete an artifact collection, how to delete artifacts with and without aliases, and more. You can schedule when ar
```suggestion
The sections in this page describe how to delete specific artifact versions, how to delete an artifact collection, how to delete artifacts with and without aliases, and more. You can schedule when artifacts are deleted from W&B with TTL policies. For more information, see [Manage data retention with Artifact TTL policy](./ttl.md). Note that whether you schedule an artifact for deletion with a TTL policy, or delete it immediately via the SDK or UI, both result in a soft-deletion and be subject to garbage collection to be transitioned to a hard-deleted state. 
```

2023-11-09 04:31 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +| Shared cloud with secure storage connector     |                         | X                 |
```suggestion
| Shared cloud with [secure storage connector](https://docs.wandb.ai/guides/hosting/secure-storage-connector)     |                         | X                 | 
```

2023-11-09 04:31 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +| Dedicated cloud with secure storage connector  |                         | X                 |
```suggestion
| Dedicated cloud with [secure storage connector](https://docs.wandb.ai/guides/hosting/secure-storage-connector)  |                         | X                 | 
```

2023-11-09 04:34 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +By default, dedicated cloud with [secure storage connector](../hosting/secure-storage-connector.md) can not edit the `GORILLA_ARTIFACT_GC_ENABLED` environment variable.
I am wondering if we still need this note? Is the point here to emphasize that we need to enable it for you if on dedicated cloud?

2023-11-09 04:40 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +* Enable bucket versioning if you use [AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/manage-versioning-examples.html), [GCP](https://cloud.google.com/storage/docs/object-versioning) or a
This is a nit but I don't think we need to note that SSC is not available for azure. If the user is already on SSC they will already know this, and if they're not they will definitely go to the SSC page to learn more about it and figure that out. this page is on deleting artifacts so it is a bit redundant to add a warning on SSC availability in here. 

But if folks feel strongly I will concede on this one :). It is a nit. cc @abhinavg6 @ngrayluna

2023-11-09 04:43 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +By default, dedicated cloud with [secure storage connector](../hosting/secure-storage-connector.md) can not edit the `GORILLA_ARTIFACT_GC_ENABLED` environment variable.
I am thinking this might not be necessary to add since for both dedicated rows we say that setting the env var is not a requirement (since we will handle this for dedicated instances). So a user would not attempt to try to set it themselves.

2023-11-09 04:44 UTC, noaleetz requested changes
left a few more suggestions including adding hyperlinks for SSC in table

2023-11-09 17:08 UTC, ngrayluna commented
Updated: 
[Delete W&B Artifacts.pdf](https://github.com/wandb/docodile/files/13310888/Delete.W.B.Artifacts.pdf)

2023-11-09 17:18 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +Artifacts that are scheduled for deletion with a TTL policy, deleted with the W&B SDK, or deleted with the W&B App UI are first soft-deleted. Artifacts that are soft deleted undergo garbage collectio
```suggestion
Artifacts that are scheduled for deletion with a TTL policy, deleted with the W&B SDK, or deleted with the W&B App UI are first soft-deleted. Artifacts that are soft deleted undergo garbage collection before they are hard-deleted.
```

2023-11-09 20:35 UTC, abhinavg6 approved these changes
LGTM, thanks for the changes.

2023-11-16 23:18 UTC, noaleetz approved these changes
ready to go!

2023-11-17 19:15 UTC, szymon-piechowicz-wandb commented on docs/guides/hosting/intro.md
>  - [Slack Alerts](./slack-alerts.md) and more.
Move `and more.` to the last bullet point.

2023-11-17 19:21 UTC, szymon-piechowicz-wandb reviewed
We should add `GORILLA_ARTIFACT_GC_ENABLED` to https://docs.wandb.ai/guides/hosting/env-vars.

Btw, the documentation for `GORILLA_DATA_RETENTION_PERIOD ` there also needs to be improved. It says the data is deleted "immediately" but that's not true. That's exactly what the variable controls: the delay after a run is deleted, and before it gets garbage collected.

2023-11-20 18:27 UTC, merged