[WIP] Adds "Export Table Data" page
wandb/docs pull request #477
Opened 2023-11-09 16:03 UTC by katjacksonWB

## Description

Adds a page discussing how to download table data.

## Ticket

[DOCS-788](https://wandb.atlassian.net/browse/DOCS-788)

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [x] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [x] I merged the latest changes from `main` into my feature branch before submitting this PR.

[DOCS-788]: https://wandb.atlassian.net/browse/DOCS-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-11-09 22:13 UTC, ngrayluna requested changes
Update links

2023-11-09 22:13 UTC, ngrayluna commented on docs/guides/tables/tables-download.md
> +- Check out the [reference documentation](/guides/artifacts/construct-an-artifact.md) on `artifacts`.
Use relative links, eg. for the first one it would be [reference documentation](../artifacts/construct-an-artifact.md)

2023-11-13 22:55 UTC, jackwandb approved these changes

2023-11-14 21:11 UTC, katjacksonWB commented
@ngrayluna Does this look good to merge?

2023-11-16 03:22 UTC, ngrayluna approved these changes

2023-11-16 03:22 UTC, merged