[WIP] Changes to Prompts Landing page and sidebar.
wandb/docs pull request #478
Opened 2023-11-09 16:44 UTC by katjacksonWB

## Description

Adds more content to the "Prompts Platform" page to give users more context about W&B's LLM offerings. ~~Also, changes the page category name to "LLMs" and changes the information architecture of the page for better flow.~~
## Ticket

[DOCS-772](https://wandb.atlassian.net/browse/DOCS-772)

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [x] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [x] I merged the latest changes from `main` into my feature branch before submitting this PR.

[DOCS-772]: https://wandb.atlassian.net/browse/DOCS-772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-11-09 18:23 UTC, ngrayluna commented on docs/guides/prompts_platform.md
> +- (Coming soon) Use this monitored data to improve your pipeline by providing feedback and fine-tuning or evaluating with it.
Edit this line to make it timeless. https://developers.google.com/style/timeless-documentation?hl=en

2023-11-09 18:24 UTC, ngrayluna commented on docs/guides/prompts_platform.md
> +- Individuals can filter and drill down to analyze prompt performance, observe all inputs sent to the prompt and track custom metrics to use for analysis
Replace "Individuals" with "you".  https://developers.google.com/style/person?hl=en

2023-11-09 18:26 UTC, ngrayluna requested changes
See comments

2023-11-09 21:50 UTC, ngrayluna commented on docs/guides/prompts_platform.md
> +Evaluating the performance of Large Language Models (LLMs) can be difficult. Weights and Biases offers several tools to streamline the evaluation process, providing a visual way to analyze your gener
Replace all instances of "Weights & Biases" with "W&B"

2023-11-09 21:58 UTC, ngrayluna commented on docs/guides/prompts_platform.md
> +Evaluating the performance of Large Language Models (LLMs) can be difficult. Weights and Biases offers several tools to streamline the evaluation process, providing a visual way to analyze your gener
This sentence 

"Weights and Biases offers several tools to streamline the evaluation process, providing a visual way to analyze your generative models."

is a little confusing. Suggest breaking it up into two or simplifying it? E.g. 

"Use W&B [BLANK and BLANK] to evaluate Large Language Models (LLMS) and analyze generative models".

or 

"Use W&B Prompts to visualize...". Monitor your large language models with LLM Monitoring.

2023-11-09 21:59 UTC, ngrayluna commented on docs/guides/prompts_platform.md
> +[W&B Prompts](/guides/prompts) is a suite of LLMOps tools built for the development of LLM-powered applications. Use W&B Prompts to visualize and inspect the execution flow of your LLMs, analyze the
Missing complete markdown file path

2023-11-09 21:59 UTC, ngrayluna commented on docs/guides/prompts_platform.md
> +[LLM Monitoring](/guides/weave/prod-mon) provides large language model usage monitoring and diagnostics. Start simply, then customize and evolve your monitoring analytics over time.
Missing full markdown path

2023-11-09 22:01 UTC, ngrayluna commented on docs/guides/prompts_platform.md
> +- [LangChain](https://docs.wandb.ai/guides/integrations/langchain)
Ah, to reference other docs you'll want to do relative markdown linking:  e.g. [Langchain](./integrations/langchain.md)

Do the same for the others.

2023-11-09 22:02 UTC, ngrayluna commented on docs/guides/prompts_platform.md
> +- Check out more detailed documentation on [Prompts](/guides/prompts) or [LLM Monitoring](/guides/weave/prod-mon).
Add full path.

2023-11-09 22:02 UTC, ngrayluna requested changes
Requested changes.

2023-11-14 21:10 UTC, katjacksonWB commented
@ngrayluna Does this look good to merge?

2023-11-16 03:20 UTC, ngrayluna requested changes
Fix paths

2023-11-16 03:20 UTC, ngrayluna commented on docs/guides/prompts_platform.md
> +[W&B Prompts](prompts/intro.md) is a suite of LLMOps tools built for the development of LLM-powered applications. Use W&B Prompts to visualize and inspect the execution flow of your LLMs, analyze the
Add "./" to paths. E.g. (./prompts/intro.md) to make it explicit.

2023-11-20 18:29 UTC, ngrayluna commented
@katjacksonWB Let me know if you have any questions. Would be great to ship this out this week :)

2024-02-26 21:19 UTC, merged