Minikube-tutorial
wandb/docs pull request #482
Opened 2023-11-15 06:51 UTC by bcsherma

## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-11-16 00:39 UTC, cvphelps commented
@ngrayluna Ben is making some edits here, so this one can wait until next week when you're back in the office

2023-11-21 19:46 UTC, ngrayluna requested changes
@bcsherma Did an edit pass and pushed said edits to your branch. Can you review and edit the comment I made? When we get that in, we can merge and ship it.

2023-11-21 19:46 UTC, ngrayluna commented on docs/tutorials/minikube_gpu.md
> +If you use Docker queues for workloads running on a single host, there is a compelling reason to use a Kubernetes queue with an agent connected to a local Kubernetes cluster instead: GPU scheduling.
This intro paragraph was a bit confusing. Can you re word it, simplify, condense it?

2023-11-27 18:39 UTC, tristan-spaulding2 commented
If possible and there are no blocking comments, could we ship this update today / tomorrow?  This guide is quite powerful and I'm working with marketing to do a small push that would direct attention to our support here.  Thanks.

2023-11-27 19:12 UTC, bcsherma commented
> If possible and there are no blocking comments, could we ship this update today / tomorrow? This guide is quite powerful and I'm working with marketing to do a small push that would direct attention to our support here. Thanks.

Yep, I think I just need to address this one comment from @ngrayluna

2023-11-27 20:13 UTC, bcsherma commented on docs/tutorials/minikube_gpu.md
> +If you use Docker queues for workloads running on a single host, there is a compelling reason to use a Kubernetes queue with an agent connected to a local Kubernetes cluster instead: GPU scheduling.
Agreed, not my finest work xD 

I've reworked it, lmk what you think

2023-11-27 23:12 UTC, ngrayluna approved these changes

2023-11-27 23:17 UTC, merged