Webhooks - Add more info in github actions payload example
wandb/docs pull request #493
Opened 2023-11-28 22:12 UTC by ngrayluna

## Description
Webhooks - Add more info in github actions payload example

## Ticket

https://wandb.atlassian.net/browse/DOCS-813?atlOrigin=eyJpIjoiZmIyMzk0MGQwZWJiNGUyYWFiZDQxNmM1OWQ2MWFlNGQiLCJwIjoiaiJ9

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-11-28 22:13 UTC, ngrayluna commented
Preview:

<img width="946" alt="Screen Shot 2023-11-28 at 2 11 33 PM" src="https://github.com/wandb/docodile/assets/15202580/8ba9472f-1fcf-43f6-86b5-f4d9fbd901af">

2023-11-28 22:14 UTC, ngrayluna commented
@noaleetz V1 draft created. 

Note: I'll duplicate the changes to the Artifacts Automation page when we finalize the wording on this (Model Reg -> Automation) page.

2023-11-29 21:05 UTC, noaleetz commented on docs/guides/model_registry/automation.md
>    Where template strings render depending on the event or model version the automation is configured for. `${event_type}` will render as either "LINK_ARTIFACT" or "ADD_ARTIFACT_ALIAS". See below for
```suggestion
  Where template strings render depends on the event or model version the automation is configured for. `${event_type}` will render as either "LINK_ARTIFACT" or "ADD_ARTIFACT_ALIAS". See below for an example mapping:
```
@ngrayluna for some reason this sentence is troubling me - should it be depends?

2023-11-29 21:06 UTC, noaleetz commented on docs/guides/model_registry/automation.md
> +The `event_type` key in the automation payload must match the `types` field in the GitHub workflow YAML file.
```suggestion
The `event_type` key in the webhook payload must match the `types` field in the GitHub workflow YAML file.
```

2023-11-29 21:07 UTC, noaleetz requested changes
left a few nits - will also ask Ken to review.

2023-11-30 21:46 UTC, ngrayluna commented
@noaleetz Incorporated your feedback.

2023-11-30 21:58 UTC, noaleetz commented on docs/guides/model_registry/automation.md
> +  Where template strings render depend on the event or model version the automation is configured for. `${event_type}` will render as either "LINK_ARTIFACT" or "ADD_ARTIFACT_ALIAS". See below for an
```suggestion
The contents and positioning of the rendered template strings depends on the event or model version the automation is configured for. ${event_type} will render as either "LINK_ARTIFACT" or "ADD_ARTIFACT_ALIAS". See below for an example mapping:
```

2023-11-30 22:01 UTC, noaleetz requested changes
Can we add whatever changes are reflected here also inside the artifact / project level webhooks doc? https://docs.wandb.ai/guides/artifacts/project-scoped-automations#create-a-webhook-automation

2023-11-30 22:31 UTC, kenleejr commented
Looks good to me!

2023-11-30 22:33 UTC, kenleejr approved these changes
Looks good to me!

2023-11-30 23:21 UTC, noaleetz approved these changes
lgtmmmmmmmmm

2023-11-30 23:21 UTC, merged