docs(launch): how launch handles git urls
wandb/docs pull request #496
Opened 2023-11-29 21:48 UTC by bcsherma

## Description

Adding docs for how git remote urls are handled within Launch.
## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [x] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [x] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-12-07 17:58 UTC, ngrayluna commented on docs/guides/launch/setup-agent-advanced.md
> +### Git repository credentials
Let's provide a very basic example of how this might look like for a common use case/repo provider.

2023-12-07 17:58 UTC, ngrayluna commented on docs/guides/launch/create-launch-job.md
> +### Git remote url handling
For my understanding, how does git remote handling work in the case where a job is created from a git commit?

2023-12-07 19:00 UTC, bcsherma commented on docs/guides/launch/create-launch-job.md
> +### Git remote url handling
This is a bit below
"If your job is being created automatically by a W&B run, the git remote url will be automatically inferred from the local git repository. If you are creating a job manually, you are responsible for providing the url in the desired format."

2024-02-05 19:58 UTC, ngrayluna commented on docs/guides/launch/create-launch-job.md
> +If you create a job manually, you are responsible for providing the URL in the desired format. For more information, see [LINK].
Let's elaborate on this. Temporarily added "For more information, see [LINK]..." as a placeholders.

2024-02-05 19:59 UTC, ngrayluna commented on docs/guides/launch/setup-agent-advanced.md
> +Follow your repository provider's documentation to create a credential that the agent can use to access the repository.
Same here. Let's give an example or elaborate more on this.

2024-02-05 20:01 UTC, ngrayluna commented on docs/guides/launch/create-launch-job.md
> +| Remote URL | Requirements for access and authentication |
Created a table for quick view.  Anything else we should add?

PS we don't need a table, but let's be more specific (with an example or two) so that users can get a concrete sense of what to do, what to look for based on their git hosting provider.

2024-02-05 20:02 UTC, ngrayluna requested changes
Looking good. Left some comments related to specificity.

2024-02-06 17:13 UTC, bcsherma commented on docs/guides/launch/create-launch-job.md
> +| Remote URL | Requirements for access and authentication |
Is this table supposed to have a column for hosting provider?

2024-02-06 17:13 UTC, bcsherma commented on docs/guides/launch/create-launch-job.md
> +If you create a job manually, you are responsible for providing the URL in the desired format. For more information, see [LINK].
I'm not sure what this link is supposed to go to

2024-02-06 17:16 UTC, bcsherma commented on docs/guides/launch/setup-agent-advanced.md
> +Follow your repository provider's documentation to create a credential that the agent can use to access the repository.
I'm not sure what you want an example of or elaboration on

2024-02-09 17:59 UTC, KyleGoyette commented on docs/guides/launch/setup-agent-advanced.md
> +Follow your repository provider's documentation to create a credential that the agent can use to access the repository.
IMO this is already a lot of elboration, we're making it clear that you need to set your agent up with the credentials. There's a ton of ways to do that, elaborating will almost certainly lead users to believe we are overly prescriptive

2024-02-09 18:21 UTC, bcsherma commented on docs/guides/launch/create-launch-job.md
> +| Remote URL | Requirements for access and authentication |
This isn't something that will vary by hosting provider, I think https and ssh supported by every major provider, though if they have a local git server it may be one or the other. But in that case I think the user will understand these docs

2024-02-09 18:49 UTC, KyleGoyette commented on docs/guides/launch/create-launch-job.md
> +| Remote URL | Requirements for access and authentication |
git authenticiation protocol's are ubiquitous, and differnet users will have a lot of different ways that they may want to do this. Adding examples of of how users can attach auth protocols to the agent will confuse users, and add noise to our docs. I'd rather keep this concise, tell them they can use these 2 protocols at most we can link to a page like this: https://docs.github.com/en/authentication/connecting-to-github-with-ssh and indicate users follow these instructions on the agent machine.

All we are trying to say is: Give your agent credentials to access your repo, these are the two protocols we support, your URL format must match the creds protocol your agent is set up with. I'd rather start overly simple and iterate by adding more than add too much initially and have more to maintain, and confuse users by making our docs seem overly prescriptive.

2024-02-09 18:49 UTC, KyleGoyette approved these changes

2024-02-09 23:51 UTC, ngrayluna approved these changes

2024-02-09 23:54 UTC, merged