Log models
wandb/docs pull request #504
Opened 2023-12-04 21:57 UTC by ngrayluna

## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-12-04 22:09 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
> +The APIs listed on this page are not intended for [INSERT].
@noaleetz Wondering if it makes sense to also call out (explicitly) when not to use these APIs.?

2023-12-04 22:11 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Use W&B to log models that are created from W&B runs.
```suggestion
Use W&B to log models to your experiments.
```
'created from W&B runs' doesn't make too much sense since you're not created a model from a run - you can also log a model to a model file that already exists and was created elsewhere

2023-12-04 22:12 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +The following APIs are useful for early model exploration and experiment tracking. Use the APIs listed on this page to quickly log models to a run, in addition to metrics, tables, media and other obj
```suggestion
The following APIs are useful for tracking models as a part of your experiment tracking workflow. Use the APIs listed on this page to quickly log models to a run, in addition to metrics, tables, media and other objects.
```

2023-12-04 22:17 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +The APIs listed on this page are not intended for [INSERT].
I don't think we need call out a reason not to use this - we already give context on when to use artifacts and jump to the docs which has enough context

2023-12-04 22:23 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +W&B suggests that you use W&B Artifacts if you want to:
```suggestion
For more advanced versioning use cases, W&B suggests that you visit [W&B Artifacts](https://docs.wandb.ai/guides/artifacts) instead of these model APIs if you want to:
```

2023-12-04 22:24 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +- Create and keep track of different versions of serialized data such as models, datasets, prompts, and more.
```suggestion
- Create and keep track of different versions of serialized data beyond models, such as datasets, prompts, and more.
```

2023-12-04 22:37 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +- How to interact with the model artifacts these methods created, such as updating properties (metadata, aliases, and descriptions)
```suggestion
- How to interact with the model artifacts these methods created, such as [updating properties](https://docs.wandb.ai/guides/artifacts/update-an-artifact) (metadata, aliases, and descriptions) 
```

2023-12-04 22:39 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +- Create lineage graphs of a model or any other objects tracked in W&B.
```suggestion
- Explore [lineage graphs](https://docs.wandb.ai/guides/artifacts/explore-and-traverse-an-artifact-graph) of a model or any other objects tracked in W&B.
```
these model apis still create artifacts with lineage - its more about connecting to how do you explore these graphs

2023-12-04 22:41 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +The following guide describes how to log and interact with models logged to a W&B run.
```suggestion
The following guide describes how to log and interact with models logged to a W&B run. You can use [this](https://colab.research.google.com/drive/1Nvgz4VQHMbr4hoVGeUdDVfHE2lHFpvbs) companion colab notebook for a complete example of how to use these APIs in your ML workflow. Note that each of the following methods will derive the project and entity from the Run.
```
we need to link the companion colab somewhere in this doc

2023-12-04 22:43 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +run = wandb.init(project=project, entity=entity)
```suggestion
run = wandb.init(project="<your-project-name>", entity="<your-entity>")
```

2023-12-04 22:43 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +project="<your-project-name>"
```suggestion
```

2023-12-04 22:43 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +entity="<your-entity>"
```suggestion
```

2023-12-04 22:45 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Declare a model artifact as an output of a run with the [`log_model`](../../../ref/python/run.md#logmodel) method. To do so, provide a name for your model artifact and the path where your model is sa
```suggestion
Use [log_model](../../../ref/python/run.md#logmodel) method to log a model artifact containing the contents inside the ‘path’ to an a run. It also marks it as an output to the run. You can see the full [lineage](https://docs.wandb.ai/guides/artifacts/explore-and-traverse-an-artifact-graph#docusaurus_skipToContent_fallback) graph of the model artifact by accessing the lineage tab inside the Artifacts view.
```

2023-12-04 22:49 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +run.log_model(model_name=model_artifact_name, path=path)
lets restrict this code block to 3 lines - I want this to be as simplified as possible - create a run, log model, and finish run. Rather than defining vars ahead of time lets stick them directly and keep this block to those 3 key lines. The whole point is to call out how quick and easy this is

2023-12-04 23:19 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +In the preceding code snippet, the model originally had a file name of `70154.h5` and was locally stored in the user's `/local/dir/` directory. When the user logged the model with `log_model`, they g
```suggestion
In the preceding code snippet, a path to the model file(s) `/local/dir/70154.h5` is passed in. This path can be a local file, directory, or [reference URI](https://docs.wandb.ai/guides/artifacts/track-external-files#amazon-s3--gcs--azure-blob-storage-references) to an external bucket such as `s3://bucket/path`. 

In this case, the path contains has a single model file name of `70154.h5` and is locally stored in the user's `/local/dir/` directory. When the user calls `log_model` on a run, the file `70154.h5` is stored in a model artifact with name "<your-model-name>" and can be accessed in a future run via [`use_model()`](../../../ref/python/run.md#usemodel)

To view the logged model artifact in the UI, users can navigate to the project the run belongs to and select the Artifacts tab in the left sidebar.
```

2023-12-04 23:22 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
> +The following guide describes how to log and interact with models logged to a W&B run.
Ooops. Missed that.

2023-12-04 23:29 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +run.log_model(model_name=model_artifact_name, path=path)
```suggestion
run.log_model(name="<your-model-name>", path="/local/dir/70154.h5")
```

2023-12-04 23:36 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +W&B suggests that you prepend the entity and name of the project your model was saved to.
we can remove this - we will pull this info from the run this is being called on in run.use_model
```suggestion
```

2023-12-04 23:42 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +The `use_model` function returns the path of downloaded artifact file(s). Keep track of this path, as you will need to have this path to link a model. In the preceeding code snippet, we stored the fi
```suggestion
The `use_model` function returns the path of downloaded artifact file(s). In the preceding code snippet, we stored the file path in a variable called `downloaded_model_path`. This path is the original path that was inputted in `log_model()`. Note that 'name’ must match a model artifact that was logged using log_model() under the same ‘name’. 

This function also marks the model artifact as an input to the run. You can see the full [lineage](https://docs.wandb.ai/guides/artifacts/explore-and-traverse-an-artifact-graph#docusaurus_skipToContent_fallback) graph of the model artifact by accessing the lineage tab inside the Artifacts view.
```
I don't think we need to mention the keeping track piece, lets decouple use and link and explain what is needed there

2023-12-04 23:45 UTC, noaleetz commented on docs/guides/track/log/log-models.md
Note that 'name' is the correct argument name for these methods (rather than model-name, I'm seeing that pop-up in a few places so want to make sure thats fixed or it will cause confusion!)

2023-12-04 23:55 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +run = wandb.init(project=project, entity=entity)
Lets just have 1 line here - its confusing to have a run that all it does is call use_artifact - we note elsewhere that entity and project are derived from the run (I specified this somewhere in the notion doc - lets make sure it also made it to the PR)
```suggestion
# Access and download model. Returns path to downloaded artifact
downloaded_model_path = run.use_model(name="<your-model-name>")
```

2023-12-04 23:56 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Use the `link_model` method to log model file(s) as a model [artifact](../../artifacts/intro.md) to a W&B run and link it to the [W&B Model Registry](../../model_registry/intro.md).
```suggestion
Use the `link_model` method to log model file(s) to a W&B run and link it to the [W&B Model Registry](../../model_registry/intro.md). 
```
no need to pull them into artifacts - the creation of a model artifact happens under the hood and we want them to complete the action and not get swept up into the confusion of artifacts

2023-12-04 23:57 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +
```
### What is the W&B Model Registry
Use the Model Registry to bookmark your best model checkpoints and centralize them across your team. The [[Model Registry](https://docs.wandb.ai/guides/model_registry)](https://docs.wandb.ai/guides/model_registry) allows you can organize your best models by task, manage model lifecycle, facilitate easy tracking and auditing throughout the ML lifecyle, and [[automate](https://docs.wandb.ai/guides/models/automation)](https://docs.wandb.ai/guides/models/automation) downstream actions with webhooks or jobs.
```

2023-12-05 00:04 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +When you link a model artifact to the registry, this creates a new version of that registered model. The new version is a pointer to the artifact version that exists in that project.
```suggestion
Linking a model to the Model Registry requires you to specify the name Registered Model it should be linked to. A Registered Model is a collection or folder of linked model versions in the Model Registry, typically representing a team’s ML task. If no Registered Model 'registered-model-name' exists, a new one will be created with this name. 

Linking is akin to 'bookmarking' or 'publishing' your model to this centralized team view. 
```

2023-12-05 00:06 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +The following code snippet is a continuation of the code snippet in [Download and use a logged model](#download-and-use-a-logged-model). The code snippet uses the
link model should not be described as a continuation of the other snippets - we should show someone how to pass in a brand new model path to illustrate the story around this being a 1 line function to log and link to registry (the use_model is skipped since you are going directly). 
```suggestion
```

2023-12-05 00:06 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +The proceeding code snippet shows how to link a model with the `link_model` API. The code snippet uses the `downloaded_model_path` variable defined in the [Download and use a logged model](#download-
```suggestion
The proceeding code snippet shows how to log and link a model in 1 line with the `link_model` API. 
```

2023-12-05 00:08 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +run.finish()
```suggestion
```

2023-12-05 00:11 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +                 linked_model_name=f"model_vit-{wandb.run.id}",
```suggestion
                 name="<your-model-name">, # optional name to assign to model artifact storing path contents
```

2023-12-05 00:12 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +                 registered_model_name="Industrial ViT",
```suggestion
                 registered_model_name="Fine-Tuned Review Autocompletion",
```

2023-12-05 00:14 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +run.link_model(path=downloaded_model_path,
```suggestion
run.link_model(path="/local/dir/fine-tuned-yelp.pt",
```

2023-12-05 00:15 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +                 aliases=["staging", "QA"])
```suggestion
                 aliases=["staging", "QA"])  # semantic ‘nicknames’ or identifiers for a linked model version
```

2023-12-05 00:25 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +```
```suggestion
```

In the preceding code snippet, a path to the model file(s) `/local/dir/fine-tuned-yelp.pt` is passed in. This path can be a local file, directory, or [reference URI](https://docs.wandb.ai/guides/artifacts/track-external-files#amazon-s3--gcs--azure-blob-storage-references) to an external bucket such as `s3://bucket/path`. 

In this case, the path contains has a single model file name of `/local/dir/fine-tuned-yelp.pt` and is locally stored in the user's `/local/dir/` directory. When `[link_model](https://docs.wandb.ai/ref/python/run#link_model)` is called on a run, the file `fine-tuned-yelp.pt` is stored in a model artifact with name "<your-model-name>" and linked to the Model Registry under the `Fine-Tuned Review Autocompletion` Registered Model. 

You can view the newly linked model by navigating the Model Registry. 
```

2023-12-05 00:46 UTC, noaleetz requested changes
big bunch of changes - lets condense the snippets to rely reflect that they are 1 lines. And we should double triple check arguments are all correct / aligned w what is shipping tomorrow!

2023-12-05 01:10 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
> +run = wandb.init(project=project, entity=entity)
Ah. So, we are migrating towards a model where all code snippets need to be "runnable"/executable. That is, if someone where to copy and paste it (and replace values with ``) that it'll run.

2023-12-05 01:40 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
> +The following code snippet is a continuation of the code snippet in [Download and use a logged model](#download-and-use-a-logged-model). The code snippet uses the
QQ: Do users need to upload a model to W&B before they link it? 

When I first wrote this, I had in mind the behavior of artifacts where you first need to upload it to W&B and then re-download it locally to do tracking of that artifact. 

So here, I thought that we had to download the model and then from there link it.

2023-12-05 01:41 UTC, ngrayluna commented
Pushed a whole bunch of changes. One thing I did was condense the code snippets, and leave a more thorough example in the example accordian menu thingys (see preview).

Note: Each code snippet should be complete/runnable. I.e. if someone where to copy and paste it (and replace values) it should have all the code they need to run it.

2023-12-05 03:56 UTC, noaleetz commented on docs/guides/track/log/log-models.md
>  The following guide describes how to log and interact with models logged to a W&B run.
```suggestion
The following guide describes how to log models to a W&B run and interact with them. 
```

2023-12-05 04:09 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +run = wandb.init(project=project, entity=entity)
Oi ok so I guess we should have
```suggestion
run = wandb.init(project="<your-project>", entity="<your-entity>")
downloaded_model_path = run.use_model(name="<your-model-name>")
# do stuff with model
run.finish()
```
How do we show using comments that a user should insert their code for whatever they want to do with the model and the finish the run? A comment block?

2023-12-05 05:17 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Use the [`log_model`](../../../ref/python/run.md#logmodel) method to log a model artifact. The `log_model` methods also marks the model artifact as an output of the run. Associating a model to a run
```suggestion
Use the [`log_model`](../../../ref/python/run.md#logmodel) method to log the file(s) under 'path' to a run. The `log_model` methods also marks the resulting model artifact as an output of the run. Associating a model to a run (with log_model, for example), enables you to track the lineage of the model. View the lineage of the model, such as the inputs and outputs of a run, within the W&B App UI. See the [Explore and traverse artifact graphs](../../artifacts/explore-and-traverse-an-artifact-graph.md) page within the [Artifacts](../../artifacts/intro.md) chapter for more information.
```

2023-12-05 05:22 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +run.log_model(model_name="<model_artifact_name>", path="<path-to-model>")
```suggestion
run.log_model(name="<model_artifact_name>", path="<path-to-model>")
```

2023-12-05 05:25 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Provide a name for your model artifact and the path where your model is saved to for the `model_name` and `path` parameters, respectively. Ensure to replace values enclosed in `<>` with your own.
```suggestion
Provide the path where your model file(s) are saved to the `path` parameter. The path can be a local file, directory, or [reference URI](../../artifacts/track-external-files.md#amazon-s3--gcs--azure-blob-storage-references) to an external bucket such as `s3://bucket/path`. 

Optionally, you can provide a name for the model artifact, a versioned directory where the files will be logged to under 'name'.  if `name` is not specified, This will default to the basename of the input path prepended with the run ID. 

Ensure to replace values enclosed in `<>` with your own.
```
path is the most critical argument, the rest are optional

2023-12-05 05:26 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +The path can be a local file, directory, or [reference URI](../../artifacts/track-external-files.md#amazon-s3--gcs--azure-blob-storage-references) to an external bucket such as `s3://bucket/path`.
```suggestion
```
added above

2023-12-05 05:30 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +model_artifact_name = "model.h5"
```suggestion
model_artifact_name = "fine-tuned-model"
```
model.h5 is a file name - a model artifact would likely not be named with a file extension - model artifacts can have many files that make them up.

2023-12-05 05:33 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +In the proceeding code snippet, a path to the model file(s) `/local/dir/70154.h5` is passed in.  When the user logged the model with `log_model`, they gave the model artifact a name of `model.h5`.
```suggestion
In the following code snippet, a path to the model file(s) `/local/dir/70154.h5` is passed in. When the user called `log_model`, a model artifact with name `fine-tuned-model` was created and the file `70154.h5` was added to it. . 
```

2023-12-05 05:38 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Provide the name of your model artifact to the `model_name` field for the `use_model` parameter. Ensure to replace other the values enclosed in `<>` with your own:
```suggestion
Provide the name of the model artifact where the model file(s) you are looking to retrieve are stored under. Note that if you did not define 'name' when originally logging the file(s) with `log_model`, the default name assigned is the basename of the input path, prepended with the run ID. Ensure to replace other the values enclosed in `<>` with your own:
```

2023-12-05 05:47 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +For example, the proceeding code snippet shows how to log a model with `log_model` method. First, the user defines a `model_name` variable that contains the full name of the model artifact. Then the
```suggestion
For example, the following code snippet shows how to log a model with `log_model` method. First, the user calls the `log_model` method to log the models' files under a model artifact 'name'. Then the user calls the `use_model` method to access and download the model file(s) under model artifact `name`. The path that is returned from the method is stored under `downloaded_model_path`.
```

2023-12-05 05:53 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +For example, the proceeding code snippet links the model created in previous code snippets to a W&B Model Registry called `"MNIST"`. To do this, the user called the `link_model` API and provided the
Can we revert to some of the previous explanations I had here for registered model (this is a different notion from the model registry - registered model is a type of folder, or artifact collection within the registry. I also want to keep in the explanation for aliases. 

Note here that the user has 2 options:
1. they can pass in a file path like /local/dir/never_been_logged.pt of a model - you don't necessarily need an old file path that was returned from use_model. 
2. they can pass in a file path that was returned from use_model

Note also that the correct parameter names are: path, registered-model-name, name, aliases

2023-12-05 05:56 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +The code shown in this example is a continuation of the code example shown in the dropdown of the [Download and use a logged model](#download-and-use-a-logged-model) section. The code in this example
I had a bunch of comments in previous iteration but link model should not be presented as a continuation of use model - re the 2 options [above](https://github.com/wandb/docodile/pull/504/files#r1414913358) - the use case where log_model had not been used and a new file path is being passed is the 1 we're aiming for

2023-12-05 05:58 UTC, noaleetz requested changes
please pay extra attention to removing consistent references to artifacts - we wanna abstract those out - and methods argument names, but we are close!!

2023-12-05 21:33 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +
can we add this block in as well?
```suggestion
### What is the W&B Model Registry
Use the Model Registry to bookmark your best model checkpoints and centralize them across your team. The [[Model Registry](https://docs.wandb.ai/guides/model_registry)](https://docs.wandb.ai/guides/model_registry) allows you can organize your best models by task, manage model lifecycle, facilitate easy tracking and auditing throughout the ML lifecyle, and [[automate](https://docs.wandb.ai/guides/models/automation)](https://docs.wandb.ai/guides/models/automation) downstream actions with webhooks or jobs.
```

2023-12-05 21:35 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +The APIs listed on this page are not intended for [INSERT].
I think I left a note elsewhere but I think the suggestions we share about are enough context to let the users decide and I don't want to rule out use cases where they might be useful. 

Suggesting as we do below where we recommend they should be used should be ok, thats my thinking!

2023-12-05 21:55 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +The following code snippet is a continuation of the code snippet in [Download and use a logged model](#download-and-use-a-logged-model). The code snippet uses the
I swear I thought I submitted a reply to this question but maybe I left it in the wrong thread. 

Short answer - no they do not. There are 2 cases:
1. log_model was never called and **this func acts as both a 2 in 1 - log and link**. It takes in the path, creates a new model artifact with the contents of the path, and links that artifact to the MR. So the contents do not need to have been previously logged as an artifact - a new artifact will be created under the hood and it will be linked. The idea is that you're only interacting with your file path as a key identifier of your contents rather than needing to rely on the artifact name. 
2. log_model already stored contents under path. 
- 2A: you pass in optional 'name' with the name you previously passed in when logging model. Since name matches an existing artifact it will be logged to it as a new version (if contents changed)
- 2B: you don't pass anything to name. We make a new model artifact and link it to the model registry - the same end result as in 1 happens where a new model artifact is created and contents added to it. 

I think the most straightforward story to tell is #1 (we should avoid workflows w too many optional parameters, i.e scenarios where users must pass in 'name' to following this workflow)

[Here](https://www.notion.so/wandbai/Model-logging-API-5d746ea5daa4486980c968a19dd3103a?pvs=4#fdb6d2e3fb6c4355a0d32e22605a5493) is more context under the hood how these wrappers work and what they do

2023-12-05 21:58 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +For example, the proceeding code snippet links the model created in previous code snippets to a W&B Model Registry called `"MNIST"`. To do this, the user called the `link_model` API and provided the
[This](https://github.com/wandb/docodile/pull/504#discussion_r1416322717) thread has a more complete explanation of the above

2023-12-05 21:59 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +The code shown in this example is a continuation of the code example shown in the dropdown of the [Download and use a logged model](#download-and-use-a-logged-model) section. The code in this example
[this](https://github.com/wandb/docodile/pull/504#discussion_r1416322717) thread has a more complete explanation of the above

2023-12-05 21:59 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +For example, the proceeding code snippet links the model created in previous code snippets to a W&B Model Registry called `"MNIST"`. To do this, the user called the `link_model` API and provided the
> Short answer - no they do not. There are 2 cases:
> 
> #1 log_model was never called and this func acts as both a 2 in 1 - log and link. It takes in the path, creates a new model artifact with the contents of the path, and links that artifact to the MR. So the contents do not need to have been previously logged as an artifact - a new artifact will be created under the hood and it will be linked. The idea is that you're only interacting with your file path as a key identifier of your contents rather than needing to rely on the artifact name.
> #2 log_model already stored contents under path.
> 2A: you pass in optional 'name' with the name you previously passed in when logging model. Since name matches an existing artifact it will be logged to it as a new version (if contents changed)
> 2B: you don't pass anything to name. We make a new model artifact and link it to the model registry - the same end result as in 1 happens where a new model artifact is created and contents added to it.
> I think the most straightforward story to tell is https://github.com/wandb/docodile/pull/1 (we should avoid workflows w too many optional parameters, i.e scenarios where users must pass in 'name' to following this workflow)

[Here](https://www.notion.so/wandbai/Model-logging-API-5d746ea5daa4486980c968a19dd3103a?pvs=4#fdb6d2e3fb6c4355a0d32e22605a5493) is more context under the hood how these wrappers work and what they do

2023-12-06 00:10 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
> +run = wandb.init(project=project, entity=entity)
I write this: "Ensure to replace other the values enclosed in <> with your own:"

2023-12-06 00:59 UTC, ngrayluna commented
@noaleetz Another round of edits. Refresh https://docs-beta.wandb.ai/guides/track/log/log-models to see changes.

2023-12-06 02:35 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Use the [`log_model`](../../../ref/python/run.md#logmodel) to log a model artifact that contains content within a directory you specify. The `log_model` methods also marks the resulting model artifac
```suggestion
Use the [`log_model`](../../../ref/python/run.md#log_model) to log your model file(s) to a run. The `[log_model]((../../../ref/python/run.md#log_model))` method also marks the resulting model artifact as an output of the W&B run. 
```
The hyperlink to the log model ref docs redirected to top of the page

2023-12-06 02:42 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Models that are associated to a W&B run enable you to track the lineage of that model. You can view the lineage of the model, such as the inputs and outputs of a run, within the W&B App UI. See the [
```suggestion
Marking models as input or output to a run enables you to track the lineage of that model. This includes a graph of the model's associations and dependencies which can be viewed in the W&B App UI. See the [Explore and traverse artifact graphs](../../artifacts/explore-and-traverse-an-artifact-graph.md) page within the [Artifacts](../../artifacts/intro.md) chapter for more information.
```

2023-12-06 02:46 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +See [`log_model`](../../../ref/python/run.md#logmodel) in the API Reference guide for more information on possible parameters.
```suggestion
See [`log_model`](../../../ref/python/run.md#log_model) in the API Reference guide for more information on possible parameters.
```

2023-12-06 02:48 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +In the proceeding code snippet, a path to the model file `/local/dir/70154.h5` is provided to the `path` parameter.
I think this might be a bit redundant / not needed (users will see this is happening in the code)

2023-12-06 02:53 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +run = wandb.init(project="MNIST_Exploration", entity="charlie")
```suggestion
run = wandb.init(project="llm-evaluation", entity="charlie")
```
matching the theme of fine-tuned-model

2023-12-06 02:54 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +
@ngrayluna should we add a placeholder comment that shows a model is being trained (i.e # insert model training code here) before we log the model to make the run seem more realistic?

2023-12-06 02:57 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Provide the name of the model artifact where the model file(s) you are looking to retrieve are stored for the `name` parameter. The name you provide must match the name of an existing logged model ar
```suggestion
Provide the name of the model artifact where the model file(s) you are looking to retrieve are stored for the `name` parameter. The name you provide must match the name of an existing logged model artifact. 
```
I think this is redundant with docstrings, in the example we use the :latest format.

2023-12-06 02:58 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +* `model_artifact_name:version`
```suggestion
```
see note [above](https://github.com/wandb/docodile/pull/504/files#r1416594085)

2023-12-06 02:58 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +* `model_artifact_name:alias`
```suggestion
```
see note [above](https://github.com/wandb/docodile/pull/504/files#r1416594085)

2023-12-06 02:58 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +* `model_artifact_name:digest`
```suggestion
```
see note [above](https://github.com/wandb/docodile/pull/504/files#r1416594085)

2023-12-06 02:59 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +You can optionally prepend the the W&B entity and project to the name. For example, the following is valid:
```suggestion
```
I don't this is necessary - I prefer not to include too much optional info, if we want we can use highlight in code snippet. This is also mentioned in docstrings.

2023-12-06 03:01 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +        )
re above we can remove this example, not necessary and adds more context for a beginner user to try to understand

2023-12-06 03:04 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +downloaded_model_path = run.use_model(name="<your-model-name>")
```suggestion
downloaded_model_path = run.use_model(name="<your-model-name>:v0")
```
I think either v0 or latest will be the only aliases we should mention that a user who has gotten this far will understand / easily be able to infer what its doing

2023-12-06 03:07 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +The `use_model` function returns the path of downloaded artifact file(s). Keep track of this path if you want to link this model later. In the preceding code snippet, the returned path is stored in a
```suggestion
The `use_model` function returns the path of downloaded model file(s). In the snippet below, the returned path is stored in a variable called `downloaded_model_path`.
```
this is the same path they used to log the model so they will have it on hand, if anything it is more important after log model to tell users to remember the 'name' they used since they will need it to fetch the path later.

2023-12-06 03:09 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Provide the path where your model file(s) are saved to the `path` parameter. The path can be a local file, directory, or [reference URI](../../artifacts/track-external-files.md#amazon-s3--gcs--azure-
```suggestion
Provide the path where your model file(s) are saved to the `path` parameter. The path can be a local file, directory, or [reference URI](../../artifacts/track-external-files.md#amazon-s3--gcs--azure-blob-storage-references) to an external bucket such as `s3://bucket/path`. Optionally provide a name for the model artifact for the `name` parameter. If `name` is not specified, W&B will use the basename of the input path prepended with the run ID as the name. Keep track of this 'name' as you will need to retrieve the model path with the `[use_model](https://docs.wandb.ai/ref/python/run#use_model)` method. 
```

2023-12-06 03:10 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +    registered_model_name="<model-registry-name>"
```suggestion
    registered_model_name="<registered-model-name>"
```

2023-12-06 03:21 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +registered_model_name = "MNIST"
```suggestion
registered_model_name = "Fine-Tuned Review Autocompletion"
```

2023-12-06 03:26 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +See [`link_model`](../../../ref/python/run.md#linkmodel) in the API Reference guide for more information on optional parameters.
i
```suggestion
See [`link_model`](../../../ref/python/run.md#link_model) in the API Reference guide for more information on optional parameters.
```

2023-12-06 03:31 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +You can think of linking a model similar to 'bookmarking' or 'publishing' a model that others members of your team can view.
```suggestion
You can think of linking a model as similar to 'bookmarking' or 'publishing' a model to a centralized team repository of models that others members of your team can view and consume. Note that linking a model to will not duplicate it in the Model Registry or move it out of the project and intro the registry. The linked model is simply a pointer to the original model in your project.
```

2023-12-06 03:37 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +A *Registered Model* is a collection or folder of linked model versions in the W&B Model Registry. Registered models typically represent a team’s ML task.
```suggestion
A *Registered Model* is a collection or folder of linked model versions in the W&B Model Registry. Registered Models typically represent candidate models for a single modeling use case or task. 
```

2023-12-06 03:38 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +```
```suggestion
run.finish()
```
```

2023-12-06 03:39 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +run = wandb.init(project="<your-project>", entity="<your-entity>")
```suggestion
run = wandb.init(project="llm-evaluation", entity="noa")
```

2023-12-06 04:28 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +A new version of a registered model is created when you link a model artifact to a model registry that already exists within that model registry.
```suggestion
If the 'registered-model-name' taken as input matches the name of a registered model that already exists within the Model Registry, the model will be linked to it. If no such registered model exists, a new one will be created and the model will be the first one linked. 
```

2023-12-06 04:30 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +For example, the proceeding code snippet logs model files and links the model model to a model registry called `"MNIST"`.
```suggestion
For example, the proceeding code snippet logs model files and links the model to a registered model named `"Fine-Tuned Review Autocompletion"`. As a quick reminder, this registered model houses a collection of bookmarked model versions. 
```

2023-12-06 04:38 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +For example, suppose you have a  model artifact named "mnist-testing" that exists within a model registry called "MNIST". And suppose that within the W&B App UI you see that the model artifact is mar
```suggestion
For example, suppose you have an existing registered model named "Fine-Tuned Review Autocompletion" in your Model Registry (see this in-product [here](https://wandb.ai/reviewco/registry/model?selectionPath=reviewco%2Fmodel-registry%2FFinetuned-Review-Autocompletion&view=all-models)). And suppose that a few model versions have already been linked to it: v0, v1, v2. If you call `link_model` with `registered-model-name="Fine-Tuned Review Autocompletion"`, the new model will be linked to this existing Registered Model as v4. If no Registered Model with this name exists, a new one will be created and the new model will be linked as v0. 
```

2023-12-06 04:39 UTC, noaleetz requested changes
new suggestions!!!

2023-12-06 18:45 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
> +run = wandb.init(project="MNIST_Exploration", entity="charlie")
I updated the code snippet w/ an actual model. It's a classifying model so it makes sense to not use the LLM example.

2023-12-06 18:46 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
> +
I put a real example in :)

2023-12-06 18:53 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
> +downloaded_model_path = run.use_model(name="<your-model-name>")
For this one, I tried to keep as bare bones. If they look at the example, they'll see the usage of an alias

2023-12-06 19:47 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Use the [`log_model`](../../../ref/python/run.md#log_model) to log a model artifact that contains content within a directory you specify. The `log_model` methods also marks the resulting model artifa
```suggestion
Use the [`log_model`](../../../ref/python/run.md#log_model) to log a model artifact that contains content within a directory you specify. The `[log_model](../../../ref/python/run.md#log_model)` methods also marks the resulting model artifact as an output of the W&B run. 
```

2023-12-06 19:49 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +
absolutely epic

2023-12-06 19:52 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Provide the name of the model artifact where the model file(s) you are looking to retrieve are stored for the `name` parameter. The name you provide must match the name of an existing logged model ar
```suggestion
Provide the name of the model artifact where the model file(s) you are looking to retrieve are stored. The name you provide must match the name of an existing logged model artifact.
```
fixed funky wording

2023-12-06 19:55 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Use the [`link_model`](../../../ref/python/run.md#link_model) method to log model file(s) to a W&B run and link it to the [W&B Model Registry](../../model_registry/intro.md). If no registered model e
```suggestion
Use the [`link_model`](../../../ref/python/run.md#link_model) method to log model file(s) to a W&B run and link it to the [W&B Model Registry](../../model_registry/intro.md). If no registered model exists, W&B will create a new for you with the name you provide for the `registered_model_name` parameter. 
```

2023-12-06 19:56 UTC, noaleetz commented on docs/guides/track/log/log-models.md
>  The proceeding code snippet shows how to link a model with the `link_model` API. Ensure to replace other the values enclosed in `<>` with your own:
```suggestion
The proceeding code snippet shows how to link a model with the `[link_model](https://docs.wandb.ai/ref/python/run#link_model)` API. Ensure to replace other the values enclosed in `<>` with your own:
```

2023-12-06 19:57 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +A *Registered Model* is a collection or folder of linked model versions in the W&B Model Registry. Registered Models typically represent candidate models for a single modeling use case or task.
```suggestion
A *Registered Model* is a collection or folder of linked model versions in the [W&B Model Registry](../../model_registry/intro.md). Registered models typically represent candidate models for a single modeling use case or task. 
```

2023-12-06 20:01 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +As a quick reminder, registered model house a collection of bookmarked model versions.
```suggestion
As a quick reminder, a registered model houses a collection of bookmarked model versions. 
```

2023-12-06 20:03 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +For example, suppose you have an existing registered model named "Fine-Tuned Review Autocompletion" in your Model Registry (see example [here](https://wandb.ai/reviewco/registry/model?selectionPath=r
```suggestion
For example, suppose you have an existing registered model named "Finetuned-Review-Autocompletion" in your Model Registry (see example [here](https://wandb.ai/reviewco/registry/model?selectionPath=reviewco%2Fmodel-registry%2FFinetuned-Review-Autocompletion&view=all-models)). And suppose that a few model versions have already been linked to it: v0, v1, v2. If you call `[link_model](../../../ref/python/run.md#link_model)` with `registered-model-name="Finetuned-Review-Autocompletion"`, the new model will be linked to this existing registered model as v4. If no registered model with this name exists, a new one will be created and the new model will be linked as v0. 
```

2023-12-06 20:06 UTC, noaleetz commented on docs/guides/track/log/log-models.md
>  ```python
@ngrayluna lets remove the spaces between each line since there are no comments here anyways

2023-12-06 20:09 UTC, noaleetz commented on docs/guides/track/log/log-models.md
```suggestion
Use the Model Registry to bookmark your best model checkpoints and centralize them across your team. The [[Model Registry](https://docs.wandb.ai/guides/model_registry)](https://docs.wandb.ai/guides/model_registry) allows you can organize your best models by task, manage model lifecycle, facilitate easy tracking and auditing throughout the ML lifecyle, and [[automate](https://docs.wandb.ai/guides/models/automation)](https://docs.wandb.ai/guides/models/automation) downstream actions with webhooks or jobs.
```

2023-12-06 20:10 UTC, noaleetz requested changes
a tiny bit more tweaks

2023-12-06 20:13 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
> +For example, suppose you have an existing registered model named "Fine-Tuned Review Autocompletion" in your Model Registry (see example [here](https://wandb.ai/reviewco/registry/model?selectionPath=r
@noaleetz The code example shows  `Fine-Tuned Review Autocompletion`

2023-12-06 20:15 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +For example, suppose you have an existing registered model named "Fine-Tuned Review Autocompletion" in your Model Registry (see example [here](https://wandb.ai/reviewco/registry/model?selectionPath=r
Gotcha - can we updated the code example to also be "Finetuned-Review-Autocompletion" (I can't find where to leave that suggestion)? Anywhere where we use this registered model name - this way it matches ex registry linked

2023-12-06 20:17 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
> +For example, suppose you have an existing registered model named "Fine-Tuned Review Autocompletion" in your Model Registry (see example [here](https://wandb.ai/reviewco/registry/model?selectionPath=r
Changed to : "Fine-Tuned-Review-Autocompletion"

2023-12-06 20:18 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
>  ```python
Sure. Extra spaces don't show up in markdown.

2023-12-06 20:22 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
Moved this to the tip banner so it's not hidden

2023-12-06 21:07 UTC, noaleetz commented on docs/guides/track/log/log-models.md
>  ```python
oops sorry I did not know that :) sounds good!!

2023-12-06 21:12 UTC, noaleetz commented on docs/guides/track/log/log-models.md
> +Models that are marked as the input or output to a run to track the lineage of that model. A model's lineage graph shows the model's dependencies and the model's associations. You can view the lineag
```suggestion
Models that are marked as an output to a run will be tracked inside the project's lineage graph. A lineage graph shows the model's dependencies and the model's associations. You can view the lineage of the model within the W&B App UI. See the [Explore and traverse artifact graphs](../../artifacts/explore-and-traverse-an-artifact-graph.md) page within the [Artifacts](../../artifacts/intro.md) chapter for more information.
```

2023-12-06 21:43 UTC, noaleetz approved these changes
https://github.com/wandb/docodile/pull/504#discussion_r1417983770 final change and can merge!

2023-12-06 22:15 UTC, ngrayluna commented on docs/guides/track/log/log-models.md
> +Models that are marked as the input or output to a run to track the lineage of that model. A model's lineage graph shows the model's dependencies and the model's associations. You can view the lineag
For now, I changed it to: You can track a model's dependencies and the model's associations if you mark the model as the input or output of a W&B run.

2023-12-06 22:23 UTC, merged