New model reg revamp
wandb/docs pull request #523
Opened 2023-12-15 19:06 UTC by ngrayluna

## Description

WIP Model Reg revamp

## Ticket

https://wandb.atlassian.net/browse/DOCS-744?atlOrigin=eyJpIjoiMWE0M2FlZjJhNzE3NGY0ZDkxMDE4NDc0ZjliNmRmN2MiLCJwIjoiaiJ9

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2023-12-22 22:11 UTC, ngrayluna commented on docs/guides/model_registry/model-management-concepts.md
> +[INSERT - to do]
@ibindlish Can you provide a definition for model aliases. :)?

2023-12-22 22:12 UTC, ngrayluna commented on docs/guides/model_registry/model-management-concepts.md
> +Registered models often represent candidate models for a single modeling use case or task. For example, [INSERT EXAMPLE].
Anyone have a superb example they'd like to share?

2023-12-22 22:13 UTC, ngrayluna commented on docs/guides/model_registry/walkthrough.md
>  # Walkthrough
Note: all non Model Reg-specific code blocks will be hidden in collapsible cells.

2023-12-26 18:35 UTC, ibindlish commented on docs/guides/model_registry/model-management-concepts.md
> +[INSERT - to do]
Model aliases are strings that allow you to uniquely identify each version of your registered model. You can't assign the same alias to multiple versions of a registered model.

2024-01-05 02:28 UTC, ibindlish requested changes

2024-01-05 02:28 UTC, ibindlish commented on docs/guides/model_registry/consume-models.md
> +run = wandb.init(project=project, entity=entity)
```suggestion
run = wandb.init()
```

2024-01-05 02:28 UTC, ibindlish commented on docs/guides/model_registry/consume-models.md
> +downloaded_model_path = run.use_model(name=f"{model_artifact_name}:{alias}")
```suggestion
downloaded_model_path = run.use_model(name=f"{entity/project/model_artifact_name}:{alias}")
```

2024-01-05 02:28 UTC, ibindlish commented on docs/guides/model_registry/consume-models.md
> +run = wandb.init(project=project, entity=entity)
context: there's a known sdk bug due to which the `use_artifact()` call doesn't work as expected if you init the run with the entity and project name :(

2024-01-05 02:28 UTC, ibindlish commented on docs/guides/model_registry/consume-models.md
> +# Download a model version
@noaleetz Do we want to add downloading files via the UI here?

2024-01-05 02:28 UTC, ibindlish commented on docs/guides/model_registry/create-registered-model.md
> +target_path = f"{entity}/model-registry/{registered_model_name}"
I thought we weren't going to include this in the model registry docs anymore? https://weightsandbiases.slack.com/archives/C02TK1QA006/p1702596857398559?thread_ts=1702526871.950079&cid=C02TK1QA006 
cc. @noaleetz  (or maybe i misunderstood?)

2024-01-05 02:28 UTC, ibindlish commented on docs/guides/model_registry/link-new-model-version.md
> +target_path = f"{entity}/model-registry/{registered_model_name}"
same question as above. ignore if its a misunderstanding. cc. @noaleetz

2024-01-05 02:28 UTC, ibindlish commented on i18n/ja/docusaurus-plugin-content-docs/current/guides/model_registry/consume-models.md
> +run = wandb.init(project="<your-project>", entity="<your-entity>")
```suggestion
run = wandb.init()
```

2024-01-05 02:28 UTC, ibindlish commented on i18n/ja/docusaurus-plugin-content-docs/current/guides/model_registry/consume-models.md
> +downloaded_model_path = run.use_model(name="<your-model-name>")
```suggestion
downloaded_model_path = run.use_model(name="<your-entity/your-project/your-model-name>:<alias/v{}>")
```

2024-01-05 02:28 UTC, ibindlish commented on i18n/ja/docusaurus-plugin-content-docs/current/guides/model_registry/consume-models.md
> +run = wandb.init(project=project, entity=entity)
```suggestion
run = wandb.init()
```

2024-01-05 02:28 UTC, ibindlish commented on i18n/ja/docusaurus-plugin-content-docs/current/guides/model_registry/consume-models.md
> +downloaded_model_path = run.use_model(name=f"{model_artifact_name}:{alias}")
```suggestion
downloaded_model_path = run.use_model(name=f"{entity/project/model_artifact_name}:{alias}")
```

2024-01-05 02:28 UTC, ibindlish commented on i18n/ja/docusaurus-plugin-content-docs/current/guides/model_registry/consume-models.md
> +downloaded_model_path = run.use_model(name="<your-model-name>")
Also, do we want to standardize between `entity` or `your-entity`, etc.?

2024-01-05 02:28 UTC, ibindlish commented on i18n/ja/docusaurus-plugin-content-docs/current/guides/model_registry/create-registered-model.md
> +artifact.link(target_path=target_path)
Same question as above. ignore if its a misunderstanding. Also, apologies if these files are generated based on the others!

2024-01-09 01:07 UTC, noaleetz commented on docs/guides/model_registry/consume-models.md
> +# Download a model version
Yes - I think that is a great idea so folks know how they can grab individual model files. @ngrayluna maybe we can add a short gif to show people how to download individual files from the Files Browser. 

https://github.com/wandb/docodile/assets/40642416/0b48fe4b-f9f2-4083-8dcd-2a2fbe412c79

2024-01-09 01:08 UTC, noaleetz commented on docs/guides/model_registry/consume-models.md
> +Use the W&B Python SDK to download a model that you have linked to the Model Registry. This is particularly useful if you want to evaluate its performance, make predictions against a dataset, or use
@ibindlish - does use_artifact call download() under the hood?

2024-01-09 01:10 UTC, noaleetz commented on docs/guides/model_registry/consume-models.md
> +downloaded_model_path = run.use_model(name=f"{model_artifact_name}:{alias}")
@ibindlish do we need to include the model path here (curious what you motivation is for adding it)?

2024-01-09 01:10 UTC, ibindlish commented on docs/guides/model_registry/consume-models.md
> +Use the W&B Python SDK to download a model that you have linked to the Model Registry. This is particularly useful if you want to evaluate its performance, make predictions against a dataset, or use
No. `use_model()` calls `use_artifact()` and then `download()` under the hood.

2024-01-09 01:11 UTC, ibindlish commented on docs/guides/model_registry/consume-models.md
> +downloaded_model_path = run.use_model(name=f"{model_artifact_name}:{alias}")
Mentioned in my comment above. https://github.com/wandb/docodile/pull/523#discussion_r1442433540

2024-01-09 01:15 UTC, noaleetz commented on docs/guides/model_registry/create-registered-model.md
> +target_path = f"{entity}/model-registry/{registered_model_name}"
Great point - @ngrayluna lets make sure to use the new APIs for linking the model artifact here rather than artifact APIS (i.e creating artifact, adding files, and link it)

2024-01-09 01:19 UTC, noaleetz commented on docs/guides/model_registry/link-new-model-version.md
> +## Interactively link a model
I think it might be useful to illustrate the 2 locations (or contexts) you can link models to the registry from:
1. directly from the artifact tab (this typically is beneficial for users to see as an option when they're getting familiar w artifacts and how to preserve/bookmark best checkpoints
2. from the Model Registry (relevant for users to are exploring created Registered Models and model cards, and Model Registry organization). We should show the case here of linking for an already existing Registered Model

* the 3rd way of linking during creation of a registered model does not need to be shown here. 

https://github.com/wandb/docodile/assets/40642416/125ae3e5-be3b-414d-beb4-01eeb00fb9ec

2024-01-09 01:21 UTC, noaleetz commented on docs/guides/model_registry/model-lineage.md
> +# Create model lineage map
this section is excellent!!!!

2024-01-09 01:22 UTC, noaleetz commented on docs/guides/model_registry/model-lineage.md
> +artifact = wandb.run.use_artifact(artifact_or_name="name", aliases="<alias>")
@ngrayluna do we need wandb.run.use_artifact -> shouldn't it just be run.use_artifact? In this case we should also be using the model APIs so we should use run.use_model and use the notes from that doc.

2024-01-09 01:23 UTC, noaleetz commented on docs/guides/model_registry/model-lineage.md
> +artifact = wandb.run.use_artifact(name)
same note as above - should be run.use_model - we should be using the model APIs for this

2024-01-09 01:24 UTC, noaleetz commented on docs/guides/model_registry/model-lineage.md
> +# Create model architecture
it might be useful to reduce the amount of example code / boilerplate code for training a model, compiling it and just highlight the linking piece.

2024-01-09 01:28 UTC, noaleetz commented on docs/guides/model_registry/model-management-concepts.md
> +A model version belongs to one, and only one, [model artifact](#model-artifact). A model version can belong to zero or more, [registered models](#registered-model).
Maybe we can make a note here highlighting that a model version represents a single model checkpoint - its a snapshot at a point in time of a model and its files within an experiment

2024-01-09 01:34 UTC, noaleetz commented on docs/guides/model_registry/model-management-concepts.md
> +[INSERT - to do]
Lets reframe to be in the affirmative:

> Model aliases are mutable, strings that allow you to uniquely identify or reference each version of your registered model used a semantically-related keyword. You can only assign an alias to one version of a registered model. This is because an alias should refer to a unique version when used programatically. It also allows aliases to be used to capture a model's state (champion, candidate, production). 


TBH I think integrating specific example of what best practice aliases are such as MLFlow does works super well
<img width="845" alt="Screenshot 2024-01-08 at 5 30 57 PM" src="https://github.com/wandb/docodile/assets/40642416/330ef911-e9a8-4cac-a48b-dcde358152fe">

2024-01-09 01:39 UTC, noaleetz commented on docs/guides/model_registry/model-management-concepts.md
> +A model artifact is a sequence of logged model versions.
We should be specific with what we mean w sequence here I think - i.e logged in order changes were made. 

We can also add a note - a model artifact might be empty if no model versions have been logged to it, or contain 1+ model versions.

2024-01-09 01:44 UTC, noaleetz commented on docs/guides/model_registry/model-management-concepts.md
> +Registered models often represent candidate models for a single modeling use case or task. For example, [INSERT EXAMPLE].
Sure, here are some from my friend chatgpt

Image Classification:

"ImageClassifier-ResNet50"
"ImageClassifier-VGG16"
"DogBreedClassifier-MobileNetV2"

Object Detection:

"ObjectDetector-YOLOv3"
"ObjectDetector-FasterRCNN"

Sentiment Analysis:

"SentimentAnalyzer-LSTM"
"SentimentClassifier-BERT"
Named Entity Recognition (NER):

"NERModel-BiLSTM-CRF"
"NERClassifier-BERT"

Language Translation:

"Translator-Transformer"
"LanguageModel-Seq2Seq"

Time Series Forecasting:

"TimeSeriesForecaster-LSTM"
"ForecastingModel-Prophet"

Generative Models:

"ImageGenerator-DCGAN"
"FashionGenerator-StyleGAN2

2024-01-09 01:45 UTC, noaleetz commented on docs/guides/model_registry/model-management-concepts.md
> +View an [example Registered Model](https://wandb.ai/timssweeney/model\_management\_docs\_official\_v0/artifacts/model/MNIST%20Grayscale%2028x28).
lets use a more up to date example in our demo repo - https://wandb.ai/reviewco/registry/model?selectionPath=reviewco%2Fmodel-registry%2FFinetuned-Review-Autocompletion&view=versions

2024-01-09 01:49 UTC, noaleetz requested changes
Left a round of feedback on technical accuracy re [this](https://weightsandbiases.slack.com/archives/C01DX8LRZEJ/p1704406908995069) thread

2024-01-16 16:33 UTC, ngrayluna commented on docs/guides/model_registry/create-registered-model.md
> +target_path = f"{entity}/model-registry/{registered_model_name}"
QQ: Do we intend the new APIs to remove needing t use the (old) public APIs? (I.e. outside of the run)

2024-01-17 20:05 UTC, ngrayluna commented on docs/guides/model_registry/model-lineage.md
> +artifact = wandb.run.use_artifact(name)
This example refers to logging a dataset artifact

2024-01-19 21:34 UTC, ibindlish approved these changes
lgtm! amazing work on the doc @ngrayluna - thanks!

Just a couple of nits, but my main question was around creating artifacts via the artifact browser - but i'll defer to @noaleetz.

2024-01-19 21:34 UTC, ibindlish commented on docs/guides/model_registry/intro.md
> +* [Bookmark your best model versions for each machine learning task.](./link-model-version.md)
**(nit)**: Would it be possible for the screenshot here to show some tags on the model panels too?

2024-01-19 21:34 UTC, ibindlish commented on docs/guides/model_registry/intro.md
> +* [Bookmark your best model versions for each machine learning task.](./link-model-version.md)
cc. @noaleetz

2024-01-19 21:34 UTC, ibindlish commented on docs/guides/model_registry/create-registered-model.md
> +Use the [`link_model`](../../ref/python/run.md#link_model) method to log model files to a W&B run and link it to the [W&B Model Registry](./intro.md).
**(nit)**: I noticed this snippet on the next page (Link a model version) too. Do we need it here?

2024-01-19 21:34 UTC, ibindlish commented on docs/guides/model_registry/create-registered-model.md
> +1. Navigate to your project's artifact browser on the W&B App at: `https://wandb.ai/<entity>/<project>/artifacts`
I'm not sure we want to advertise this method of creating registered models - because its not relevant to the model registry.

but I'll defer to @noaleetz

2024-01-20 00:58 UTC, noaleetz commented on docs/guides/model_registry/consume-models.md
> +Use the W&B Python SDK or the W&B App UI to download a model that you have linked to the Model Registry. Downloading a model is particularly useful if you want to evaluate a model's performance, make
```suggestion
Use the W&B Python SDK to download a model artifact that you have linked to the Model Registry. Downloading a model is particularly useful if you want to load or consume a model in a future run in order to evaluate a model's performance, make predictions with a dataset, or use ship the model to production. 

You can download individual files in an artifact in the Model Registry UI. 
```

You can download individual files but not the whole artifact. Typically the main reason why people download is so that they can have it locally in order to use in a later run.

2024-01-20 01:01 UTC, noaleetz commented on docs/guides/model_registry/consume-models.md
> +* `latest` - Use `latest` tag to specify the model version that is most recently linked.
```suggestion
* `latest` - Use `latest` alias to specify the model version that is most recently linked.
```
we have tags already for registered models so it is very important not to use tag language for aliases!

2024-01-20 01:21 UTC, noaleetz commented on docs/guides/model_registry/create-model-cards.md
> +* **Deserialize the model**: Provide information on how someone on your team can load the model into memory.
```suggestion
* **Deserialize the model**: Provide information on how someone on your team can load the model into memory.
* **Task**: The specific type of task or problem that a machine learning model is designed to perform. It's a categorization of the model's intended functionality.
* **License**: The legal terms and permissions associated with the use of the machine learning model. It helps model users understand the legal framework under which they can utilize the model.
* **References**: Citations or references to relevant research papers, datasets, or external resources.
* **Deployment**: Details on how and where the model is deployed and guidance on how it is integrated into other enterprise systems, such as a workflow orchestration platforms.

```

2024-01-20 01:22 UTC, noaleetz commented on docs/guides/model_registry/create-model-cards.md
> +* **Architecture**: The architecture of the machine learning algorithm. Did the algorithm use transfer learning? And so forth.
```suggestion
* **Architecture**: Information about the model architecture, layers, and any specific design choices.
```

2024-01-20 01:24 UTC, noaleetz commented on docs/guides/model_registry/create-registered-model.md
> +Interactively create a registered model within the [Model Registry App](https://wandb.ai/registry/model) or within your project's artifact browser.
thread [here](https://weightsandbiases.slack.com/archives/C0621EREJ1W/p1705699564808609) - we shouldn't refer to creating new collections via Artifact browser

2024-01-20 01:24 UTC, noaleetz commented on docs/guides/model_registry/create-registered-model.md
> +1. Navigate to your project's artifact browser on the W&B App at: `https://wandb.ai/<entity>/<project>/artifacts`
agreed! thread here - https://weightsandbiases.slack.com/archives/C0621EREJ1W/p1705699564808609

2024-01-20 01:26 UTC, noaleetz commented on docs/guides/model_registry/create-registered-model.md
> +Manual linking a model to the model registry is useful for one-off models. However, it is often useful to programmatically link model versions to the model registry. For example, suppose you have a n
```suggestion
Manual linking a model to the model registry is useful for one-off models. However, it is often useful to programmatically link model versions to the model registry. For example, suppose you have a nightly job. It is tedious to manually link a model created each night. Instead, you could create a script that evaluates the model, and if the model improves in performance, link that model to the model registry with the W&B Python SDK.
```

2024-01-20 01:32 UTC, noaleetz commented on docs/guides/model_registry/organize-models.md
> +3. Click the plus button (**+**) next to **Tags**.
can we add some screenshots of models w tags 
<img width="602" alt="Screenshot 2024-01-19 at 5 31 56 PM" src="https://github.com/wandb/docodile/assets/40642416/f6aa273b-68cf-465d-86a5-8fe2b72ebc84">

<img width="1055" alt="Screenshot 2024-01-19 at 5 30 59 PM" src="https://github.com/wandb/docodile/assets/40642416/1b54a350-3511-4dc3-96e7-4ed99e134c77">

2024-01-20 01:34 UTC, noaleetz commented on docs/guides/model_registry/intro.md
> +* [Bookmark your best model versions for each machine learning task.](./link-model-version.md)
I added some examples of screenshot and a similar comment inside the section of organizing models

2024-01-20 01:36 UTC, noaleetz commented on docs/guides/model_registry/link-model-version.md
> +For example, the following image shows that a `v0` [model version](./model-management-concepts.md#model-version) called `mnist_model`, was linked to the `MNIST-dev` model registry.
```suggestion
For example, the following image shows that a `v0` [model version](./model-management-concepts.md#model-version) called `mnist_model`, was linked to the `MNIST-dev` model registry.
```
```suggestion
For example, the following image shows that a `v0` [model version](./model-management-concepts.md#model-version) called `mnist_model`, was linked to the `MNIST-dev` Registered Model.
```
<img width="1095" alt="Screenshot 2024-01-19 at 5 36 36 PM" src="https://github.com/wandb/docodile/assets/40642416/53995ae7-e05c-402e-9613-a155815e6fc0">

are your referring to Model Registry? Or Registered Model? Screenshot above is a Registered Model

2024-01-20 01:42 UTC, noaleetz commented on docs/guides/model_registry/model-management-concepts.md
> +Model aliases are mutable strings that allow you to uniquely identify or reference each version of your registered model used a semantically-related keyword. You can only assign an alias to one versi
```suggestion
Model aliases are mutable strings that allow you to uniquely identify or reference each version of your registered model used a semantically-related identifier. You can only assign an alias to one version of a registered model. This is because an alias should refer to a unique version when used programatically. It also allows aliases to be used to capture a model's state (champion, candidate, production). Note, these are distinct from tags which are added to registered models, which are akin to keywords or labels and can be added to more than 1 registered models. 
```

2024-01-20 01:42 UTC, noaleetz commented on docs/guides/model_registry/model-management-concepts.md
> +A model artifact is a group of logged [model versions](#model-version). Model versions are stored in a model artifact in the order they are logged to the model artifact.
```suggestion
A model artifact is a collection of logged [model versions](#model-version). Model versions are stored in a model artifact in the order they are logged to the model artifact. 
```

2024-01-20 01:44 UTC, noaleetz commented on docs/guides/model_registry/model-management-concepts.md
> +For example, suppose you create a model artifact. During model training, you create model a version when you periodically save checkpoints. Each checkpoint will correspond to its own [model version](
```suggestion
For example, suppose you create a model artifact. During model training, you create model a version when you periodically save checkpoints. Each checkpoint will correspond to its own [model version](#model-version). All of the model versions belong to the model artifact you created at the beginning of your training script and will be assigned a version number depending on the sequence in which they were logged. A new version is automatically created when the contents of the latest version that was logged has changed. 
```

2024-01-20 01:47 UTC, noaleetz commented on docs/guides/model_registry/model-management-concepts.md
> +A registered model is a collection of pointers (links) to model versions. You can think of a registered model as a folder of "bookmarks". Each "bookmark" of a registered model is a pointer to a [mode
```suggestion
A registered model is a collection of pointers (links) to model versions. You can think of a registered model as a folder of "bookmarks" of candidate models for the same ML Task. Each "bookmark" of a registered model is a pointer to a [model version](#model-version) that belongs to a [model artifact](#model-artifact). Model versions are assigned version numbers in the order in which they were linked to the registered model. 
```

2024-01-20 01:48 UTC, noaleetz requested changes
left comments!

2024-01-22 18:53 UTC, ngrayluna commented on docs/guides/model_registry/consume-models.md
> +Use the W&B Python SDK or the W&B App UI to download a model that you have linked to the Model Registry. Downloading a model is particularly useful if you want to evaluate a model's performance, make
This do mentions downloading the model itself, not the entire artifact...?

2024-01-22 18:54 UTC, ngrayluna commented on docs/guides/model_registry/organize-models.md
> +3. Click the plus button (**+**) next to **Tags**.
For time, I didn't add the Organize model page to the docs. Wondering if we can make it a fast follow in Q1?

2024-01-22 18:55 UTC, ngrayluna commented on docs/guides/model_registry/model-management-concepts.md
> +Model aliases are mutable strings that allow you to uniquely identify or reference each version of your registered model used a semantically-related keyword. You can only assign an alias to one versi
Let's also add a new definition here called "Model tags"?

2024-01-22 23:47 UTC, noaleetz commented on docs/guides/model_registry/consume-models.md
> +Use the W&B Python SDK or the W&B App UI to download a model that you have linked to the Model Registry. Downloading a model is particularly useful if you want to evaluate a model's performance, make
I think we should only refer to logging a model artifact (i.e the full directory of files which can be multiple, not just the weights file) as this whole package is what people will be downloading and loading into their run. Because downloading in the UI and SDK don't both act on 1 object (i.e download() is called on whole artifact while UI you download individual files) we should focus on download() via SDK and shouldn't advertise them as identical actions. Does that make sense? 

i.e I think we should should discuss the SDK version as the primary way to download, and we can add a note at the end that says you can also download individual files in the file browser (but not the whole directory). 

We can include but I just want to make sure it is clear that the browser is more for downloading individual files, not for loading the whole directory onto your machine.

2024-01-22 23:49 UTC, noaleetz commented on docs/guides/model_registry/create-registered-model.md
> +Use the [`link_model`](../../ref/python/run.md#link_model) method to log model files to a W&B run and link it to the [W&B Model Registry](./intro.md).
cc @ngrayluna - should we leave this in both places? I think it might make sense to only have it in the section for linking a model version unless we want to show both here

2024-01-22 23:51 UTC, noaleetz commented on docs/guides/model_registry/organize-models.md
> +3. Click the plus button (**+**) next to **Tags**.
Can we leave in the current section exactly as is? I don't think there are any changes needed from the current version so I think we can keep it in. Including leaving current screenshots.

2024-01-23 00:05 UTC, noaleetz commented on docs/guides/model_registry/model-management-concepts.md
> +Model aliases are mutable strings that allow you to uniquely identify or reference each version of your registered model used a semantically-related keyword. You can only assign an alias to one versi
Yes I think this is a great idea - and we can link the chapter on model tags to learn more about how to use them. 

Model Tags: Model Tags are used to organize registered models into categories and to search over those categories in the Model Registry's search bar. They appear at the top of the Registered Model Card. You might choose to use them to group your registered models by ML task, owning team, or priority. The same tag can be added to multiple registered models to allow for grouping. Please note that tags, which are labels applied to registered models for grouping and discoverability, are different from model aliases (defined above) which serve as unique identifiers or nicknames to fetch one model version programatically. To learn more about using tags to organize the tasks in your Model Registry, see [this](https://docs.wandb.ai/guides/model_registry/model_tags) page.

2024-01-23 00:05 UTC, noaleetz commented on docs/guides/model_registry/model-management-concepts.md
> +Model aliases are mutable strings that allow you to uniquely identify or reference each version of your registered model used a semantically-related keyword. You can only assign an alias to one versi
^ left a sample definition above

2024-01-23 00:09 UTC, noaleetz commented on docs/guides/model_registry/model-management-concepts.md
> +A registered model is a collection of pointers (links) to model versions. You can think of a registered model as a folder of "bookmarks". Each "bookmark" of a registered model is a pointer to a [mode
```suggestion
A registered model is a collection of pointers (links) to model versions. You can think of a registered model as a folder of "bookmarks". Each "bookmark" of a registered model is a pointer to a [model version](#model-version) that belongs to a [model artifact](#model-artifact). You can use [tags](https://docs.wandb.ai/guides/model_registry/model_tags) to group your registered models. 
```

2024-01-23 00:10 UTC, noaleetz requested changes
responded to your notes!! lmk if you want to discuss any in slack.

2024-01-23 21:55 UTC, ngrayluna commented on docs/guides/model_registry/consume-models.md
> +Use the W&B Python SDK or the W&B App UI to download a model that you have linked to the Model Registry. Downloading a model is particularly useful if you want to evaluate a model's performance, make
Ah. I see what you mean. Makes sense.

2024-01-23 22:08 UTC, ngrayluna commented on docs/guides/model_registry/create-registered-model.md
> +Use the [`link_model`](../../ref/python/run.md#link_model) method to log model files to a W&B run and link it to the [W&B Model Registry](./intro.md).
Good catch. This section should actually read "Programmatically create a registered model".

2024-01-25 21:07 UTC, merged