Adding deployment type and other details for SSC
wandb/docs pull request #544
Opened 2024-01-02 17:43 UTC by abhinavg6

## Description

Adding deployment type specific details for SSC, along with differentiating between instance and team level SSC.

## Ticket

NA

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings. - Still getting unrelated TypeError: Invalid URL errors.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-01-02 21:35 UTC, venky-wandb approved these changes
LGTM!

2024-01-04 18:33 UTC, katjacksonWB requested changes
Made some language changes, let me know if there are any questions.

2024-01-04 18:33 UTC, katjacksonWB commented on docs/guides/hosting/secure-storage-connector.md
> +W&B uses a garbage collection process to delete W&B artifacts. For more information on how W&B deletes artifacts, and for information on how to enable garbage collection based on how you W&B, see the
```suggestion
W&B uses a garbage collection process to delete W&B artifacts. For more information on how W&B deletes artifacts and on how to enable garbage collection based on how you W&B, see the [garbage collection](../artifacts/delete-artifacts.md#how-to-enable-garbage-collection-based-on-how-wb-is-hosted) guide.
```
I simplified this a bit.

2024-01-04 18:33 UTC, katjacksonWB commented on docs/guides/hosting/secure-storage-connector.md
> +When it comes to **Self-managed** instances, the instance level secure storage connector is the default since the deployment is fully managed by the customer. In such a case the capability doesn't ha
```suggestion
For Self-Managed instances, the instance level secure storage connector is the default since the deployment is fully managed by the customer. In such a case the capability doesn't have a special significance, as compared to when you use it with Dedicated Cloud. The team level secure storage connector provides the same benefits for Self-Managed instances, especially when different business units and departments share an instance to efficiently utilize the infrastructure and administrative resources. This also applies to firms that have separate project teams managing ML workflows for separate customer engagements.
```
I've removed any instances of bolding that weren't related to UI elements.

2024-01-04 18:33 UTC, katjacksonWB commented on docs/guides/hosting/secure-storage-connector.md
> +The following table shows the availability of different kinds of secure storage connector across different W&B Server deployment types. X means the feature is available on the specific deployment typ
```suggestion
The following table shows the availability of different kinds of secure storage connector across different W&B Server deployment types. An `X` means the feature is available on the specific deployment type.
```

2024-01-04 18:33 UTC, katjacksonWB commented on docs/guides/hosting/secure-storage-connector.md
> +| Self-managed | X | X | Refer to the preceding `note` on significance of secure storage connector for **Self-managed** instances. Also, you could use the S3-compatible secure storage like [MinIO](ht
```suggestion
| Self-managed | X | X | The instance level secure storage connector is the default since the deployment is fully managed by the customer. It is also possible to use a S3-compatible secure storage solution like [MinIO](https://github.com/minio/minio) |
```

2024-01-04 18:33 UTC, katjacksonWB commented on docs/guides/hosting/secure-storage-connector.md
> +You should configure your instance or team level secure storage connector with the bucket from the same cloud as your instance in **Dedicated Cloud**. It is not possible to configure a bucket from a
```suggestion
Configure your instance or team level secure storage connector with the bucket from the same cloud as your instance in Dedicated Cloud. It is not possible to configure a bucket from a different cloud.
```

2024-01-04 18:33 UTC, katjacksonWB commented on docs/guides/hosting/secure-storage-connector.md
> +* Instance level: The instance level secure storage allows you to use your own managed bucket to store any files that your users may access as part of any runs in your W&B Server instance. This capab
```suggestion
* Instance level: The instance level secure storage allows you to use your own managed bucket to store any files that your users may access as part of any runs in your W&B Server instance. This capability is only available for Dedicated Cloud and Self-Managed instances; for SaaS Cloud instances, the instance level bucket is fully managed by W&B. 
```

2024-01-04 18:33 UTC, katjacksonWB commented on docs/guides/hosting/secure-storage-connector.md
> +* Team level: The team level secure storage allows teams within your organization to utilize a separate storage bucket from the one used at the instance level. This provides greater data access contr
```suggestion
* Team level: The team level secure storage allows teams within your organization to utilize a separate storage bucket from the one used at the instance level. This provides greater data access control and data isolation for teams with highly sensitive data or strict compliance requirements. This capability is available for all W&B organizations, including SaaS Cloud.
```

2024-01-04 18:33 UTC, katjacksonWB commented on docs/guides/hosting/secure-storage-connector.md
> +In case of **Dedicated Cloud** or **Self-managed** instances, you could configure secure storage connector at both the instance level and separately for any or all teams within your organization. Tak
```suggestion
For Dedicated Cloud or Self-Managed instances, you could configure secure storage connector at both the instance level and separately for any or all teams within your organization. For example, if there are two teams called _Omega_ & _Kappa_ in a Dedicated Cloud instance, and you have configured secure storage connector at the instance level, if you also configure the secure storage connector separately for team _Omega_, files pertaining to its runs are stored in team level secure storage. On the other hand if you do not configure the secure storage connector for team _Kappa_, files pertaining to its runs are stored in instance level secure storage.
```

2024-01-04 19:00 UTC, abhinavg6 reviewed
Accepted all but one change, thanks for the review Katherine.

2024-01-04 19:00 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +| Self-managed | X | X | Refer to the preceding `note` on significance of secure storage connector for **Self-managed** instances. Also, you could use the S3-compatible secure storage like [MinIO](ht
@katjacksonWB - I think the preceding note aspect would be good to include here, because I want to ensure that customers considering that deployment type read that whole thing. I'll make the change for second statement as a separate commit.

2024-01-04 22:07 UTC, ngrayluna approved these changes

2024-01-04 22:12 UTC, merged