Artifacts TTL - Team Default updates in docs
wandb/docs pull request #563
Opened 2024-01-16 19:59 UTC by ngrayluna

## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

https://wandb.atlassian.net/browse/DOCS-829

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-01-16 20:06 UTC, ngrayluna commented
@noaleetz V1 ready for review. Note: I'll. probably add some .gifs so that the page doesn't look so plane...

2024-01-17 01:02 UTC, estellazx commented on docs/guides/artifacts/ttl.md
> +7. From the dropdown, select **Edit TTL policy**.
it might be good to note that if you can't see this setting, check if your admin allows members to set TTLs

2024-01-17 01:03 UTC, estellazx approved these changes
lgtm

2024-01-17 03:28 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +7. From the dropdown, select **Edit TTL policy**.
agreed! We should make sure to highlight with a note any workflows that are (1) only visible to admin or (2) only visible if your admin has set the relevant permissions for it so that there is no confusion why UI editing is not visible

2024-01-17 17:26 UTC, ngrayluna commented on docs/guides/artifacts/ttl.md
> +7. From the dropdown, select **Edit TTL policy**.
@estellazx QQ: Does an error message appear if someone tries to set a TTL policy via the Python SDK for an artifact when they don't have permission to? (Admin sets only admins can set or edit a TTL policy)

2024-01-18 01:32 UTC, noaleetz commented on docs/guides/app/settings-page/team-settings.md
> +Navigate to your team’s profile page and select the **Team settings** icon to manage team settings. Not all members in a team can modify team settings. The account type (Administrator, Member, or Ser
instead of 'modify' team settings - the team settings will not be visible to all users (because you won't even be able to find it if you're not an admin).

2024-01-18 01:33 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
>  W&B deactivates the option to set a TTL policy for model artifacts linked to the Model Registry. This is to help ensure that models are not deleted by mistake.
```suggestion
W&B deactivates the option to set a TTL policy for model artifacts linked to the Model Registry. This is to help ensure that linked models do not accidentally expire if used in production workflows.
```

2024-01-18 01:34 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +* Only team admins can edit a [team's settings](../app/settings-page/team-settings.md) and permit who can set or edit a TTL policy.
```suggestion
* Only team admins can view a [team's settings](../app/settings-page/team-settings.md) and access team level TTL settings such as (1) permitting who can set or edit a TTL policy or (2) setting a team default TTL. 
```

2024-01-18 01:37 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +* It is likely that your team admin does not permit you to manage TTL policies if you do not see the option to set or edit a TTL policy in the W&B App UI or if you get an error when you try to progra
```suggestion
* If you do not see the option to set or edit a TTL policy in an artifact's details in the W&B App UI or if setting a TTL programmatically does not successfully change an artifact's TTL property, your team admin has not given you permissions to do so. 
```
I don't think we need to comment on likelihood here

2024-01-18 01:40 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +## Define who can edit and set TTL policies
```suggestion
## Team Admin Only: Control who can edit and set TTL policies
```
we should make it clear that any instructions below are only to be followed if you have access to team settings. It might make sense to avoid mixing the admin only abilities/instructions and having a separate section labeled:
1. Team Admin Only: Set a default TTL for your team
2. Team Admin Only: Define permissions for setting or editing a TTL

it's a bit confusing for non admins that the instructions are mixed in together

2024-01-18 01:43 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +7. From the dropdown, select **Edit TTL policy**.
Discussed via slack - results in no-op but no error messages

2024-01-18 01:43 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +## Set default TTL policies for a team
```suggestion
## Team Admin Only: Set default TTL policies for a team
```

2024-01-18 01:44 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +7. From the dropdown, select **Edit TTL policy**.
https://weightsandbiases.slack.com/archives/C01DX8LRZEJ/p1705537246757359?thread_ts=1705440391.913479&cid=C01DX8LRZEJ

2024-01-18 01:48 UTC, noaleetz commented on i18n/ja/docusaurus-plugin-content-docs/current/guides/artifacts/ttl.md
> +![](/images/artifacts/edit_ttl_ui.gif)
```suggestion
![](/images/artifacts/edit_ttl_ui.gif)
```
we should maybe show a gif that shows user navigating from Team Policy to Custom Policy (i.e what does it look like to edit a TTL when a default policy has been set). You can see what this looks like if you set a default TTL and then go back and try to edit it (your options will be Team Policy, Custom, Deactivate)

2024-01-18 02:27 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +9. Select the **Update TTL** button to save your changes.
can we also add a gif to show this (deactivation)

2024-01-18 02:29 UTC, noaleetz requested changes
left a few comments!

2024-01-18 18:58 UTC, ngrayluna commented on docs/guides/artifacts/ttl.md
> +## Set default TTL policies for a team
I added a banner within the section. Didn't add "Team Admin Only" because it will make searching the toping header not intuitive.

2024-01-18 21:08 UTC, merged