Update how to delete an artifact collection code snippet
wandb/docs pull request #566
Opened 2024-01-19 00:30 UTC by noaleetz

## Description

Updates code snippet for deleting an artifact collection to fetch the collection object from the api and calling delete it. This makes more sense because it handles the case where an artifact collection is empty, and in this case you can't query for the version in order to retrieve the collection. The updated snippet shows how to access the collection directly instead of via the artifact version. 
## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-01-19 00:31 UTC, noaleetz commented
@ngrayluna @ibindlish can you sanity check this PR to update code snippet for deleting a collection by accessing the collection directly via API?

2024-01-19 00:37 UTC, ibindlish requested changes

2024-01-19 00:37 UTC, ibindlish commented on docs/guides/artifacts/delete-artifacts.md
> +You can also delete artifact version programmatically with the [delete()](../../ref/python/artifact.md#delete) method. Provide the name of the project and entity for the `project` and `entity` keys i
This heading says artifact version but we're showing how to delete the artifact collection. Do the docs already talk about deleting versions?

2024-01-19 00:40 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +You can also delete artifact version programmatically with the [delete()](../../ref/python/artifact.md#delete) method. Provide the name of the project and entity for the `project` and `entity` keys i
Thanks for flagging - cc @ngrayluna - must be from the first round of updates. FIxing

2024-01-19 00:40 UTC, noaleetz commented on docs/guides/artifacts/delete-artifacts.md
> +You can also delete artifact version programmatically with the [delete()](../../ref/python/artifact.md#delete) method. Provide the name of the project and entity for the `project` and `entity` keys i
```suggestion
You can also delete artifact collection programmatically with the [delete()](../../ref/python/artifact.md#delete) method. Provide the name of the project and entity for the `project` and `entity` keys in `wandb.Api`, respectively:
```

2024-01-19 00:56 UTC, noaleetz commented
btw docs [here](https://docs.wandb.ai/guides/artifacts/delete-artifacts)

2024-01-19 18:51 UTC, ngrayluna commented
Do we have an `Api.artifact_collection` method? If yay, it's not documented here: https://docs.wandb.ai/ref/python/public-api/api.

Interesting, I see it in the source code [wandb/wandb/apis/public/api.py](https://github.com/wandb/wandb/blob/f40c3d357acf32ebd43989f5c0efc2dc01fa87a9/wandb/apis/public/api.py#L911) but there are no docstrings. Hence, why it won't appear in our ref guide.

2024-01-19 18:57 UTC, ngrayluna requested changes
Should we mention this API if there is no documention and/or docstrings generated for this function?

i.e. I won't see any info if I do a `help(wandb.Api.api.artifact_collection)`

2024-01-24 06:22 UTC, noaleetz commented
> Should we mention this API if there is no documention and/or docstrings generated for this function?
> 
> i.e. I won't see any info if I do a `help(wandb.Api.api.artifact_collection)`



> Do we have an `Api.artifact_collection` method? If yay, it's not documented here: https://docs.wandb.ai/ref/python/public-api/api.
> 
> Interesting, I see it in the source code [wandb/wandb/apis/public/api.py](https://github.com/wandb/wandb/blob/f40c3d357acf32ebd43989f5c0efc2dc01fa87a9/wandb/apis/public/api.py#L911) but there are no docstrings. Hence, why it won't appear in our ref guide.

Hey @ibindlish - does this method definitely exist? I know you had shared it in this slack msg [here](https://weightsandbiases.slack.com/archives/C04MNBGJDBN/p1705598623677109?thread_ts=1705596900.104449&cid=C04MNBGJDBN) when we discussed Gong deleting empty collections but it looks like this isn't in our ref docs.

2024-01-24 20:19 UTC, ibindlish commented
> > Should we mention this API if there is no documention and/or docstrings generated for this function?
> > i.e. I won't see any info if I do a `help(wandb.Api.api.artifact_collection)`
> 
> > Do we have an `Api.artifact_collection` method? If yay, it's not documented here: https://docs.wandb.ai/ref/python/public-api/api.
> > Interesting, I see it in the source code [wandb/wandb/apis/public/api.py](https://github.com/wandb/wandb/blob/f40c3d357acf32ebd43989f5c0efc2dc01fa87a9/wandb/apis/public/api.py#L911) but there are no docstrings. Hence, why it won't appear in our ref guide.
> 
> Hey @ibindlish - does this method definitely exist? I know you had shared it in this slack msg [here](https://weightsandbiases.slack.com/archives/C04MNBGJDBN/p1705598623677109?thread_ts=1705596900.104449&cid=C04MNBGJDBN) when we discussed Gong deleting empty collections but it looks like this isn't in our ref docs.

@noaleetz @ngrayluna Yep, the method exists. We should probably create a ticket to add docstrings for all our public api methods

2024-01-26 00:31 UTC, noaleetz commented
Hey @ngrayluna - @ibindlish put a PR out to add docstrings for artifact_collection: https://github.com/wandb/wandb/pull/6899

Can we merge this change?

2024-01-26 00:42 UTC, ngrayluna commented
@noaleetz Those changes won't show up for public users until the next SDK release. @ibindlish Am I correct on this?

2024-01-26 18:22 UTC, ibindlish commented
> @noaleetz Those changes won't show up for public users until the next SDK release. @ibindlish Am I correct on this?

Yeah. My docstring change will show up after the feb release of the sdk. But is it necessary for us to wait until then? The method exists even now.

2024-02-07 17:47 UTC, ngrayluna approved these changes

2024-02-07 17:47 UTC, merged