Update ttl.md to include resources: video, colab, report
wandb/docs pull request #567
Opened 2024-01-19 06:24 UTC by noaleetz

## Description

Adding link to youtube video and report + colab for programmatic TTL
## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-01-19 17:50 UTC, ngrayluna commented on docs/guides/artifacts/ttl.md
> +<CTAButtons colabLink="https://colab.research.google.com/drive/1ZP6W4FhkmGUOPPloIHqUhGLd2vYBVvph?usp=sharing"/>
@noaleetz Can you double check this is the correct shareable link to use? (Want to make sure it's accessible to everyone :)

2024-01-19 17:51 UTC, ngrayluna requested changes
Moved around links. Added a button for the Colab link.  One comment to double-check and we should be good to go.

Note: I removed the link to the report because, it is redundant to what we have on this page...

2024-01-22 03:16 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +<CTAButtons colabLink="https://colab.research.google.com/drive/1ZP6W4FhkmGUOPPloIHqUhGLd2vYBVvph?usp=sharing"/>
started a thread w you and Kevin Stofan here on moving this to [colab](https://weightsandbiases.slack.com/archives/C01DX8LRZEJ/p1705693980118379) in our repo - he owns the colab so he is the best person to close loop w this

2024-02-16 04:09 UTC, noaleetz reviewed
needs updated link to colab in github repo

2024-02-16 04:09 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +<CTAButtons colabLink="https://colab.research.google.com/drive/1ZP6W4FhkmGUOPPloIHqUhGLd2vYBVvph?usp=sharing"/>
Hi @ngrayluna - with thomas' PR merged - it looks like this is the best link to use which points to the colab in our repo - https://colab.research.google.com/github/wandb/examples/blob/kas-artifacts-ttl-colab/colabs/wandb-artifacts/WandB_Artifacts_Time_to_live_TTL_Walkthrough.ipynb. 

Can we update and merged this PR?

2024-02-20 17:56 UTC, merged