Update the Lineage guide for new clustering UX [do not merge until release]
wandb/docs pull request #607
Opened 2024-03-04 17:51 UTC by katjacksonWB

## Description

Updates lineage docs for the new updates. Also reorganizes the text content and simplifies the guide's language.

## Ticket

See [this doc](https://www.notion.so/wandbai/DAG-Lineage-Clustering-Performance-Roll-out-Plan-1a0afea7590f4b7bbd7ab26cd7dec3ed?pvs=4) for context.

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [x] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [x] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-03-06 20:56 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
>  W&B automatically tracks the artifacts a given run logged as well as the artifacts a given run used. Explore the lineage of an artifact with the W&B App UI or programmatically.
Do you think we can add a blurb (maybe at the end) as to what the benefits are of having your project's lineage tracked? Something like:

Use an artifact's lineage to track and manage of the various artifacts produced throughout the machine learning lifecycle. These artifacts can include data sets, models, parameters, metrics, and code. Artifact lineage is crucial for ensuring reproducibility, auditability, and governance of machine learning projects.

The key components and benefits of artifact lineage in MLOps include:

Reproducibility: By tracking the lineage of all artifacts, teams can reproduce experiments, models, and results, which is essential for debugging, experimentation, and validating machine learning models.

Version Control: Artifact lineage involves versioning of artifacts so that changes can be tracked over time. This allows teams to roll back to previous versions of data, code, or models if needed.

Auditability: Having a detailed history of the artifacts and their transformations enables organizations to comply with regulatory and governance requirements. This is particularly important in industries such as finance and healthcare, where models must be explainable and transparent.

Collaboration and Knowledge Sharing: Artifact lineage facilitates better collaboration among team members by providing a clear record of what has been tried, what worked, and what didn’t. This helps in avoiding duplication of efforts and accelerates the development process.

2024-03-06 21:07 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
>  W&B automatically tracks the artifacts a given run logged as well as the artifacts a given run used. Explore the lineage of an artifact with the W&B App UI or programmatically.
Thinking we should start with a more generic section that covers "what you can expect to find in your artifact's lineage graph" or "what is in an artifact's lineage graph" or "anatomy of your artifact's lineage graph". My proposal:

An artifact's lineage will be displayed as Directed Acyclic Graph (DAG) that visualizes the relationships and dependencies between various artifacts within a W&B project. Artifacts in W&B can be datasets, models, or any other relevant assets that are part of your ML pipeline. The DAG provides a graphical representation of how these artifacts evolve, interact, and contribute to the development of machine learning models. When you view an artifact lineage DAG in W&B, you will see:

- Nodes: Each node in the DAG represents either an artifact version or run. An artifact version could be, a dataset or model version, a launch job, or a set of evaluation results. A run could be training run, or a pre-processing transformation. 

- Edges: Edges connect the nodes and represent the flow or the dependency between artifacts. 

- Versioning: The DAG highlights the version history of an artifact, allowing users to track changes over time. This helps identify the exact version of an artifact used or logged by a W&B run. 

- Provenance: Users can see the provenance of artifacts, meaning the origin and the transformation process that an artifact went through.

2024-03-06 21:09 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +The artifact or run type you provide is located above its name, withA artifacts represented by blue icons and runs represented by green icons. The input and output of a run or artifact is depicted in
```suggestion
The artifact or run type you provide is located above its name, with artifacts represented by blue icons and runs represented by green icons. The input and output of a run or artifact is depicted in the graph with arrows. 
```

2024-03-06 21:13 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +The artifact or run type you provide is located above its name, withA artifacts represented by blue icons and runs represented by green icons. The input and output of a run or artifact is depicted in
added a few more details here to incorporate in comment above that might be appropriate for this section - https://github.com/wandb/docodile/pull/607/files#r1515154412

2024-03-06 21:14 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +### Traverse from an artifact
Hmm I'm a bit confused by the wording here - what does it mean by traverse from an artifact?

2024-03-06 21:15 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +Create an artifact object and provide the name of the project, artifact, and alias of the artifact:
I think we can remove mentions of object since artifact and object are a bit redundant

2024-03-06 21:18 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +Create an artifact object and provide the name of the project, artifact, and alias of the artifact:
It might be worth to avoid using public API for artifact creation and instead show users how to create it in the context of a run. The workflow would be - create an artifact, add content to it, and log it to a run (this might be a training run, where the logged output is a model). And then then show how to then mark this artifact as input to a downstream run. 

Then continue with existing code of how to walk up and down from that newly created artifact. 

For example - [this](https://docs.wandb.ai/guides/artifacts/create-a-new-artifact-version#single-run)
<img width="696" alt="Screenshot 2024-03-06 at 2 21 20 PM" src="https://github.com/wandb/docodile/assets/40642416/0a9217ab-b4bc-45ad-9f83-9835f968ea29">
section shows artifact creation in context of a run.

2024-03-06 21:19 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +Create an artifact object and provide the name of the project, artifact, and alias of the artifact:
```suggestion
Create an artifact object and provide the name of the project, artifact, and version number or alias of the artifact:
```

2024-03-06 21:23 UTC, noaleetz requested changes
left feedback. New UX should be up in google QA. Can you add relevant images and gifs and will take another look.

2024-03-06 21:24 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
>  W&B automatically tracks the artifacts a given run logged as well as the artifacts a given run used. Explore the lineage of an artifact with the W&B App UI or programmatically.
We should add gifs + section for cluster specific interactions coming in with new UX:

- Summary of Changes:
    - When a level of the graph (i.e a vertical column of nodes) has 5+ runs or artifacts, a cluster will be created
    - A cluster has a search bar to find specific versions
    - To continue investigating the lineage of a node in a cluster, a node can be pulled out from a cluster
    - Clicking on a node, whether an artifact or run node, will open a preview drawer with an overview of the node (previously a new tab opened, redirecting the user to a new lineage graph)

I don't see any details of these interactions in these PR. 

https://www.notion.so/wandbai/DAG-Lineage-Clustering-Performance-Roll-out-Plan-1a0afea7590f4b7bbd7ab26cd7dec3ed?pvs=4#a3b14cdde82d4580a400416e22e2e53c

2024-03-07 23:16 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +W&B automatically tracks the artifacts a given run logged as well as the artifacts a given run used. These artifacts can include data sets, models, parameters, metrics, and code. You can explore an a
```suggestion
W&B automatically tracks the artifacts a given run logged as well as the artifacts a given run used. These artifacts can include datasets, models, eval results, or more. You can explore an artifact's lineage to track and manage of the various artifacts produced throughout the machine learning lifecycle.
```
I'm realizing we shouldn't tell ppl to store parameters, metrics, and code since those should be logged to runs but we can also just do models and datasets

2024-03-07 23:47 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +- Collaboration and Knowledge Sharing: Artifact lineage facilitates better collaboration among team members by providing a clear record of what has been tried, what worked, and what didn’t. This help
```suggestion
- Collaboration and Knowledge Sharing: Artifact lineage facilitates better collaboration by providing a clear record of which intermediate artifacts are produced. Intermediate artifacts can be re-used and pulled into downstream projects to avoid duplication.
```

2024-03-07 23:50 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +The lineage graph generates based on the `type` you provide when you create runs and artifacts.
Re-reading this sentence - it doesn't actually make too much sense. We don't generate the graph based on type, we generate based off using log_artifact and use_artifact to mark inputs and outputs to runs. I say we remove or reframe how we generate (I think by generate this comment initially meant to point out out that the type of an artifact will be displayed on an artifacts node"

2024-03-07 23:51 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +Clicking on a node opens a preview with an overview of the node. Clicking on the arrow pulls out the run or artifact so you can track the lineage of the individual node.
```suggestion
Clicking on a node opens a preview with an overview of the node. Clicking on the arrow extracts the individual run or artifact so you can examine the lineage of the extracted node. 
```

2024-03-07 23:51 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +You can also navigate a graph usuing the [W&B API]((../../ref/python/public-api/api.md)).
```suggestion
You can also navigate a graph using the [W&B API]((../../ref/python/public-api/api.md)). 
```

2024-03-07 23:54 UTC, noaleetz commented on static/images/artifacts/lineage2.png
Very small nit but can we use an image here that shows the entire graph (i.e a graph that is small enough where you can see the complete thing when panning out?) - checkout [this](https://wandb.ai/wandb-smle/artifact_workflow/artifacts/raw_dataset/raw_data/v0/lineage) link

<img width="720" alt="Screenshot 2024-03-07 at 4 54 36 PM" src="https://github.com/wandb/docodile/assets/40642416/c9688886-7d11-45e5-b25e-3d287cb99ee9">

2024-03-07 23:55 UTC, noaleetz commented on static/images/artifacts/lineage1.gif
can we make sure we wait for the lineage page to load before ending the recording? Just because it ends a bit abruptly while the graph is still loading

2024-03-07 23:56 UTC, noaleetz commented on static/images/artifacts/lineage3.gif
I think it might be worth separating out into 2 gifs: 1 is looking at a preview of a run or artifact, 2 is extracting a node from a cluster (and maybe searching)

2024-03-07 23:58 UTC, noaleetz commented on static/images/artifacts/lineage4.gif
let's make sure any pages load to completion before ending the gif (just so it doesn't end abruptly when the page is loading or panning out to the final state)

2024-03-08 00:02 UTC, noaleetz commented on static/images/artifacts/lineage3.gif
We should include an image (or gif) which shows that the user can hover on an edge so you can trace back to the previous node it is dependent on! We should probably leave a note somewhere when we talk about navigating the UX to showcase this as I'm worried it's not super intuitive given how thin the edges are!

<img width="1037" alt="Screenshot 2024-03-07 at 5 01 08 PM" src="https://github.com/wandb/docodile/assets/40642416/9b8d21e2-4aad-46fb-944c-490a508c1cc0">

2024-03-08 00:02 UTC, noaleetz requested changes
a few comments on text but mostly feedback on the media! Great great work here, this is looking fantastic. 

This will probably be my last big round of feedback :)

2024-03-08 05:30 UTC, ngrayluna commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +### Benefits of tracking lineage
Let's remove this "### Benefits of tracking lineage" we can assume that the intro topic "##Lineage" describes why it's useful.

2024-03-08 05:33 UTC, ngrayluna commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +![Getting to the Lineage tab](../../../static/images/artifacts/lineage1.gif)
Can you remake this .gif? It's too small to see (even when expanded).

2024-03-08 05:35 UTC, ngrayluna commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +You can also navigate a graph usuing the [W&B API]((../../ref/python/public-api/api.md)).
There's an extra ")" floating here.

2024-03-08 05:36 UTC, ngrayluna commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +```
Specify the code type (python) https://docusaurus.io/docs/markdown-features/code-blocks#syntax-highlighting

2024-03-08 05:38 UTC, ngrayluna requested changes
Left some minor comments. In addition to Noa's, and the Vale lint check, we're close to shipping!

2024-03-11 23:23 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +W&B automatically tracks the artifacts a given run logged as well as the artifacts a given run used. These artifacts can include datasets, models, evaluation results, or more. You can explore an arti
I think there's a typo

2024-03-11 23:23 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +W&B automatically tracks the artifacts a given run logged as well as the artifacts a given run used. These artifacts can include datasets, models, evaluation results, or more. You can explore an arti
artifact's lineage to track and manage of the various artifacts

2024-03-11 23:25 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +- Version Control: Artifact lineage involves versioning artifacts and tracking their changes over time. This allows teams to roll back to previous versions of data, code, or models if needed.
```suggestion
- Version Control: Artifact lineage involves versioning artifacts and tracking their changes over time. This allows teams to roll back to previous versions of data or models if needed.
```

2024-03-11 23:25 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +The artifact or run type you provide appears in front of its name, with artifacts represented by blue icons and runs represented by green icons. Arrows detail the input and output of a run or artifac
for runs - the type is called job type not run type

2024-03-11 23:25 UTC, katjacksonWB commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +W&B automatically tracks the artifacts a given run logged as well as the artifacts a given run used. These artifacts can include datasets, models, evaluation results, or more. You can explore an arti
Fixed!

2024-03-11 23:26 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +Create an artifact object. First, create a run with `wandb.init`. Then,create a new artifact or retrieve an existing one with `wandb.Artifact`. Next, add files to the artifact with `.add_file`. Final
```suggestion
Create an artifact. First, create a run with `wandb.init`. Then, create a new artifact or retrieve an existing one with `wandb.Artifact`. Next, add files to the artifact with `.add_file`. Finally, log the artifact to the run with `.log_artifact`. The finished code looks something like this:
```

2024-03-11 23:29 UTC, noaleetz commented on docs/guides/artifacts/explore-and-traverse-an-artifact-graph.md
> +## Next steps
can we give users a public project to explore the lineage in product? Here is a good project that can be used - https://wandb.ai/wandb-smle/artifact_workflow/artifacts/raw_dataset/raw_data/v0/lineage

2024-03-11 23:29 UTC, noaleetz requested changes
few typos + nits, lets also add a link to a lineage they can play with

2024-03-11 23:41 UTC, noaleetz approved these changes
legooooo

2024-03-11 23:56 UTC, ngrayluna approved these changes

2024-03-12 01:35 UTC, merged