add model registry course link
wandb/docs pull request #609
Opened 2024-03-06 14:16 UTC by kldarek

## Description

We have a great model management course now - added the link to model registry guide intro page. 

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here: n/a

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ x] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ x] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-03-08 11:02 UTC, kldarek reviewed
@ngrayluna I think the course recommendation belongs to the higher level bullet points, rather than "learn about" section? Conceptually, it's the biggest thing folks can take to advance their knowledge on model reg (compared to short videos, walkthrough or reports that we have above, and especially contrasting with specific features we list in "learn about" section. WDYT?

2024-03-22 21:24 UTC, kldarek commented
@ngrayluna @noaleetz quick follow up on this, thanks!

2024-03-24 00:45 UTC, noaleetz commented on docs/guides/model_registry/intro.md
> +* Take the W&B online [Enterprise Model Management](https://www.wandb.courses/courses/enterprise-model-management) course.
```suggestion
* Take the W&B [Enterprise Model Management](https://www.wandb.courses/courses/enterprise-model-management) course.   
```
@kldarek can you specify the key point(s) / areas that the course covers that relate to the Model Reg docs? i.e "take the w&b EMM course to learn about...

2024-03-24 00:45 UTC, noaleetz requested changes
added request for more specific CTA

2024-03-27 18:22 UTC, kldarek commented on docs/guides/model_registry/intro.md
> +* Take the W&B online [Enterprise Model Management](https://www.wandb.courses/courses/enterprise-model-management) course.
Hey @noaleetz I think we cover Model Reg comprehensively in the course, do you think we should highlight anything in particular? I'd just say take the course to learn Model Registry best practices.

2024-03-27 21:56 UTC, noaleetz commented on docs/guides/model_registry/intro.md
> +* Take the W&B online [Enterprise Model Management](https://www.wandb.courses/courses/enterprise-model-management) course.
The CTA is not very convincing as is and how it ties into these docs. I agree that we cover Model Reg in the course, my ask though is that you specify a specifics on what the course covers in this CTA to connect it to the docs (i.e finish the sentence "take the course for an in-depth review on..."

2024-03-28 09:48 UTC, kldarek commented on docs/guides/model_registry/intro.md
> +* Take the W&B online [Enterprise Model Management](https://www.wandb.courses/courses/enterprise-model-management) course.
@noaleetz @ngrayluna How about this? 
Take the Weights & Biases Enterprise Model Management course and:
- learn how to use the W&B Model Registry to manage and version your models, track lineage, and promote models through different lifecycle stages.
- discover how to automate your model management workflows using webhooks and launch jobs.
- see how the Model Registry integrates with external ML systems and tools in your model development lifecycle for model evaluation, monitoring, and deployment.

Thanks to Agata for the copy!

2024-03-28 17:31 UTC, noaleetz approved these changes

2024-03-28 17:31 UTC, noaleetz commented on docs/guides/model_registry/intro.md
> +* Take the W&B online [Enterprise Model Management](https://www.wandb.courses/courses/enterprise-model-management) course.
sounds good to me - feel free to update the PR with these changes! Stamping

2024-03-29 18:17 UTC, kldarek commented
@ngrayluna updated the PR as recommended by Noa above.

2024-04-02 16:29 UTC, ngrayluna approved these changes

2024-04-02 16:29 UTC, merged