Wb server toc byob
wandb/docs pull request #625
Opened 2024-03-14 21:54 UTC by ngrayluna

## Description

New BYOB/SSC page. 

Note[1]: I made a controversial decision in this draft, namely, I refer to this page mostly by BYOB and not Secure Storage Connector. Not wedded to this, but here was my thinking:

1. At a glance, it's easier for Devs to know what we are talking about when we say BYOB.
2. SSC mostly refers to the pre-signed URL bit, so it's not indicative of what this doc is trying to explain; how to bring, configure buckets for storing sensitve data.

Note[2]: Ignore Vale stuff for now. Want to focus on the content. We can word smith later. :)

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-03-14 21:54 UTC, ngrayluna commented
Preview here:

[BYOB (Secure storage connector) _ Weights & Biases Documentation.pdf](https://github.com/wandb/docodile/files/14608291/BYOB.Secure.storage.connector._.Weights.Biases.Documentation.pdf)

2024-03-18 22:08 UTC, ngrayluna commented
@abhinavg6 New SSC/BYOB doc ready for review: 
[BYOB (Secure storage connector) _ Weights & Biases Documentation.pdf](https://github.com/wandb/docodile/files/14643028/BYOB.Secure.storage.connector._.Weights.Biases.Documentation.pdf)

2024-03-19 01:59 UTC, abhinavg6 requested changes
Left some comments @ngrayluna.

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +Bring your own bucket (BYOB) to store artifacts and other sensitive data for Dedicated Cloud deployments or Self-Managed instances. Data that is stored in your own bucket does not flow out of your ow
```suggestion
Bring your own bucket (BYOB) to store artifacts and other sensitive data for Dedicated Cloud deployments or Self-Managed instances. In case of Dedicated Cloud, such data is not stored in the W&B managed infrastructure.
```

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +Bring your own bucket (BYOB) to store artifacts and other sensitive data for Dedicated Cloud deployments or Self-Managed instances. Data that is stored in your own bucket does not flow out of your ow
I've changed this because `does not flow out` by itself can be slightly dodgy given changing things at our end.

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +Any communication between W&B and your bucket occurs only with pre-signed URLs.
I think we should remove the term `only` :)

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +W&B uses a garbage collection process to delete W&B Artifacts. For more information, see [How to enable garbage collection based on how W&B is hosted](../artifacts/delete-artifacts.md#how-to-enable-g
Actually may make sense to link just to `../artifacts/delete-artifacts.md` since that also refers to TTL for scheduling deletion.

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +There are two ways you can manage your storage object: at an Instance level or at a Team level.
```suggestion
There are two ways you can configure your storage bucket: at an Instance level or at a Team level. 
```

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +- Instance level: Any user within your organization can access any runs or files stored in your W&B Server instance.
```suggestion
- Instance level: Any user with relevant permissions within your organization can access any files stored in your instance-level storage.
```

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +- Team level:  A storage object that only members of a specific team within your organization can access.  Team level storage objects allow greater data access control and data isolation for teams wi
```suggestion
- Team level:  Storage bucket that only members of specific team(s) within your organization can access.  Team level storage buckets allow greater data access control and data isolation for teams with sensitive data or strict compliance requirements.
```

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +Configure your instance or team level storage objects with the same cloud provider. It is not possible to configure buckets from a different cloud providers.
I think we can remove this tip. We're making a change to allow connecting to different cloud providers or on-prem storages. We could add that as a simple add-on in a separate PR later.

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +For example, suppose you have a team called Kappa in your organization. Your organization (and Team Kappa) have an instance level storage object they use. Next, you create a team called Omega. When y
```suggestion
For example, suppose you have a team called Kappa in your organization. Your organization (and Team Kappa) have an instance level storage bucket they use. Next, you create a team called Omega. When you create Team Omega, you configure a Team level storage bucket for that team. Files generated by team Omega are not accessible by Team Kappa. However, files created by Team Kappa are accessible by Team Omega. If you want data isolation for Team Kappa as well, configure a Team level storage bucket for that team as well.
```

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +Team level storage objects provides the same benefits for Self-Managed instances, especially when different business units and departments share an instance to efficiently utilize the infrastructure
```suggestion
Team level storage bucket provides the same benefits for Self-Managed instances, especially when different business units and departments share an instance to efficiently utilize the infrastructure and administrative resources. This also applies to firms that have separate project teams managing ML workflows for separate customer engagements.
```

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
>  |----------------------------|--------------------|----------------|------------------------|
Just FYI, there are going to be a few minor changes here by April, but those can come in a separate PR.

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
>  | SaaS Cloud | | X | The team level secure storage connector is available only for Amazon Web Services and Google Cloud Platform. W&B fully manages the default and only bucket for Azure cloud. |
```suggestion
| SaaS Cloud | | X | The team level secure storage connector is available only for Amazon Web Services and Google Cloud Platform. W&B fully manages the default and only storage bucket for Azure cloud. |
```

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
>  | Dedicated Cloud | X | X | Both the instance and team level secure storage connector are available for Amazon Web Services and Google Cloud Platform. Only instance level secure storage connector is
```suggestion
| Dedicated Cloud | X | X | Both the instance and team level BYOB are available for Amazon Web Services and Google Cloud Platform. Only instance level BYOB is available for Azure cloud. |
```

2024-03-19 01:59 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
>  | SaaS Cloud | | X | The team level secure storage connector is available only for Amazon Web Services and Google Cloud Platform. W&B fully manages the default and only bucket for Azure cloud. |
```suggestion
| SaaS Cloud | | X | The team level BYOB is available only for Amazon Web Services and Google Cloud Platform. W&B fully manages the default and only bucket for Azure cloud. |
```

2024-03-20 01:45 UTC, abhinavg6 commented
@ngrayluna - I've made some minor updates to the doc and I feel it's in a good shape now. Plz let me know if you've any questions.

2024-03-20 04:27 UTC, ngrayluna reviewed
Quick question

2024-03-20 04:27 UTC, ngrayluna commented on docs/guides/hosting/secure-storage-connector.md
> +Reach out to your W&B Team to configure the Instance level secure storage connector for your Dedicated Cloud or Self-managed instance.
@abhinavg6 Quick question: so as to not confuse the word "Team" can we instead have their CTA be to reach out to Support?

2024-03-20 04:31 UTC, abhinavg6 approved these changes
LGTM. Thank you for being patient with my comments.

2024-03-20 04:31 UTC, abhinavg6 commented on docs/guides/hosting/secure-storage-connector.md
> +Reach out to your W&B Team to configure the Instance level secure storage connector for your Dedicated Cloud or Self-managed instance.
Sure Noah, that works.

2024-03-26 17:55 UTC, merged