Updates Artifacts Landing Page
wandb/docs pull request #627
Opened 2024-03-19 18:22 UTC by katjacksonWB

## Description

Edits to the Artifacts landing page to make it more readable, in conjunction with some colab changes.

## Ticket

Now addresses [DOCS-533](https://wandb.atlassian.net/browse/DOCS-533) and [DOCS-539
](https://wandb.atlassian.net/browse/DOCS-539)
## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [x] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [x] I merged the latest changes from `main` into my feature branch before submitting this PR.

[DOCS-533]: https://wandb.atlassian.net/browse/DOCS-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-03-24 00:56 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +* [View where a model came from, including trained data](./explore-and-traverse-an-artifact-graph.md).
```suggestion
* [Visualize a model's or dataset's lineage and dependencies](./explore-and-traverse-an-artifact-graph.md).
```

2024-03-24 01:12 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +## Use cases
can add a breakdown of a few common input/output combos on the use cases they represent? We often only talk about using a dataset as input and a model as output, and people get the idea that only a training run should have its artifacts tracked. Here are some other ideas to add in this use cases section:
1. ML workflow (run type) = dataset processing / transformation (input = dataset, output = dataset)
2. ML workflow (run type) = model evaluation or inference (input(s) = dataset, model, output = table)
3. ML workflow (run type) = model quantization (or putting model in different format) input = model, output = model). 

The goal is to convey the idea that you can have a W&B project that doesn't contain any training runs - for example we have some customers that just have a 'dataset factory' project where all inputs and output artifacts are datasets, and they're trying to track the lineage of transformations or processing run on their datasets like de-duplication, removal of PII, sampling, etc.)

2024-03-24 01:15 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +See the [track external files](./track-external-files.md) page for information on how to add references to files or directories stored in external object storage, like an Amazon S3 bucket.
```suggestion
See the [track external files](./track-external-files.md) page for information on how to add references to files or directories stored in external object storage, like an Amazon S3 bucket. 
```
can we add a note explaining when this would be a relevant feature to explore? i.e - "have all your data stored in an external storage bucket? You can leave it all in there and just create an artifact that points to your stored content. We can still get checksum info and track version changes without having any access to your content / having you directly upload it to W&B."

2024-03-24 01:16 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +## Next steps
can we add a pointer to automation docs? i.e want to automate actions based off changes to your artifacts? 

Thinking similar for model registry - lets at a CTA to model registry docs.

2024-03-24 01:17 UTC, noaleetz requested changes
first round of feedback in! lets use next steps to add CTAs to artifacts automations, and also to Model Registry

2024-03-27 17:50 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +## Use cases
Hey @katjacksonWB - sharing a diagram which shows some of these combinations created by phil a while back
![image (40)](https://github.com/wandb/docodile/assets/40642416/f9bd6123-71f4-4297-afbb-6eb39a240293)

2024-03-27 18:03 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +## Use cases
You can see here some examples of the variety of workflows a user might want to add reproducibility for using a (1) run (2) input artifact (3) output artifact. My ask here is to highlight some other workflows aside from the most common one we promote - Model Training (which you can see above in the center) which takes in a dataset version and outputs a model version. 

For example - Data Prep (which aligns with my #1 above):
> ML workflow (run type) = dataset processing / transformation (input = dataset, output = dataset)

I would probably call this dataset pre-processing or transformation though instead of dataset prep. 

Another example above is model evaluation - this takes a model as input and outputs a table artifact to inspect results. 

My proposal would be to highlight 4 use cases for artifacts:
1. Model Training (most basic one - dataset artifact as input, model artifact as output)
2. Dataset Pre-Processing (dataset artifact as input, dataset artifact as output)
3. Model Evaluation (model artifact + test dataset artifact as input, table artifact as output)
4. Model Optimization (model artifact as input, model artifact as output)

2024-03-27 18:05 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +## Use cases
Once you have another iteration on this specific section around use cases - I'm thinking we can loop in Ryan McConville (SMLE link for Artifacts) to get his eyes on whether the way these use cases are articulated make sense to him!

2024-04-02 23:24 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +Some of the use cases of artifacts including:
Hey @katjacksonWB - as discussed can we redo this section on more focus on inputs + outputs? This is an example table for automations I had made (very different use case) which is one way/idea to present the combinations of inputs and outputs and run types. This automations had a similar goal of showing what all the options are for the type of workflows you can harness artifacts for. 
<img width="862" alt="Screenshot 2024-04-02 at 5 22 39 PM" src="https://github.com/wandb/docodile/assets/40642416/7e254464-9d3d-4dde-885f-e205e1444a96">

2024-04-02 23:27 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +* Learn about [artifact automation](./project-scoped-automations.md).
for the artifact automation can we be specific on why / how artifact automations connects? My suggestion was that we have something like: "To learn how to trigger downstream workflows in response to changes to your artifacts, go to artifact automations"

2024-04-02 23:28 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +Indicate the artifact you want to use with the [`use_artifact`](../../ref/python/run.md#use_artifact) method, which returns a run object:
```suggestion
Indicate the artifact you want to mark as input to your run with the [`use_artifact`](../../ref/python/run.md#use_artifact) method, which returns an artifact object:
```
Possible mistake - I think this returns an artifact object not run

2024-04-02 23:30 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +artifact = run.use_artifact("my_data") #returns a run object using the "my_data" artifact
is the input param format correct? doesn't it have to have version specified via :latest?

2024-04-02 23:32 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +print("reference file:", artifact.manifest.entries[ref].ref) #prints a URL pointing to the "my_data" artifact for future reference
I think this might be better to put inside the reference artifacts doc no? It's kind of confusing to have this when we're not talking about reference artifacts only in this section

2024-04-02 23:33 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +datadir = artifact.download() #downloads the "my_data" artifact
can we update the comment to tell the user specifically what they can expect to see when calling download? i.e creates a dir called artifacts/ locally with contents XYZ... so user know where on their machine this contents will show up

2024-04-02 23:33 UTC, noaleetz requested changes
left another round of comments!

2024-04-03 19:12 UTC, katjacksonWB commented on docs/guides/artifacts/intro.md
> +Some of the use cases of artifacts including:
Will do- that table's a super good reference point. Thank you!

2024-04-11 03:07 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +See the [track external files](./track-external-files.md) page for information on how to add references to files or directories stored in external object storage, like an Amazon S3 bucket.
Hey @katjacksonWB is this resolved?

2024-04-11 03:07 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +## Next steps
Hey @katjacksonWB is this resolved?

2024-04-11 03:07 UTC, noaleetz commented on docs/guides/artifacts/intro.md
> +## Use cases
Hey @katjacksonWB is this resolved?

2024-04-11 03:08 UTC, noaleetz approved these changes

2024-04-23 08:36 UTC, rymc commented on docs/guides/artifacts/intro.md
> +Use W&B Artifacts to track and version data as the inputs and outputs of your [W&B Runs](../runs/intro.md). For example, a model training run might take in a dataset as input and trained model as out
Suggesting a few changes below..

Use W&B Artifacts to track and version data as the inputs and outputs of your [W&B Runs](../runs/intro.md). For example, a model training run might take in a dataset as input and produce a trained model as output. In addition to logging hyperparameters, metadata and metrics to a run, you can use an artifact to log, track and version the dataset used to train the model as input and another artifact for the resulting model checkpoints as outputs.

2024-04-23 08:43 UTC, rymc commented on docs/guides/artifacts/intro.md
> +| Model Training         | Dataset (training data)     | Trained [Model](../models.md)                |
If not too much, I would suggest modifying under "Input" to be _Dataset (training and validation data)_.

2024-04-23 08:45 UTC, rymc commented on docs/guides/artifacts/intro.md
> +| Model Evaluation       | Model + Dataset (test data) | [Table](../tables/intro.md)                        |
Perhaps specify this as a "W&B Table"?

2024-04-23 08:48 UTC, rymc commented on docs/guides/artifacts/intro.md
>  1. Create a [W&B run](../runs/intro.md).
Should this be W&B Run (i.e. uppercase)?

2024-04-23 08:49 UTC, rymc commented on docs/guides/artifacts/intro.md
>  4. Log your artifact to W&B.
"Add one or more files or directories.."? It's useful to know files can be added individually, or a directory (and the example code is adding a directory).

2024-04-23 08:52 UTC, rymc commented on docs/guides/artifacts/intro.md
>  artifact.add_dir(local_path="./dataset.h5")  # Add dataset directory to artifact
`artifact.add_dir(local_path="./dataset.h5")` appears a little confusing to me because dataset.h5 implies it's a file, not a directory, but the code calls `add_dir()`. Should it be `add_file()` or instead using `add_dir()` with something that is more clearly a directory?

2024-04-24 22:54 UTC, katjacksonWB commented on docs/guides/artifacts/intro.md
>  artifact.add_dir(local_path="./dataset.h5")  # Add dataset directory to artifact
@rymc Thanks for the comments! I think I addressed all of them; would you mind taking another look? Thanks!

2024-04-25 10:09 UTC, rymc commented on docs/guides/artifacts/intro.md
>  artifact.add_dir(local_path="./dataset.h5")  # Add dataset directory to artifact
Looks good to me, thanks @katjacksonWB!

2024-04-25 10:10 UTC, rymc approved these changes

2024-05-13 23:50 UTC, ngrayluna approved these changes

2024-05-13 23:51 UTC, merged