Add torchtune docs
wandb/docs pull request #656
Opened 2024-04-22 10:17 UTC by tcapelle

Add [torchtune](https://pytorch.org/torchtune/stable/deep_dives/wandb_logging.html) documentation.

2024-04-22 17:46 UTC, tcapelle commented
<img width="1197" alt="image" src="https://github.com/wandb/docodile/assets/18441985/466b4d7b-2e10-46a2-b45a-5bb800ea7865">
<img width="1198" alt="image" src="https://github.com/wandb/docodile/assets/18441985/12e02920-cae6-49c5-81d8-642ba8b03c92">
<img width="1217" alt="image" src="https://github.com/wandb/docodile/assets/18441985/4c6d6f4f-6565-460c-aef0-cbb9b4b70145">

2024-04-29 10:42 UTC, morganmcg1 requested changes

2024-04-29 10:42 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +[torchtune](https://pytorch.org/torchtune/stable/index.html) is a PyTorch-based library designed to streamline the authoring, fine-tuning, and experimentation processes for large language models (LLM
Make this 2 sentences

2024-04-29 10:42 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +
Add colab badge

2024-04-29 10:42 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +
Add small codeblock showing the core lines of code needed to turn on W&B logging

https://docs.wandb.ai/guides/integrations/huggingface#-next-level-logging-in-few-lines

2024-04-29 10:42 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +1. First install the `wandb` library:
Delete install step

2024-04-29 10:42 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +## What do we log?
Add Table with all arguments and descriptions, like here https://docs.wandb.ai/guides/integrations/huggingface#additional-wb-settings

2024-04-29 10:42 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +  metric_logger._component_=torchtune.utils.metric_logging.WandBLogger \
show the part of the config file with wandb logging turned on, not just cli argument

2024-04-29 10:42 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +If you want to save the model checkpoints to [W&B Artifacts](https://docs.wandb.ai/guides/artifacts), the simplest solution is to override the [`save_checkpoint`](https://github.com/pytorch/torchtune
don't link to torchtune code as the links will probably go stale pretty quickly as its in active development

2024-04-29 10:42 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +    wandb_at = wandb.Artifact(
rename `wandb_at` to `art`or similr,  `*_at` isn't commonly used

2024-04-29 10:54 UTC, tcapelle commented on docs/guides/integrations/torchtune.md
> +    wandb_at = wandb.Artifact(
I use `*_at` all the time, for some reason I always thought that this was the "standard" naming 🤔

2024-04-29 10:56 UTC, tcapelle commented on docs/guides/integrations/torchtune.md
> +If you want to save the model checkpoints to [W&B Artifacts](https://docs.wandb.ai/guides/artifacts), the simplest solution is to override the [`save_checkpoint`](https://github.com/pytorch/torchtune
I will keep the checkpointer link, as I don't think they will change this paradigm. Will remove specific line pointers

2024-04-29 10:58 UTC, tcapelle commented on docs/guides/integrations/torchtune.md
> +  metric_logger._component_=torchtune.utils.metric_logging.WandBLogger \
this makes you use W&B straight away with the supplied recipes, what do you think about adding the part of the config also?

2024-04-29 11:00 UTC, tcapelle commented on docs/guides/integrations/torchtune.md
> +
we don't have a colab... should we make one? this is a CLI library anyway

2024-04-29 11:05 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +  metric_logger._component_=torchtune.utils.metric_logging.WandBLogger \
The goal is to show best practice of how to use the integration, which I think should be via a config file given that there are a number of different arguments to be set

you can show both but we should prefer the config file

2024-04-29 11:06 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +If you want to save the model checkpoints to [W&B Artifacts](https://docs.wandb.ai/guides/artifacts), the simplest solution is to override the [`save_checkpoint`](https://github.com/pytorch/torchtune
sounds good

2024-04-29 11:08 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +    wandb_at = wandb.Artifact(
less so in integrations land I guess, 

transformers:


<img width="758" alt="Screenshot 2024-04-29 at 12 06 46" src="https://github.com/wandb/docodile/assets/20516801/6e7af313-8bb6-44d0-bbf2-67a70799fa54">


lightning:


<img width="606" alt="Screenshot 2024-04-29 at 12 07 24" src="https://github.com/wandb/docodile/assets/20516801/8ef2e9e4-a1dc-46c0-a671-9fde4749ac06">

2024-04-29 11:08 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +
yep lets create a colab

2024-04-29 11:09 UTC, morganmcg1 requested changes

2024-04-29 11:09 UTC, morganmcg1 commented on docs/guides/integrations/torchtune.md
> +# torchtune
Can you also address the the `vale` grammar failures and warnings thanks

2024-04-29 11:12 UTC, tcapelle commented on docs/guides/integrations/torchtune.md
> +## What do we log?
What do you expect here exactly? We could add a list of the params to init? as the library is evolving, for the time being we log whatever they call inside the train function, so loss, tokens_per_sec, lr and the config

2024-04-29 11:12 UTC, tcapelle commented on docs/guides/integrations/torchtune.md
> +  metric_logger._component_=torchtune.utils.metric_logging.WandBLogger \
added a tabbed view

2024-04-29 11:12 UTC, tcapelle commented on docs/guides/integrations/torchtune.md
> +If you want to save the model checkpoints to [W&B Artifacts](https://docs.wandb.ai/guides/artifacts), the simplest solution is to override the [`save_checkpoint`](https://github.com/pytorch/torchtune
roger

2024-04-29 11:15 UTC, tcapelle commented on docs/guides/integrations/torchtune.md
> +1. First install the `wandb` library:
done

2024-04-30 11:26 UTC, tcapelle commented
New look:
<img width="987" alt="image" src="https://github.com/wandb/docodile/assets/18441985/f55db8f0-f8b0-4cad-aabd-0a4f77bbfeb7">

2024-04-30 12:19 UTC, tcapelle commented
![torchtune_docs](https://github.com/wandb/docodile/assets/18441985/f04ae79a-3d5b-4a4f-a496-bef6ec54ed2b)

2024-05-03 17:43 UTC, tcapelle commented
This is ready for review/merge @ngrayluna

2024-05-07 21:40 UTC, ngrayluna commented
Some notes:

* We don't use "->".
*  Bold text is reserved only for referring to UI elements.
* Don't use "we" in the docs.

2024-05-07 21:47 UTC, ngrayluna approved these changes

2024-05-08 21:48 UTC, tcapelle reviewed
the pytorch team wanted us to explicitely call torchtune with undercase.

2024-05-08 21:48 UTC, tcapelle commented
feel free to merge @ngrayluna

2024-05-08 21:51 UTC, merged