Removes unclear model link from Artifacts landing page.
wandb/docs pull request #673
Opened 2024-05-14 19:40 UTC by katjacksonWB

## Description

Removes unclear model link from the table in the Artifacts landing page.
Bonus: also adds one-line artifact logging to the landing page, replacing sub-optimal code. Sneaky.

## Ticket

N/A

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [x] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [x] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-05-15 21:34 UTC, ngrayluna commented on docs/guides/artifacts/intro.md
> +run.log_artifact(artifact "./dataset.h5", "my_data", "dataset" ) # Logs the artifact version "my_data:v0" as a dataset with data from dataset.h5
Add parameter names.

2024-05-16 21:28 UTC, noaleetz approved these changes

2024-05-21 17:03 UTC, ngrayluna commented on docs/guides/artifacts/intro.md
> +run.log_artifact(artifact data = "./dataset.h5", naame = "my_data", type= "dataset" ) # Logs the artifact version "my_data:v0" as a dataset with data from dataset.h5
@katjacksonWB Some typos here in the artifact log command.

2024-05-21 17:03 UTC, ngrayluna requested changes
Typo in log artifact command

2024-05-21 21:27 UTC, ngrayluna approved these changes

2024-05-21 21:27 UTC, merged