Adds new section to Artifacts TTL docs on auto-generated artifacts.
wandb/docs pull request #685
Opened 2024-05-23 20:58 UTC by katjacksonWB

## Description

Adds new section to Artifacts TTL docs on auto-generated artifacts.

## Ticket

[DOCS-870](https://wandb.atlassian.net/browse/DOCS-870)
## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [x] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [x] I merged the latest changes from `main` into my feature branch before submitting this PR.

[DOCS-870]: https://wandb.atlassian.net/browse/DOCS-870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-05-24 21:17 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +## Determine if your Artifact is affected by TTL policies
Can we frame this more as "Artifacts TTL is disabled for system-generated Artifact"

the wording of 'your' artifact is strange because the whole idea of system-generated artifacts are that they are not the users / the user doesn't have knowledge of them being created

2024-05-24 21:18 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +- The Artifact name starts with: `run-*`
defined by type is run_table

2024-05-24 21:21 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +The following Artifact naming schemes indicate an auto-generated Artifact:
can we frame this around the type scheme rather than artifact name? this is easier to recognize since it will show up in a collapsed dropdown at the bottom of artifacts sidebar. We can use similar structure as table where we the list is by type, and then we mention what the artifact name will be

2024-05-24 21:22 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +- The Artifact name starts with: `source-*`
defined by type is `code`

2024-05-24 21:22 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +- The Artifact name starts with: `job`
defined by type is `job`

2024-05-24 21:23 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +- The Artifact name starts with: `wandb-*`
defined by type is wandb-history (or any type starting with wandb-)

2024-05-24 21:24 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +The following Artifact naming schemes indicate an auto-generated Artifact:
let's remind users how to identify an artifacts type - it is a property of the artifact.

2024-05-24 21:25 UTC, noaleetz requested changes
left a few comments mostly around to defining the list via the artifact type rather than by name

2024-05-29 00:02 UTC, noaleetz commented on docs/guides/artifacts/ttl.md
> +You can check an Artifact's type on the [W&B platform](../artifacts/explore-and-traverse-an-artifact-graph.md) or programatically:
```suggestion
You can check an Artifact's type on the [W&B platform](../artifacts/explore-and-traverse-an-artifact-graph.md) or programmatically:
```

2024-05-29 00:03 UTC, noaleetz approved these changes

2024-07-09 17:43 UTC, ngrayluna approved these changes

2024-07-09 19:41 UTC, merged