Registry mvp docs
wandb/docs pull request #689
Opened 2024-05-28 22:21 UTC by ngrayluna

## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-05-28 22:22 UTC, ngrayluna commented on docs/guides/registry/configure_registry.md
> +| Role | Permissions |
@noaleetz Can you fill these in? :)

2024-05-28 22:23 UTC, ngrayluna commented on docs/guides/registry/create_collection.md
> +    {label: 'Unrestricted collection types', value: 'alltypes'},
Comment to resolve: https://github.com/wandb/docodile/pull/687#discussion_r1614029117

2024-05-28 22:24 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +# Registry
@noaleetz This is the page that will probably need the most review; how to capture user's attention, tell them the why, what, and how + next steps.

2024-05-28 22:25 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +import Translate, {translate} from '@docusaurus/Translate';
Will we have a live asset that customers can see?

2024-05-28 22:26 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +<!-- To do: INSERT -->
Besides links to the registry dev guide, are there other resources that we want to link to here? If yes, what?

2024-05-29 00:08 UTC, noaleetz commented on docs/guides/registry/create_collection.md
> +    {label: 'Unrestricted collection types', value: 'alltypes'},
is there a specific screenshot from the prototypes you can share of what you're referring to here? is this a custom registry? or is then when user selects the option of all types in the registry settings?

2024-05-29 00:10 UTC, noaleetz commented on docs/guides/registry/intro.md
> +import Translate, {translate} from '@docusaurus/Translate';
at the moment we won't have a fully public registries app the same way we do for projects. Users need to be in a given org to see Registries (and be a W&B user). If the registry visibility is Organization - to see the wandb registry a user must be in the wandb team. 

But I will let you know if/when we add a fully public registry that can become a demo registry

2024-05-29 00:15 UTC, noaleetz commented on docs/guides/registry/intro.md
> +<!-- To do: INSERT -->
Can we make sure to be consistent with the naming of the product - W&B Registries?

2024-05-29 00:16 UTC, noaleetz commented on docs/guides/registry/intro.md
> +<!-- To do: INSERT -->
For now we don't have any content but hoping we'll get some good tutorial videos the closer we get. here is the coming soon article - https://wandb.ai/wandb_fc/product-announcements-fc/reports/Coming-soon-Registries-in-W-B-Models--Vmlldzo3OTc4OTg1

2024-05-30 02:48 UTC, noaleetz commented on docs/guides/registry/configure_registry.md
> +| Role | Permissions |
filled this out in this commit - https://github.com/wandb/docodile/commit/5f88d886ae481d5ba2fce6ee336ec6dfa6bca77f

2024-06-06 01:55 UTC, noaleetz commented on docs/guides/registry/delete_registry.md
I don't think we need a full page for this - we can just stick this in the page for creating a registry. We should be specific that it is "creating a custom registry".

2024-06-06 01:59 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +A core registry is a template for specific use cases with a standardizes setup to maintain core functionality. W&B automatically creates core registries and adds them to the W&B Registry App.
```suggestion
There are two core registries: Models and Datasets. These will automatically exist in the Registries home page. By default, the Model Registry will be configured to accept artifacts of type="model" and the Dataset Registry will be configured to accept artifacts of type="dataset". An admin can choose to add additional accepted types. 
```

2024-06-06 02:00 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +Use custom registries for greater flexibility and customization. [INSERT]
can you be more specific here on what exactly is different / more flexible or customizable here?

2024-06-06 02:01 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +Use custom registries for greater flexibility and customization. [INSERT]
We should also make sure to share examples of what users can use custom registries for: some ideas - a private registry for a specific team, a registry for benchmark datasets, a registry for evaluation datasets, a registry for code, etc.

2024-06-06 02:02 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +| Organization | Anyone in the organization can view the registry. |
not necessarily. Anyone in the organization is a user in the registry. It is not necessarily true that all are viewers only.

2024-06-06 02:11 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +| Restricted   | Only invited organization members can view and edit the registry.|
also not necessarily true -> it depends on the role you have in the registry. It's probably better to first explain the different roles a user can be in a registry (viewer, member, admin, owner) and then use those terms to explain. 

Only invited organization members can access the registry. 

whether they can view or edit the registry depends on which role they get when added. [This](https://weightsandbiases.slack.com/archives/C05UUJ350CA/p1712262412947029) thread has these details 

when a registry is created or when a user is added: by default
org-level admins -> admin
registry creator -> owner
all other org users -> viewer

2024-06-06 02:17 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +| Flexibility    | Limited to adding additional types to the existing list.| High flexibility. Users can customize names, descriptions, accepted artifact types and visibility.|
Users can do all the following customization in a core registry: add types, change user roles
```suggestion
| Edit Properties | Add accepted types | Edit registry name, description, visibility, and accepted artifact types. |
```

can we use alternate wording instead of flexibility - core registries have largely the same flexibility so it feels weird to frame one option as high or low flexibility and makes the low flexibility version seem worse.

2024-06-06 02:17 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +| Metadata       | Preconfigured and not editable by users. | Users can edit.  |
what is meant by metadata here?

2024-06-06 02:19 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +| Artifact types | Preconfigured artifact types that cannot be removed. Users can add additional types. | Fully customizable by users.|
```suggestion
| Artifact types | Preconfigured accepted types that cannot be removed. Users can add additional types. | All types defined by an admin.|
```

2024-06-06 02:20 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +## Registry visibility
I think the registry visibility should be in its own guide, along with editing user roles/access in a registry settings called access controls

2024-06-06 02:20 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +For information on  how to create a custom registry, see [Create a custom registry](./create_collection.md).
```suggestion
For information on how to create a custom registry, see [Create a custom registry](./create_collection.md).
```

2024-06-06 02:20 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +## Registry visibility
rather than being in a registry types section

2024-06-06 02:21 UTC, noaleetz commented on docs/guides/registry/create_registry.md
> +Create a custom registry within an organization. Custom registries are particularly useful for organizing project-specific requirements that differ from the default, core registries that W&B provides
i would use different examples here, such as evaluation datasets, fine-tuning datasets, code, jobs, etc.

2024-06-06 02:23 UTC, noaleetz commented on docs/guides/registry/create_registry.md
> +W&B Registries is in active development. Currently, you can not remove an artifact type once it is defined.
I'm confused how these 2 sentences are related (this is unrelated to registries being in active development). 

```suggestion
W&B Registries is in active development. Currently, you can not remove an artifact type once it is added and the registry settings are saved.  
```
^ why is the note on artifact types here? this should be noted in context when we talk about editing types

2024-06-06 02:24 UTC, noaleetz commented on docs/guides/registry/create_registry.md
> +5. Select who can view the registry from the **Registry visibility** dropdown. See [LINK] for more information on how to limit visibility.
```suggestion
5. Select who can view the registry from the **Registry visibility** dropdown. See [LINK] for more information on what the available options are for registry visibility.
```

2024-06-06 02:27 UTC, noaleetz commented on docs/guides/registry/create_registry.md
> +6. Select either **All types** or **Specify types** from the **Accepted artifacts type** dropdown.
it's not going to be obvious to new users who don't know what artifacts are what accepted artifact types are. I think we should have a section that talks about "Defining a registry's accepted types" - this should explain what types are, how they are set when creating artifacts, what are the implications of selecting All types vs specify types, why you should standardize accepted types (i.e so a user doesn't link a model artifact to dataset registry). Types is an important mechanism for how a user organizes their registry and enforces that the right things go in the right registries.

2024-06-06 02:28 UTC, noaleetz commented on docs/guides/registry/create_registry.md
> +The preceding image shows a custom registry called "Forecast" that a user is about to create. The registry is set to **Restricted** [LINK] which means that only members that are manually added to the
can pick a registry name and type example that makes a bit more sense - i.e Benchmark Datasets, and type is "hf-dataset"

2024-06-06 02:28 UTC, noaleetz commented on docs/guides/registry/create_registry.md
> +The following steps describe how to restrict the visibility of a custom registry that already exists:
can we just show this in a gif instead of listing out all the steps?

2024-06-06 02:29 UTC, noaleetz commented on docs/guides/registry/create_collection.md
> +5. Optionally provide a description of your collection in the **Description** field.
do we need the optional steps here?

2024-06-06 02:31 UTC, noaleetz commented on docs/guides/registry/create_collection.md
> +Administrators of a registry can optionally add additional artifact types that the registry accepts. Note that you can not remove artifacts types from a core registry once they are added.
```suggestion
Registry admins can add additional accepted artifact types by navigating to the registry settings. Once an accepted type is added to the settings, it cannot be removed.
```

2024-06-06 02:32 UTC, noaleetz commented on docs/guides/registry/create_collection.md
> +10. From the **Version** dropdown, select the artifact version you want to link to your collection.
similar to current model registry, we should have a section on linking to a registry. There are multiple ways to do this, and this list only covers one way. 

We can borrow some of the explanations from existing linking to the model registry docs. We should make sure to emphasize that linking == publishing to the registry, and bring the version from a more private, project level scope, to this shared org level space (any users w access to the registry can access the linked version)

2024-06-06 02:33 UTC, noaleetz commented on docs/guides/registry/create_collection.md
> +## Create a collection within a core registry
creating a collection for core and custom registries is the same. we should only show this once. 

let's make sure there is a gif associated with the workflow (in general anything that has a long list of instructions I think can be replaced by a gif, or at the very least be accompanied by a gif). These lists are really long and clunky to read, most users probably skip them.

2024-06-06 02:35 UTC, noaleetz commented on docs/guides/registry/create_collection.md
> +For example, the proceeding image shows a registry named "Forecast". Within the "Forecast" registry there are two collections called "LowLightPedRecog-YOLO" and "TextCat". "LowLightPedRecog-YOLO" col
can we had an example from the model registry, not forecast? We have a bunch of good LLM task names in the reviewco registry - https://wandb.ai/reviewco/registry/model?selectionPath=reviewco%2Fmodel-registry%2FFinetuned-Review-Autocompletion&view=versions

2024-06-06 02:37 UTC, noaleetz commented on docs/guides/registry/create_collection.md
> +10. From the **Version** dropdown, select the artifact version you want to link to your collection.
In the same 'linking to a registry' guide we should explain the term source vs linked artifact version

2024-06-06 02:38 UTC, noaleetz commented on docs/guides/registry/configure_registry.md
> +Registries, and the linked artifacts inside of them, are scoped at the organization level. This means that teams within an organization can share artifacts linked in a registry.
```suggestion
Registries, and the linked artifacts inside of them, belong to the organization. This means that teams within an organization can publish and consume artifacts linked to a registry, given the correct access control.
```

2024-06-06 02:39 UTC, noaleetz commented on docs/guides/registry/configure_registry.md
> +# Configure registry access
we should just call this registry settings or something because we will refer to the registry settings across this doc

2024-06-06 02:41 UTC, noaleetz commented on docs/guides/registry/configure_registry.md
> +Organization admins can limit who can access a registry by configuring user-defined roles for that registry. User defined roles are useful for fine-grained control on how specific members within an o
nope - registry admins (by default an org admin will be a registry admin, but someone who is not an org admin can still be granted this access for a registry). 

the roles are not user defined - we have 4 options for roles - viewer, member, admin, owner

2024-06-06 02:42 UTC, noaleetz commented on docs/guides/registry/configure_registry.md
> +For example, a user with member access in the core Model registry can be be assigned viewer access in the core Dataset registry.
let's avoid referring to something as a core Dataset Registry - we should just call it Model Registry or Dataset Registry. There really isn't too much different in the behavior of the core and custom registry for now.

2024-06-06 02:42 UTC, noaleetz commented on docs/guides/registry/configure_registry.md
> +A user within an organization can have different roles, and therefore permissions, for each registry in their organization. Organization administrators can set a given user's permission.
```suggestion
A user can have different roles, and therefore permissions, for each registry in their organization. Registry admins can set a given user's permission.
```

2024-06-06 02:44 UTC, noaleetz commented on docs/guides/registry/configure_registry.md
> +## Configure user roles in a registry
this is in general, but the settings page is accessible by everyone, but can only be changed by an admin. Sections that are only relevant for someone with registry admin access should be clearly marked (and ideally they should be consolidated in 1 area/guide so that a regular user doesn't have to keep scrolling through them when not relevant to them)

2024-06-06 02:46 UTC, noaleetz commented on docs/guides/registry/configure_registry.md
there a few important [callouts](https://weightsandbiases.slack.com/archives/C05UUJ350CA/p1712262412947029) that on roles and settings that would be good to review / decide if or where they should go in this guide:
<img width="448" alt="Screenshot 2024-06-05 at 7 46 40 PM" src="https://github.com/wandb/docodile/assets/40642416/73afd5ef-d2ff-4983-addc-b85948532d18">

2024-06-06 02:56 UTC, noaleetz commented
A few high-level comments that we discussed:
1. all the relevant section from the old model registry docs need to be added / changed to apply to the generic registry tone (i.e link a model to the registry). Those will all still apply 
2. we should replace long list with gifs where we can, the long lists of instructions can be super hard to digest and most users will skip them
3. Let's try to de-emphasize differences between core and custom registries since they largely function the same, I don't want users to get tripped up. 
4. The examples should mostly focus on model and dataset registry, or realistic/common artifacts or collections an avg ML team might have - especially when referring to hierarchy (you can always ask Meril to edit the text or make a copy of a specific screen w a different set of text)
5. We should have a guide and creating model and dataset cards - this is a big selling point when talking to users so we should call it out
6. I left a few comments there are changing the hierarchy / combining some of the guides and section and renaming them - as a first step before doing any big rewriting, would be great if you can share the next iteration of guide names and the section names within them (including the old workflows from model registry we also need to include) so we can make sure we're aligned there (so that you don't do any big rewriting and then the hierarchy has to be changed again) 
7. We'll probably also want a section that's a landing page for "how to access your old model registry". There we can also put details of what the changes from old model registry that I outlined in the Intros to Registries doc to help existing model registry users understand the changes, and also put details of the migration when we offer it in future.

2024-06-06 02:58 UTC, noaleetz requested changes
round 1 of comments - let's focus on intro last (I didn't leave comments on that)

2024-06-17 17:01 UTC, ngrayluna commented on docs/guides/registry/registry_types.md
> +| Flexibility    | Limited to adding additional types to the existing list.| High flexibility. Users can customize names, descriptions, accepted artifact types and visibility.|
Changed to "customization"

2024-06-17 17:15 UTC, ngrayluna commented on docs/guides/registry/registry_types.md
> +| Restricted   | Only invited organization members can view and edit the registry.|
Noted. The idea behind this table was to highlight  who can see the registry. 

Sort of like, "who has permission to know the registry exists" sort of thing... but perhaps that's the wrong way to think about "visibility"?

2024-06-17 17:15 UTC, ngrayluna commented on docs/guides/registry/registry_types.md
> +| Metadata       | Preconfigured and not editable by users. | Users can edit.  |
Description, etc.?

2024-06-17 17:53 UTC, ngrayluna commented on docs/guides/registry/create_registry.md
> +Create a custom registry within an organization. Custom registries are particularly useful for organizing project-specific requirements that differ from the default, core registries that W&B provides
This is a dumb question: will it not be a common use case for  users to use the default Dataset registry for (e.g.) evaluation datasets, fine-tuning datasets? In this case, they would create a collection for this task?

2024-06-17 17:56 UTC, ngrayluna commented on docs/guides/registry/create_registry.md
> +W&B Registries is in active development. Currently, you can not remove an artifact type once it is defined.
It's referenced in step #6:

"6. Select either **All types** or **Specify types** from the **Accepted artifacts type** dropdown."

2024-06-17 17:59 UTC, ngrayluna commented on docs/guides/registry/create_registry.md
> +Create a custom registry within an organization. Custom registries are particularly useful for organizing project-specific requirements that differ from the default, core registries that W&B provides
Which brings me to: What is the canonical ml workflow example that will resonate with new users and custom registries?

2024-06-17 17:59 UTC, ngrayluna commented on docs/guides/registry/registry_types.md
> +| Organization | Anyone in the organization can view the registry. |
[See comment below]

2024-06-17 19:13 UTC, ngrayluna commented on docs/guides/registry/create_registry.md
> +The preceding image shows a custom registry called "Forecast" that a user is about to create. The registry is set to **Restricted** [LINK] which means that only members that are manually added to the
I'm limited to the prototype example (it's the only one we have w/ this workflow) 😬

2024-06-17 19:14 UTC, ngrayluna commented on docs/guides/registry/create_registry.md
> +The following steps describe how to restrict the visibility of a custom registry that already exists:
We will use both. Text is required for accessibility reasons.

2024-06-17 19:20 UTC, ngrayluna commented on docs/guides/registry/create_collection.md
> +For example, the proceeding image shows a registry named "Forecast". Within the "Forecast" registry there are two collections called "LowLightPedRecog-YOLO" and "TextCat". "LowLightPedRecog-YOLO" col
I'm limited to the ones we have in the mock up UI...I want to show what we describe

2024-06-17 19:24 UTC, ngrayluna commented on docs/guides/registry/configure_registry.md
> +# Configure registry access
Given how complex the access roles/rules are, it makes sense to have this page front and cnter. We can make a separate page for other settings?

2024-06-17 19:27 UTC, ngrayluna commented on docs/guides/registry/configure_registry.md
> +Organization admins can limit who can access a registry by configuring user-defined roles for that registry. User defined roles are useful for fine-grained control on how specific members within an o
A little confused, can't the admin decide these roles for members of an org?

2024-06-18 04:30 UTC, ngrayluna commented on docs/guides/registry/registry_types.md
> +Use custom registries for greater flexibility and customization. [INSERT]
See this comment: https://github.com/wandb/docodile/pull/689#discussion_r1643194394

2024-06-18 04:31 UTC, ngrayluna commented on docs/guides/registry/create_registry.md
> +The preceding image shows a custom registry called "Forecast" that a user is about to create. The registry is set to **Restricted** [LINK] which means that only members that are manually added to the
We can update once we have another example

2024-06-18 04:36 UTC, ngrayluna commented on docs/guides/registry/configure_registry.md
> +## Configure user roles in a registry
I imply that only admins can edit/that this info pertains only to them, but I can make it more obvious by putting it in an info block?: 
<img width="558" alt="Screen Shot 2024-06-17 at 9 35 37 PM" src="https://github.com/wandb/docodile/assets/15202580/90d2e967-1849-498c-a079-59dd0845d7a9">

2024-06-18 04:51 UTC, ngrayluna commented on docs/guides/registry/create_collection.md
> +10. From the **Version** dropdown, select the artifact version you want to link to your collection.
Makes sense. I'll add that to the next draft.

2024-06-18 04:56 UTC, ngrayluna commented on docs/guides/registry/configure_registry.md
We need to find a way to make this easy to understand for new users....I suggest that some of this be doubly emphasized in the rollout plan/email/marketing. In like a "What's new" or "What's changing".  From that wording, we can steal that and add it on the landing page for the Registry docs.

2024-06-21 02:05 UTC, noaleetz commented on docs/guides/registry/configure_registry.md
we don't need to directly put this list - I just wanted to share it with you to give context on different concepts that are distributed already across this PR (its a mini FAQ for you to consult on some of the default behaviors)

2024-06-21 02:06 UTC, noaleetz commented on docs/guides/registry/configure_registry.md
> +# Configure registry access
Sure - what if we had 2 pages:
1. Access Controls
2. Registry Settings (separate page for other settings)

2024-06-21 02:24 UTC, noaleetz commented on docs/guides/registry/configure_registry.md
> +Organization admins can limit who can access a registry by configuring user-defined roles for that registry. User defined roles are useful for fine-grained control on how specific members within an o
Ah yes - so this part is a bit tricky - we have 3 set of roles (or 3 scopes of a role): Org roles, team roles, registry roles. Your role in a team has no impact or relationship on your role in any registry - a registry is an object that belongs to org, not a team. So no matter your role in any team, it won't impact any permissions you have on any team. 

Custom roles only exist for [teams](users can be assigned custom org roles only at the team level.) (you can't have a custom role inside an org (in [this](https://docs.wandb.ai/guides/hosting/iam/manage-users#invite-users) section of docs you'll see that when managing org users you only have these 3 options: "Select the role you want to assign to the user, from Admin, Member or Viewer. By default, all users are assigned a Member role". 

To be more specific - the language I was calling out here is that (1) Registry admins limit registry access rather than org admins (you can be a registry admin either by being an org admin, or if someone makes you an admin in the registry), and (2) you can't have a user-defined role in a registry - you can only be assigned 1 of 3 roles. 

> Organization admins can limit who can access a registry by configuring user-defined roles for that registry. User defined roles are useful for fine-grained control on how specific members within an organization can interact with a registry. 
Registry admins can limit who can access a registry by navigating to a registry's settings and assigning a user's role to Admin, Member, or Viewer. User's can have different roles in different registries, for example, a viewer in the Model Registry and a member in the Dataset Registry. This is useful to limit who has write-access to certain registries.

2024-06-21 02:28 UTC, noaleetz commented on docs/guides/registry/configure_registry.md
> +## Configure user roles in a registry
ooh I didn't follow what this screenshot refers to - is it to point out an info block and what that looks like? 

But anyways, yes, I think we should call out explicitly at the top of "Access Controls" section, and "Configure Registry Settings" section (we discussed [here](https://github.com/wandb/docodile/pull/689/files#r1648328099) that we will have 2 sections -> I think in an info block this is a good idea right after the header "Note - you must be a Registry admin to..."

2024-06-21 02:55 UTC, noaleetz commented on docs/guides/registry/create_registry.md
> +Create a custom registry within an organization. Custom registries are particularly useful for organizing project-specific requirements that differ from the default, core registries that W&B provides
Not a dumb question - yes, technically, Evaluation Datasets or Benchmark datasets VS. training datasets - they're all datasets. But they are used in different contexts and they're versioned independently of each other. 

Training Dataset:
- Model reproducibility.
- Track data changes for continuous improvement.
- Facilitate experimentation by comparing models on different data versions.
- Format: Large, diverse text data in formats like plain text, JSON, CSV. May include raw text, annotations.

Benchmark Dataset:
- Consistent evaluation over time.
- Fair comparison between models or versions.
- Track improvements in evaluation quality without affecting previous benchmarks.
- Format: Smaller, focused, high-quality annotated data in formats like JSON, CSV.

**What would different collections be called within each registry?**

Training Dataset (in Dataset Registry) (might contain raw data that is scraped): 
- Raw_User_Browsing_History
- Raw_Product_Descriptions_Reviews
- Raw_Transaction_Logs

Benchmark Dataset (curated for validation to produce a score):
- Curated_User_Profiles_Known_Preferences
- Curated_Product_Lists_Expert_Recommendations
- Curated_Historical_Recommendation_Outcomes

And then for fine-tuning, you might have a registry that has these tasks:

- Fine_Tuning_Code_Completion_Dataset
- Fine_Tuning_Code_Documentation_Dataset
- Fine_Tuning_Bug_Reports_Resolution_Dataset
- Fine_Tuning_Constitutional_Law_Cases_Dataset
- Fine_Tuning_Legal_Documents_Summarization_Dataset
- Fine_Tuning_Patent_Law_Analysis_Dataset
- Fine_Tuning_Healthcare_EHR_Data

Within those tasks, there could still be versioning that happens (you delete corrupted data, add a new corpus of data for that task)

2024-06-21 03:07 UTC, noaleetz commented on docs/guides/registry/create_registry.md
> +Create a custom registry within an organization. Custom registries are particularly useful for organizing project-specific requirements that differ from the default, core registries that W&B provides
**Project: Developing an Ensemble of LLMs to Answer Questions on Medical Insurance Policies**

1. **Registry Name: Raw_Datasets**
   - **Purpose**: Store the initial raw data collected from various sources before any preprocessing or cleaning.
   - **Contents**:
     - `Raw_User_Queries_Data`: Unprocessed text data gathered from user interactions, customer service logs, or other sources where users ask questions about medical insurance policies.
     - `Raw_Insurance_Policies`: Collected medical insurance policy documents, including terms and conditions, coverage details, and exclusions.

2. **Registry Name: Training_Datasets**
   - **Purpose**: Contain the data that has been cleaned, preprocessed, and is ready for training the model.
   - **Contents**:
     - `User_Query_Insurance_Answer_Training_Data`: Pairs of user questions and corresponding answers extracted from insurance policies. This dataset is used to teach the LLM how to accurately respond to queries about medical insurance policies.

3. **Registry Name: Benchmark_Datasets**
   - **Purpose**: Hold curated datasets used to evaluate the performance of the trained models. These datasets are designed to provide a consistent measure of model accuracy and effectiveness.
   - **Contents**:
     - `User_Query_Insurance_Answer_Test_Data`: A set of user questions and corresponding expert-validated answers that the model has never seen during training. This dataset is used to test the model’s ability to accurately answer new questions about medical insurance policies.

4. **Registry Name: Fine_Tuned_Models**
   - **Purpose**: Store the versions of models that have been fine-tuned on the specific training datasets for different parts of the ensemble model pipeline.
   - **Contents**:
     - `Fine_Tuned_Query_Classifier_v1`: First version of the model fine-tuned to classify the type of user query.
     - `Fine_Tuned_Policy_Extractor_v1`: First version of the model fine-tuned to extract relevant sections from insurance policies.
     - `Fine_Tuned_Response_Generator_v1`: First version of the model fine-tuned to generate user-friendly responses based on extracted policy sections.

5. **Registry Name: Deployment_Configs**
   - **Purpose**: Store configurations and parameters necessary for deploying the trained models into a production environment.
   - **Contents**:
     - `Query_Classifier_Deployment_Config`: Configuration files for deploying the query classification model.
     - `Policy_Extractor_Deployment_Config`: Configuration files for deploying the policy extraction model.
     - `Response_Generator_Deployment_Config`: Configuration files for deploying the response generation model.

Each registry serves a specific purpose in the machine learning pipeline, from initial data collection to final model deployment.

2024-06-21 03:16 UTC, noaleetz commented on docs/guides/registry/create_registry.md
> +The preceding image shows a custom registry called "Forecast" that a user is about to create. The registry is set to **Restricted** [LINK] which means that only members that are manually added to the
ahhhh yes ok gotcha gotcha - commented in [this](https://weightsandbiases.slack.com/archives/C01DX8LRZEJ/p1718939746641269?thread_ts=1718318901.046779&cid=C01DX8LRZEJ) thread so you can start using feature

2024-06-21 03:16 UTC, noaleetz commented on docs/guides/registry/create_collection.md
> +For example, the proceeding image shows a registry named "Forecast". Within the "Forecast" registry there are two collections called "LowLightPedRecog-YOLO" and "TextCat". "LowLightPedRecog-YOLO" col
ah yes gotcha - see above [comment](https://github.com/wandb/docodile/pull/689#discussion_r1648363619) on using the live beta

2024-06-21 03:21 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +| Restricted   | Only invited organization members can view and edit the registry.|
Ah yes. Maybe we should try to use language like access (since view and edit have connotations of specific permission). The idea of different visibility, and what we should highlight is "who has access to the registry by default" -> note I used access which is agnostic / avoid specifying view vs edit. 

`| Visibility | Description | Default Role
| --- | --- | --- | 
| Organization | Everyone in the org can access the registry. | If you are an admin for your org, you'll be an admin for the registry by default. All other users will be a viewer in the registry by default | 
| Restricted   | Only invited org members can access the registry.| The user who created the restricted registry is the only user in the registry by default, and is the org's owner. `

2024-06-21 03:26 UTC, noaleetz commented on docs/guides/registry/registry_types.md
> +| Organization | Anyone in the organization can view the registry. |
commented in there - we should use "access" if we're trying to be agnostic to whether you have read or write access

2024-06-21 03:27 UTC, noaleetz requested changes
addressed all comments! 

I invited you to a team inside this org "registries-bug-bash" -> https://beta.wandb.ai/registry -> are you able to access it? Not everything is perfect in it yet styling wise but feel free to play around with it and if there's a particular workflow that looks similar enough to prototype but here you can customize the names, permissions, etc if helpful

2024-06-25 18:47 UTC, ngrayluna commented on docs/guides/registry/create_registry.md
> +Create a custom registry within an organization. Custom registries are particularly useful for organizing project-specific requirements that differ from the default, core registries that W&B provides
Ahh. OK, so the mapping is to have registry for ea. step of the ML pipeline. 

The mental model I had was a one stop shop for all data (in the case of registry with dataset type) related to a specific ML task. For e.g. Suppose I want to train a CNN to classify/identify earthquakes from seismogram recordings. In this case:

* Registry name: Realtime earthquake data (seismograms)
   * Collections:
      * Northern California earthquake data 
         * V0 raw dataset
         * V1 processed dataset
      * Southern California earthquake data 
         * V0 raw dataset
         * V1 processed dataset
      * Training data
         * Combined, processed NorCal and SoCal dataset: v0  
      * Test data
         *  Subset of combined, processed NorCal and SoCal dataset: v0  

So, in the example you have, you have a separate registry for raw and processed datasets. (Whereas I just bunch it into one).

For the model part:

* Registry name: CNN Earthquake Classifier
   * Collections:
      * CNN (2 layers only)
         * model:v0 
         * model:v1
      * CNN (4 layers)
         * model:v0 
         * model:v1
      * Transfer learning CNN using MNIST
         * model:v0 
         * model:v1

2024-06-26 03:36 UTC, ngrayluna commented on docs/guides/registry/create_registry.md
> +Create a custom registry within an organization. Custom registries are particularly useful for organizing project-specific requirements that differ from the default, core registries that W&B provides
Anyhow, I used one of the examples you listed above.

2024-06-26 03:52 UTC, ngrayluna commented on docs/guides/registry/create_collection.md
> +For example, the proceeding image shows a registry named "Forecast". Within the "Forecast" registry there are two collections called "LowLightPedRecog-YOLO" and "TextCat". "LowLightPedRecog-YOLO" col
@noaleetz Left a note to create a new diagram for "Create a collection" https://wandb.atlassian.net/browse/DOCS-887

[Didn't have time to link an artifacts/have artifact type available to create a collection w/in the live demos.]

2024-06-26 03:59 UTC, ngrayluna commented on docs/guides/registry/configure_registry.md
> +# Configure registry access
This will be a follow up task: https://wandb.atlassian.net/browse/DOCS-888

2024-06-26 05:13 UTC, ngrayluna commented on docs/guides/registry/configure_registry.md
> +Organization admins can limit who can access a registry by configuring user-defined roles for that registry. User defined roles are useful for fine-grained control on how specific members within an o
Noted. I changed some text and created an info blurb to summarize this.

<img width="646" alt="Screen Shot 2024-06-25 at 10 13 04 PM" src="https://github.com/wandb/docodile/assets/15202580/074768bc-7ae5-46f3-98c1-b8bf38f3f91a">


As a follow up, we should create a diagram to show this. I suspect customers will be confused by this as well.

2024-06-26 05:14 UTC, ngrayluna commented on docs/guides/registry/configure_registry.md
> +Organization admins can limit who can access a registry by configuring user-defined roles for that registry. User defined roles are useful for fine-grained control on how specific members within an o
https://wandb.atlassian.net/browse/DOCS-889

2024-06-26 06:59 UTC, ngrayluna commented on docs/guides/registry/create_collection.md
> +10. From the **Version** dropdown, select the artifact version you want to link to your collection.
Added new page" https://docs-beta.wandb.ai/guides/registry/link_version

2024-06-26 07:03 UTC, ngrayluna commented
@noaleetz Except for the main landing page I think the docs are "ready" for MVP docs. 

Action item for MVP release:
1. Review 
2. Provide content for the landing page.
3. Noah to add Raven's image to landing page (once name is changes from "Registries" -> "Registry" (see Figma note).

Note:
There are a several post MVP updates to do. You can see the child Jira issues here: https://wandb.atlassian.net/browse/DOCS-846

2024-06-26 07:08 UTC, ngrayluna commented on docs/guides/registry/link_version.md
> +For example, the following image shows a `v0` model version called `artifact-joe-clo` (see **Source version** field `artifact-joe-clo:v0`), linked to a collection called `"Joe Clos other collection"`
Note: This is only temp (see comments and Jira child issue).

2024-06-26 20:32 UTC, noaleetz commented on docs/guides/registry/intro.md
> +<!-- To do: Add Raven's new diagram -->
<img width="709" alt="Registry-structure-graphic-docs" src="https://github.com/wandb/docodile/assets/40642416/48a105c9-1911-4c3e-a770-5f66c7525d8c">

Raven has updated this so we should be good to go with inserting!

2024-06-26 20:44 UTC, noaleetz commented on docs/guides/registry/intro.md
> +A *registry* is a [INSERT]. You can think of a registry as the top most level of a directory. Each registry consists of one or more sub directories called collections. A *collection* is a folder or a
```suggestion
A *registry* is a repository or catalog for ML assets of the same kind. You can think of a registry as the top most level of a directory. Each registry consists of one or more sub directories called collections. A *collection* is a folder or a set of linked [*artifact versions*](../artifacts/create-a-new-artifact-version.md) inside a registry. An [artifact version](../artifacts/create-a-new-artifact-version.md) is a single, immutable snapshot of an artifact at a particular stage of its development.  A registry belongs to an organization, not a specific team.
```

2024-06-26 20:53 UTC, noaleetz commented on docs/guides/registry/intro.md
> +W&B Registry is in active development.
```suggestion
W&B Registry is in private preview. Please contact your account team or support@wandb.com for early access.  
```

2024-06-26 20:58 UTC, noaleetz commented on docs/guides/registry/intro.md
> +## Migrating from W&B Model Registry to W&B Registry
```suggestion
## Migrating from team W&B Model Registry to W&B Registry
```

2024-06-26 21:07 UTC, noaleetz commented on docs/guides/registry/intro.md
> +[INSERT blurb on how this impacts customers]
```suggestion
If your team is actively using the existing W&B Model Registry to organize your models, this will still be available through the new Registry UI. Navigate to the Model Registry from the homepage, and the banner will allow to select a team and visit it's model registry.

https://github.com/wandb/docodile/assets/40642416/3b4376ee-0464-45ee-b5dd-46f6b0b59dcf

Please look out for incoming information on a migration we will be making available to migrate contents from the current model registry into the new model registry inside W&B Registry. You can reach out to support@wandb.com with any questions or to speak to our product team about any concerns with the migration.
```

2024-06-26 21:09 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +## Interactively link an artifact version
```suggestion
## How to link an artifact version to a registry collection
```
interactively link sounds a bit redundant with the main header - do we need it? Or can we replace it to be more specific to what this section will show? See my proposed changes for the main header

2024-06-26 21:09 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +# Link an artifact version to a collection
```suggestion
# Link an artifact version to a registry
```

2024-06-26 21:17 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +## View the source of linked artifacts
we shouldn't be recommending to people that they look at the underlying project - I think we should reserve this section to focus on the difference between a source and linked version. Not everyone will have access to the underlying project.

Source version: the artifact version inside a team's project that is logged to a W&B Run.  
Linked version: the artifact version that is published to the registry. This is really a pointer to the source artifact, and is the exact same artifact version, just made available in the scope of the registry.

2024-06-26 21:21 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +## View the source of linked artifacts
```suggestion
## Source artifacts vs. linked artifacts
```

2024-06-26 21:51 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +    {label: 'Artifact browser', value: 'artifacts_ui'},
```suggestion
    {label: 'Artifact browser', value: 'artifacts_ui'},
    {label: 'Link via API', value: 'link_to_registry_via_api'}
```

2024-06-26 21:51 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +  defaultValue="registry_ui"
```suggestion
  defaultValue="link_to_registry_via_api"
```

2024-06-26 21:58 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +
```suggestion
</TabItem>
  <TabItem value="link_to_registry_via_api">

To link via API, use the `link_artifact` method. Here is a small code snippet showing how to do this:

```python
import wandb 

ARTIFACT_NAME = "<ARTIFACT-TO-LINK>"
ENTITY_NAME = "<TEAM-ARTIFACT-BELONGS-IN>"
PROJECT_NAME = "<PROJECT-ARTIFACT-TO-LINK-BELONGS-IN>"

ORG_ENTITY_NAME = "<YOUR ORG NAME>"
REGISTRY_NAME = "<REGISTRY-TO-LINK-TO>" # to link to model registry this should be set to "model"
COLLECTION_NAME = "<REGISTRY-COLLECTION-TO-LINK-TO>"

with wandb.init(entity=ENTITY_NAME, project=PROJECT_NAME) as run:
    artifact = wandb.Artifact(ARTIFACT_NAME, "model")
    with tempfile.NamedTemporaryFile(delete=False) as temp_file:
        temp_file.write(b"model file to link to registry")
    artifact.add_file(temp_file.name)
    run.link_artifact(
        artifact=artifact,
        target_path=f"{ORG_ENTITY_NAME}/wandb-registry-{REGISTRY_NAME}/{COLLECTION_NAME}",
        aliases=["staging"],
    )
Refer to the [link_artifact method documentation](https://docs.wandb.ai/ref/python/run#link_artifact) for more details.

```

2024-06-26 22:49 UTC, merged