Update and rename automation.md to model-registry-automations.md
wandb/docs pull request #701
Opened 2024-06-10 21:20 UTC by noaleetz

## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-06-11 20:23 UTC, jcrawley approved these changes

2024-06-13 15:41 UTC, ngrayluna requested changes
To do: 

Update sidebar.js + find all mentions of this doc page in the current docs + add redirects.

2024-06-14 00:24 UTC, noaleetz commented
Btw I'm going to pull out the changes for updating the linked resources into a different PR until we changed the sidebar

2024-06-18 21:50 UTC, closed without merging

2024-06-18 21:50 UTC, ngrayluna commented
Closing. Duplicate of this: https://github.com/wandb/docodile/pull/717