Operator updates
wandb/docs pull request #703
Opened 2024-06-12 06:56 UTC by mkaesz-wandb

## Description

- Updated the W&B Kubernetes Operator documentation: Why we did the change, config reference, deploy instructions, console access, faq
- Updated the "Install on AWS" section with instructions on how to migrate to operator
- Updated the "Install on bare metal" section by replacing install instructions with references to W&B operator

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [x] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [x] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-06-17 23:13 UTC, adityachoudhari26 approved these changes

2024-06-18 08:58 UTC, flamarion requested changes
Hey @mkaesz-wandb , there are some comments from `Vale` about the terms that should be fixed.
Not sure if it's still mandatory but in the past I've been asked to fix them in my PRs.
Without then would definitely be easier to review 😄 but feel free to let others jump in and comment if they are required to fix.

2024-06-18 09:14 UTC, flamarion approved these changes

2024-06-18 09:14 UTC, flamarion commented on docs/guides/hosting/self-managed/aws-tf.md
> +### Before and after Architecture
This may make sense.
According to ChatGPT `Corrected Title: "Before and after architecture"`

2024-06-18 09:17 UTC, mkaesz-wandb commented on docs/guides/hosting/self-managed/aws-tf.md
> +### Before and after Architecture
Vale will complain if I change that. The A or architecture must be in capital letter.

2024-06-20 15:48 UTC, zacharyblasczyk approved these changes

2024-07-18 00:26 UTC, ngrayluna approved these changes

2024-07-18 00:26 UTC, merged