Add code snippet on how to organze model w/ public API
wandb/docs pull request #713
Opened 2024-06-17 15:46 UTC by ngrayluna

## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

https://wandb.atlassian.net/jira/software/projects/DOCS/boards/28?selectedIssue=DOCS-871&sprintStarted=true

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-06-18 01:24 UTC, noaleetz commented on docs/guides/model_registry/organize-models.md
> +registered_model.tags = ["test1", "test2"]
```suggestion
registered_model.tags = ["property1", "property2"]
```

2024-06-18 01:26 UTC, noaleetz commented on docs/guides/model_registry/organize-models.md
> +registered_model.save()
can we also show a snippet for how to add a tag to this list (how a user might come back and later append a tag in a future workflow)

`registered_model.tags = registered_model.tags + ["property3"]`

2024-06-18 01:28 UTC, noaleetz commented on docs/guides/model_registry/organize-models.md
we should consider framing this as something different than organizing models since it also involves renaming the registered model and editing description. The new piece here is that you can now programmatically fetch an artifact collection and directly update its properties.

2024-06-18 01:29 UTC, noaleetz requested changes
adding @amusipatla-wandb as a reviewer

2024-09-25 23:03 UTC, ngrayluna commented
stale. closing

2024-09-25 23:03 UTC, closed without merging