docs(launch): warn sweeps on launch does not support config file inputs
wandb/docs pull request #718
Opened 2024-06-19 00:32 UTC by bcsherma

## Description

Sweeps on launch does not currently support varying config file inputs. We want to notify users of this limitation in the relevant docs.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-06-19 03:10 UTC, KyleGoyette approved these changes

2024-06-20 22:06 UTC, ngrayluna commented on docs/guides/launch/job-inputs.md
> +[Sweeps on Launch](./sweeps-on-launch.md) does not support sweeping over config file inputs. Sweep parameters must be controlled through the `Run.config` object.
Let's use another verb that is not the product name.

E.g. Something like, "Sweeps on Launch does not support config file inputs"? 

[Not sure what "sweeping over file inputs" means..]

2024-06-23 21:29 UTC, ngrayluna requested changes
See comment

2024-06-25 02:18 UTC, bcsherma commented on docs/guides/launch/job-inputs.md
> +[Sweeps on Launch](./sweeps-on-launch.md) does not support sweeping over config file inputs. Sweep parameters must be controlled through the `Run.config` object.
Good point, I've made an update here.

2024-06-25 02:36 UTC, ngrayluna approved these changes

2024-06-25 02:36 UTC, merged