Update registry landing page.md
wandb/docs pull request #731
Opened 2024-06-27 18:26 UTC by noaleetz

still need to fix code snippet

## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-06-27 20:48 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +## How to get started
I think linking to resources that show the old Model Registry will confuse users. Let's link to resources that show the new UI, emphasize the new user story, etc.

2024-06-27 20:50 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +Track and manage your staged artifacts with a few simple steps.
Can we remove the word "staged"? Perhaps something like?: 

"Track and manage artifacts in a registry with a few simple steps"

2024-06-28 00:22 UTC, noaleetz commented on docs/guides/registry/intro.md
> +## How to get started
Until we have the equivalent docs for registry (those are the docs that I'm suggesting we include in the post-MVP epic) my thought was that we should still link to some resource in the meantime even though it is specific to model registry. We can remove but if so would like to align on potential timeline for when we can add them back so users know about these capabilities. Let's discuss more in [this](https://weightsandbiases.slack.com/archives/C05UUJ350CA/p1719525895678949?thread_ts=1719514599.925499&cid=C05UUJ350CA) thread

2024-06-28 00:24 UTC, noaleetz commented on docs/guides/registry/intro.md
> +## How to get started
for example we need to be able to link to automations for a registry

2024-06-28 00:43 UTC, noaleetz commented on docs/guides/registry/intro.md
> +Track and manage your staged artifacts with a few simple steps.
are you worried staged will intro a new potential definition? Can we do "Manage your artifacts ready for staging in a few steps"

2024-07-01 19:54 UTC, ngrayluna commented
Missed this during the first review, let's change the wording on this:

"Look out for incoming information on a migration we will be making available to migrate contents from the current model registry into the new model registry inside W&B Registry. You can reach out to support@wandb.com with any questions or to speak to our product team about any concerns with the migration."

Things to change:
1. Don't use language that dates the docs "Look out for...."
2. Refer to W&B not"our", "we", etc. 
3. This "..or to speak to our product team about any concerns with the migration." won't make sense for non beta users. Can we remove it? Or provide an email? (Or other point of contact)
4. We'll want to be careful on product capitalization. So model registry should be capitalized in "...from the current model registry into the new model registry inside W&B Registry."

2024-07-01 19:54 UTC, ngrayluna requested changes
Image HTML tag is breaking the docs: https://weightsandbiases.slack.com/archives/C01DX8LRZEJ/p1719863302819619?thread_ts=1719861040.785199&cid=C01DX8LRZEJ

2024-07-02 21:04 UTC, ngrayluna commented
Fixed images and links. Condensed intro paragraph and tried to make it less market-y and more geared to devs. Current preview here:
[Registry _ Weights & Biases Documentation.pdf](https://github.com/user-attachments/files/16074208/Registry._.Weights.Biases.Documentation.pdf)

2024-07-02 21:05 UTC, ngrayluna commented
@noaleetz Lemme know if this looks good. If yay, I'll merge :)

2024-07-02 22:29 UTC, ngrayluna approved these changes

2024-07-02 22:29 UTC, merged