Adds "collection types" section
wandb/docs pull request #738
Opened 2024-07-03 00:05 UTC by ngrayluna

## Description

Original image was weird. Only temp since I didn't have a working demo at the time.

## Ticket

https://wandb.atlassian.net/browse/DOCS-887

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-07-05 00:52 UTC, noaleetz commented on docs/guides/registry/create_collection.md
> +For example, the preceding image shows a registry named "Fine-tuned models". Within the "Fine-tuned models" registry there are is a collection called "MNIST".
can we use a screenshot that has multiple dummy collections in them? Here are some examples of other Fine-tuned Models collection names I pulled from chatgpt:

"Finetuned-Review-Autocompletion"
"Finetuned-Llama7B"
"Finetuned-BERT-Classification"
"Finetuned-GPT3-Dialogue"
"Finetuned-RoBERTa-Sentiment"
"Finetuned-ViT-Image-Classification"

2024-07-05 01:00 UTC, noaleetz commented on docs/guides/registry/create_collection.md
Sections to this guide that need to be added:
1. How to programmatically create a collection - you do this by linking to a collection that does not yet exist. So if you call link_artifact with target_path registries-bug-bash/wandb-registry-model/fancy-new-collection -> we first check if a collection with this name exists in the registry, and if it doesn't we will automatically make a new one for you with this name

2. What the type field is and how do you choose this? We need to convey in there that you will only be able to link artifacts that match this collection type, and the collection type has to be one of the allowed ones for this registry

3. Description - this field should be used to define your Model Card, Dataset Card, or Collection card and should be used for documentation. 

4. Tags - what are tags, how to change them later

These are questions a user will face when going through the drawer workflow of creating a new collection and will want to know what these fields are and if they can change them later

2024-07-05 01:00 UTC, noaleetz requested changes
🌀

2024-07-12 01:02 UTC, ngrayluna commented on docs/guides/registry/create_collection.md
@noaleetz I addressed 1 and 2. 

Should we dedicate separate pages for 3 and 4, like we did w/ Model Reg docs? https://docs.wandb.ai/guides/model_registry/organize-models and https://docs.wandb.ai/guides/model_registry/create-model-cards

2024-07-12 01:11 UTC, ngrayluna commented
@noaleetz New preview ready https://docs-beta.wandb.ai/guides/registry/create_collection

2024-07-12 20:56 UTC, noaleetz commented on docs/guides/registry/create_collection.md
we're going to be shipping a new version level tags feature so now the registry will have both collection and version tags (it won't be for another few weeks though / in dev right now) - I'm thinking we can have sections:
1. Tags (or Organize Registry with Tags, etc.)
2. Model & Dataset Cards 

In #2 we will also mention how to create cards in custom registries but I think this title is better since Model and Dataset card is more familiar than collection card

2024-07-12 21:04 UTC, noaleetz commented
> d03a744

what's the PR here I should review?

2024-07-12 21:28 UTC, noaleetz approved these changes

2024-07-12 21:28 UTC, noaleetz commented on docs/guides/registry/create_collection.md
line 50: Before you create a collection, check the artifact type that the collection accepts:

did you mean: before you link to a collection, check the artifact type that the collection accepts

2024-07-12 21:28 UTC, noaleetz commented on docs/guides/registry/create_collection.md
> When you create a collection, you must select the type of artifacts that you can link to that collection. Each collection accepts one, and only one, type of artifact.  The type of artifact that a collection can have is determined by the registry that that collection is in.
line 24: change to:
_When you create a collection, you must select the type of artifacts that you can link to that collection. Each collection accepts one, and only one, type of artifact.  The type of artifact that a collection can have is determined by the accepted types defined for that registry. You can configure the accepted types a registry allows in the registry settings. This is to ensure, for example, that model artifacts are not linked to the dataset registry. _

2024-07-29 19:34 UTC, noaleetz commented on docs/guides/registry/create_collection.md
Ah I am a bit lost

2024-07-29 19:38 UTC, ngrayluna commented on docs/guides/registry/create_collection.md
Ignore my comment to this comment. I was wrong. :)

2024-07-29 19:40 UTC, ngrayluna commented
[Create a collection _ Weights & Biases Documentation.pdf](https://github.com/user-attachments/files/16418335/Create.a.collection._.Weights.Biases.Documentation.pdf)

2024-07-29 19:43 UTC, ngrayluna commented
Ah. I see that you approved it. Merging

2024-07-29 19:43 UTC, merged