Quick updates to landing page
wandb/docs pull request #745
Opened 2024-07-10 18:49 UTC by ngrayluna

## Description

* Provides context to how the code snippet works.
* Added diagram to landing page
* Added intro blrubon definitions back 

Why the last two bullet points: 1. I think it's important we introduce users to "how it works' as soon as possible. If they want to refer, go deeper, than can optionally go to the future "terms and concepts" page.
2. When talking  w/ Phil, he liked what we did for the Launch page (which shows the major diagram and terms on the landing page). 

## Ticket

https://wandb.atlassian.net/browse/DOCS-909

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-07-10 18:50 UTC, ngrayluna commented
Preview it on Beta; https://docs-beta.wandb.ai/guides/registry

2024-07-14 04:18 UTC, noaleetz commented on docs/guides/registry/intro.md
> +2. Log an artifact version ith the run object's [`log_artifact`](../../ref/python/run.md#log_artifact) method
```suggestion
2. Log an artifact version to the run using [`log_artifact`](../../ref/python/run.md#log_artifact) method
```

2024-07-14 04:20 UTC, noaleetz commented on docs/guides/registry/intro.md
> +3. Link the artifact to a collection with the run object's [`link_artifact`](../../ref/python/run.md#link_artifact) method.
```suggestion
3. Link the artifact to the registry with the [`link_artifact`](../../ref/python/run.md#link_artifact) method. 
```

2024-07-14 04:21 UTC, noaleetz commented on docs/guides/registry/intro.md
> +# Provide the entity of your organization
```suggestion
```
i think this is redundant - it's clear that that's what is meant to be passed in the next line, we don't have to overexplain

2024-07-14 04:23 UTC, noaleetz commented on docs/guides/registry/intro.md
> +# The name of the registry you want to create
```suggestion
```
you can't create a registry programmatically this way - a new custom registry can only be created in the UI. So this would instead be the name of the registry you want to link to. The link_artifact will fail if you try to link to a registry that doesn't exist. I think this comment can be inline and doesn't require a separate line

2024-07-14 04:23 UTC, noaleetz commented on docs/guides/registry/intro.md
> +# The name of the collection you want to create
I would probably also frame this as the the collection you want to link to, if none exists, a new one will be created. We need to avoid adding too much redundant info in the quick-starts, especially info that is already repeated in the python SDK docs (reference docs) for a specific function.

2024-07-14 04:28 UTC, noaleetz commented on docs/guides/registry/intro.md
>  registry_name = "<registry_name>"
```suggestion
registry_name = "model"
```
At the quickstart, users won't be familiar with custom registries, I would prefer to guide them to linking directly to the model registry since this is the most common registry use case and is there by default. In later sections, for example in the section on linking to a registry, we can make this more generic. But the goal of this quickstart is to make it as easy as possible to get your first version in W&B registry

2024-07-14 04:29 UTC, noaleetz commented on docs/guides/registry/intro.md
> +The proceeding code sample logs and link a pseudo model artifact called `my_model.txt` to a registry called "Models".
```suggestion
The proceeding code sample logs and link a simulated model file called `my_model.txt` to the model registry. 
```

2024-07-14 04:31 UTC, noaleetz commented on docs/guides/registry/intro.md
>  4. Next, log the simulated model file to the run as an artifact called "gemma-finetuned-3twsov9e". Note that, because we want to link the artifact to the Models registry(next step), that we specify `
```suggestion
4. Next, log the simulated model file to the run as an artifact called "gemma-finetuned-3twsov9e". Note that because we are linking the artifact to the model registry (next step), we specify `"model"` as the artifact's type (`type="model"`).
```

2024-07-14 04:35 UTC, noaleetz commented on docs/guides/registry/intro.md
> +# Provide the name of your organization
We're defining and commenting redundant information here. I really want to air on the side of the quickstart being short and sweet due to feedback that users always feel like it is a lot of work and activation energy to start linking. It's really important that a user knows that in a few lines of code, a user can log an artifact and link it, and they don't need to learn too much or make so many decisions to get their 1st model successfully linked

2024-07-14 04:35 UTC, noaleetz commented on docs/guides/registry/intro.md
> -    target_path=f"<INSERT-ORG-NAME>/wandb-registry-model/registry-quickstart-collection"
can we keep this format of created the path? I really don't think we need a whole 2 lines just to define variables that are going to passed in here.

2024-07-14 04:39 UTC, noaleetz requested changes
I still feel strongly about keeping this code snippet on the landing page short and sweet. I've gotten a lot of feedback from SMLEs and from Lukas that it can feel overwhelming + require a lot of mini decisions, to successfully get to that 1st "ah-ha I made a version show up in my model registry" and I want to air this time on the side of making the quickstart overly simply. If we get feedback that it doesn't define enough things we can go back, but a developer really needs to see that this takes only 3 lines of code to do, even if they don't understand every nitty gritty detail at the landing page. That's why we have the rest of the guides to support them with!

2024-07-15 23:12 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +# The name of the collection you want to create
True. But the SDK is also not that clear....that's why it's more specific here

e.g. if we look at link_artifact: https://docs.wandb.ai/ref/python/run#link_artifact

the definition of target_path does not specify what users need to provide for the registry

2024-07-15 23:24 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +# Provide the name of your organization
I added this here because I hit an error when I tried to create my first collection and registry on my own; I specified the wrong entities (personal vs team vs org)

It was like an "Ah ha" moment when I figured out that we need to provide the org entity, not a Team entity. Hence, why it is mentioned here.

2024-07-15 23:25 UTC, ngrayluna commented on docs/guides/registry/intro.md
> -    target_path=f"<INSERT-ORG-NAME>/wandb-registry-model/registry-quickstart-collection"
We can, but it makes Lukas rage quit when he can't see the text w/out side scrolling.

2024-07-15 23:30 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +# Provide the name of your organization
I think part of the issue is that the path we need to specify is so long. This means that:
1 and it requires a lot for the user to specify...some of which are new to them . E.g. collections. 
2. I need to separate the variables because the path is so long that people need to side scroll to see the whol path. Lukas rage quits w/ side scrolling...

2024-07-15 23:32 UTC, ngrayluna commented
> I still feel strongly about keeping this code snippet on the landing page short and sweet. I've gotten a lot of feedback from SMLEs and from Lukas that it can feel overwhelming + require a lot of mini decisions, to successfully get to that 1st "ah-ha I made a version show up in my model registry" and I want to air this time on the side of making the quickstart overly simply. If we get feedback that it doesn't define enough things we can go back, but a developer really needs to see that this takes only 3 lines of code to do, even if they don't understand every nitty gritty detail at the landing page. That's why we have the rest of the guides to support them with!

Agreed. The example I have is literally as short as the example can be (30 lines of code) + 3 steps calling out what to do: 

<img width="673" alt="Screen Shot 2024-07-15 at 4 33 28 PM" src="https://github.com/user-attachments/assets/8e67dcb1-7d6e-4e1a-bf72-2744c256decc">

vs the one they copy and paste (36 lines of code) + 5 steps of explaining:
 
<img width="684" alt="Screen Shot 2024-07-15 at 4 34 51 PM" src="https://github.com/user-attachments/assets/cf317420-87bc-4bd8-bdbd-ef809f684445">


Taking a step back here, who is this landing page for? Who is our target audience? I think it's important to teach good practices for new users. 

The verbosity is helpful to folks new to the Registry (and W&B in general), e.g. highlighting using an org entity. But it might annoy SMLEs .

2024-07-15 23:39 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +# Provide the name of your organization
By side scroll, I mean that the path gets cut off so that you can't see exactly what you need to specify:
<img width="666" alt="Screen Shot 2024-07-15 at 4 38 35 PM" src="https://github.com/user-attachments/assets/c702dea7-de2c-4523-889d-b217f0352056">

2024-07-16 00:23 UTC, ngrayluna commented
There's also this option, where I remove the comments and list it below the code:

<img width="581" alt="Screen Shot 2024-07-15 at 5 23 15 PM" src="https://github.com/user-attachments/assets/785c3da4-0976-434d-b903-29444fb1bc71">

2024-07-16 00:24 UTC, ngrayluna commented
Thought, can we make the path for them? and instead, have them specify some of this as parameters in the `link_model` API? That'll make the code look less messy.

2024-07-29 19:28 UTC, ngrayluna commented on docs/guides/registry/intro.md
>  registry_name = "<registry_name>"
Right. The code examples here serve two functions: 
1. The template/generic code that users can copy and paste and fill on their own to successfully link an artifact (i.e. they don't need to figure it out themselves).  [Code snippet 1]
2. The example code they can copy and paste to get an actual result (the expandable "Example" code). This is where we can uses model registry.

2024-07-29 19:29 UTC, ngrayluna commented
@noaleetz bump on this. Preview this doc here: https://docs-beta.wandb.ai/guides/registry

2024-07-31 17:11 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +# Provide the name of your organization
Another reason to call out using team and org entities: https://weightsandbiases.slack.com/archives/C01DNEX5TJ4/p1721843127931409?thread_ts=1721821903.835019&cid=C01DNEX5TJ4

2024-08-21 23:35 UTC, ngrayluna commented on docs/guides/registry/intro.md
>  ## Enable W&B Registry
@noaleetz Do we still need this? Or can we remove it with the latest Server release?

2024-08-21 23:36 UTC, ngrayluna commented
@noaleetz Bump on this. (After you get back)

2024-08-21 23:36 UTC, ngrayluna commented
Latest preview: [Registry _ Weights & Biases Documentation.pdf](https://github.com/user-attachments/files/16700904/Registry._.Weights.Biases.Documentation.pdf)

2024-10-03 19:55 UTC, johndmulhausen commented
Closing as stale per conversation w/Noah

2024-10-03 19:55 UTC, closed without merging