troubleshooting section based on feedback link_version.md
wandb/docs pull request #772
Opened 2024-07-25 01:16 UTC by noaleetz

https://weightsandbiases.slack.com/archives/C05UUJ350CA/p1721846550821839?thread_ts=1721833388.063569&cid=C05UUJ350CA

## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-07-25 01:18 UTC, noaleetz commented
<img width="1192" alt="Screenshot 2024-07-24 at 6 17 31 PM" src="https://github.com/user-attachments/assets/15803a46-8798-4000-929e-1723722a8608">

@ngrayluna I will need your help sticking this image in! I can't figure it out

2024-07-25 01:54 UTC, ibindlish requested changes

2024-07-25 01:54 UTC, ibindlish commented on docs/guides/registry/link_version.md
> +When you have an organization with a team name that exactly matches the organization name, our system appends a unique hash to the organization name to avoid naming collisions. We refer to this as th
```suggestion
When your organization's name exactly matches that of a team in your organization or our database, our system appends a unique hash to the organization name to avoid naming collisions. We refer to this as the `ORG_IDENTIFIER`.
```

2024-07-25 01:54 UTC, ibindlish commented on docs/guides/registry/link_version.md
> +When you have an organization with a team name that exactly matches the organization name, our system appends a unique hash to the organization name to avoid naming collisions. We refer to this as th
I think my suggested change (or something similar) will be better since the collision can happen with a team outside their org too. I would like to avoid a situation where the user comes back to us asking why we use the `ORG_IDENTIFIER` if none of their teams have the same name as their organization

2024-07-25 01:55 UTC, ibindlish commented on docs/guides/registry/link_version.md
> +When you have an organization with a team name that exactly matches the organization name, our system appends a unique hash to the organization name to avoid naming collisions. We refer to this as th
Though I'm wondering if we can just use the word entity instead of team above and just say 

```suggestion
When your organization's name exactly matches that of another entity in our system, we append a unique hash to the organization name to avoid naming collisions. We refer to this as the `ORG_IDENTIFIER`.
```

2024-07-25 16:13 UTC, ngrayluna commented
Thanks! I'll give a review once we pass the tech pass from @ibindlish  :)

2024-07-26 00:24 UTC, ibindlish approved these changes

2024-07-26 00:44 UTC, noaleetz commented
@ngrayluna ready for your review! stamped by @ibindlish

2024-07-29 19:57 UTC, ngrayluna commented on docs/guides/registry/link_version.md
> +    target_path=f"{ORG_ENTITY_NAME}/wandb-registry-{REGISTRY_NAME}/Example ML Task"
We need to update this code example. It doesn't specify the team entity, which can be confusing for folks who don't know that they need to use this in order to link later.

2024-07-29 20:01 UTC, ngrayluna commented on docs/guides/registry/link_version.md
> +For example, if your organization name is `reviewco` and you also have a team named `reviewco`, we will append a hash to the organization name, resulting in an `ORG_ENTITY_NAME` such as `reviewco_XYZ
Is ORG_ENTITY_NAME a variable? Or why are we capitalizing it? Also, how do they find this?

2024-07-29 20:03 UTC, ngrayluna commented on docs/guides/registry/link_version.md
> +    target_path=f"{ORG_ENTITY_NAME}/wandb-registry-{REGISTRY_NAME}/Example ML Task"
Update: I added this in the latest commit: https://github.com/wandb/docodile/pull/772/commits/0d4c0af7810e2b2c61f67ead6818ec239dc0ae0a

2024-07-29 20:04 UTC, ngrayluna commented
@noaleetz A question about the ORG_IDENTIFIER ^^

2024-07-30 01:13 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +For example, if your organization name is `reviewco` and you also have a team named `reviewco`, we will append a hash to the organization name, resulting in an `ORG_ENTITY_NAME` such as `reviewco_XYZ
Great question. It's an imperfect reality that this exists and we need to explore medium term options to not have this be the case but it would have been a 2 week project, anyways to answer your question:
- Yes - ORG_ENTITY_NAME is a variable that the user would have to manually input 
- re how they find it - this is the goal of the PR and the explanations I provide in this section  - to show the user where in the UI they can find it:

currently there are 2 ways to find what value to use for org-entity-id in the UI, and we should provide a gif to the user to locate these ways:
- [New] At the top of each registry, we show a box with a code snippet of how to link to the registry (i.e we show them what to pass into run.link_artifact including the target_path parameter 
- When they create an empty collection in the UI, they can also access that same code snippet with run.link_artifact which lets them copy the exact line of code to link to that collection

<img width="1000" alt="Screenshot 2024-07-29 at 6 09 24 PM" src="https://github.com/user-attachments/assets/50c5714a-276c-4f96-aa31-6209a895e605">
<img width="989" alt="Screenshot 2024-07-29 at 6 11 26 PM" src="https://github.com/user-attachments/assets/d7707725-92ed-42ba-ad7a-19ce64fd11b7">

There is currently no way to get this programmatically from the the org-name, I am trying to allocate resources but until then these are the ways it can be confirmed via the UI

2024-07-30 01:14 UTC, noaleetz commented
> @noaleetz A question about the ORG_IDENTIFIER ^^

Sorry - if you are seeing ORG_IDENTIFIER anywhere, that should just be ORG_ENTITY_NAME (I was testing around different names but must have missed one.

2024-07-31 16:57 UTC, ngrayluna commented on docs/guides/registry/link_version.md
> +TEAM_ENTITY = "<team-entity>"
@noaleetz Left a follow up question before updating: https://github.com/wandb/docodile/commit/0d4c0af7810e2b2c61f67ead6818ec239dc0ae0a#r144786620 

Can you answer in this thread so it doesn't get lost in the GitHub ether?

2024-07-31 16:59 UTC, ngrayluna commented on docs/guides/registry/link_version.md
> +### Logging artifacts from a personal account
https://github.com/wandb/docodile/commit/0d4c0af7810e2b2c61f67ead6818ec239dc0ae0a#r144786620

2024-07-31 16:59 UTC, ngrayluna commented on docs/guides/registry/link_version.md
> +1. Specify the team as the entity when you initialize a run with [`wandb.init()`](https://docs.wandb.ai/ref/python/init). If you do not specify the `entity` when you initialize a run, the run uses yo
https://github.com/wandb/docodile/commit/0d4c0af7810e2b2c61f67ead6818ec239dc0ae0a#r144786680

2024-07-31 17:12 UTC, ngrayluna commented on docs/guides/registry/link_version.md
> +### Logging artifacts from a personal account
@noaleetz Left a question using that link above, but please reply here.

2024-07-31 17:13 UTC, ngrayluna commented on docs/guides/registry/link_version.md
> +1. Specify the team as the entity when you initialize a run with [`wandb.init()`](https://docs.wandb.ai/ref/python/init). If you do not specify the `entity` when you initialize a run, the run uses yo
@noaleetz Left a question using that link above, but please reply here.

2024-07-31 19:37 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +TEAM_ENTITY = "<team-entity>"
> QQ: is a team within an org have the same entity as the team? i.e. If my team is called AwesomeTeam is the entity for that team "AwesomeTeam"?

Yes! Team and entity used to be synonymous (unless you were using your personal entity). Now entity is kind of a bad umbrella term that encompasses team, org, and personal - but I think most users think of entity as being synonymous with team.

2024-07-31 19:39 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +1. Specify the team as the entity when you initialize a run with [`wandb.init()`](https://docs.wandb.ai/ref/python/init). If you do not specify the `entity` when you initialize a run, the run uses yo
this links to a comment I left so I'm a bit confused what the question is here

2024-07-31 19:40 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +### Logging artifacts from a personal account
Also links to a question I left so I am not sure what ? to answer

2024-07-31 19:42 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +ORG_NAME = "<org_name>"
```suggestion
ORG_ENTITY = "<org_entity_name>"
```

2024-07-31 19:42 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +TEAM_ENTITY = "<team_entity>"
```suggestion
TEAM_ENTITY = "<team_entity_name>"
```

2024-07-31 19:43 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +    target_path=f"{ORG_ENTITY_NAME}/wandb-registry-{REGISTRY_NAME}/Example ML Task"
```suggestion
    target_path=f"{ORG_ENTITY}/wandb-registry-{REGISTRY_NAME}/Example ML Task"
```
updated to reflect variable names above - in the troubleshooting part we will discuss more in-depth what exactly to use for this field.

2024-07-31 19:45 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +W&B appends a unique hash to the organization name to avoid naming collisions when you have an organization with a team name that exactly matches the organization name. The combination of the name an
```suggestion
W&B appends a unique hash to the organization name to avoid naming collisions with existing entities. The combination of the name and the unique hash is known as the `ORG_ENTITY`.
```
there are a few different reasons there might be a collision - not just if there is matching team name. Sometimes another org can have the same name as well, so keeping it more general as to why collisions can occur.

2024-07-31 19:46 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +For example, if your organization name is "reviewco" and you also have a team named "reviewco", W&B appends a hash to the organization name that results in an `ORG-IDENTIFIER` named `reviewco_XYZ1234
```suggestion
For example, if your organization name is "reviewco" and you also have a team named "reviewco", W&B appends a hash to the organization name that results in an `ORG_ENTITY` named `reviewco_XYZ123456`. 
```

2024-07-31 19:46 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +1. Check Out an Empty Collection: Create or inspect the empty state for an empty collection inside a registry.
```suggestion
1. Check out an Empty Collection: Create or inspect the empty state for an empty collection inside a registry.
```

2024-07-31 19:46 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +To verify the exact path for linking:
Screenshot/gif needs to be added

2024-07-31 19:47 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +3. If an artifact is logged to the wrong entity, you will need to re-log it to an entity within your organization.
```suggestion
3. If an artifact is logged to your personal entity, you will need to re-log it to an entity within your organization.
```

2024-07-31 19:50 UTC, noaleetz reviewed
I'm not sure how to request changes but added comments/suggestions to the PR based on your commit!

2024-08-01 16:34 UTC, ngrayluna commented on docs/guides/registry/link_version.md
> +TEAM_ENTITY = "<team-entity>"
Let's make sure that we call out which entity, e.g. team entity vs organization entity vs personal entity. Because, depending on the context, one needs to be aware of the differences + our API parameters use the term "entity"

2024-08-01 16:38 UTC, ngrayluna commented on docs/guides/registry/link_version.md
> +    target_path=f"{ORG_ENTITY_NAME}/wandb-registry-{REGISTRY_NAME}/Example ML Task"
Folks generally don't like doing something wrong and then going to a troubleshooting guide (also, they may not think to view the troubleshooting guide)...I think we should be verbose here AND explain what to provide (e.g. in the troubleshooting section).

2024-08-01 22:15 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +    target_path=f"{ORG_ENTITY_NAME}/wandb-registry-{REGISTRY_NAME}/Example ML Task"
```suggestion
    target_path=f"{ORG_ENTITY}/wandb-registry-{REGISTRY_NAME}/Example ML Task"
```

2024-08-02 05:27 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +When linking to a registry with the Python SDK, always use the ORG_ENTITY_NAME format in the target_path. In this case, the target path takes the form of `{ORG_ENTITY_NAME}/wandb-registry-{REGISTRY_N
```suggestion
When linking to a registry with the Python SDK, always use the ORG_ENTITY_NAME format in the target_path. In this case, the target path takes the form of `{ORG_ENTITY}/wandb-registry-{REGISTRY_NAME}/{COLLECTION_NAME}`. 
```

2024-08-05 05:18 UTC, noaleetz commented
Left suggestions but i cannot approve since it is my pr originally, but I think we should be good to go

2024-08-05 17:03 UTC, ngrayluna commented
New updates: 
[Link an artifact version to a registry _ Weights & Biases Documentation.pdf](https://github.com/user-attachments/files/16500626/Link.an.artifact.version.to.a.registry._.Weights.Biases.Documentation.pdf)

2024-08-05 17:04 UTC, ngrayluna commented on docs/guides/registry/link_version.md
> +1. Create or inspect an empty collection inside a registry.
@noaleetz This is temp. I reworded from "empty state" to this ^^. Is this correct? 

Re on rewording change: "Empty state" sounds confusing.

2024-08-05 21:25 UTC, noaleetz commented
everything looks good but still missing images/gifs of the 2 ways to find the name

2024-08-06 19:24 UTC, ngrayluna commented
@noaleetz Done!

PS As I was working on this, added a section on "how to find team entity" in addition to finding the org entity. Both are currently in the troubleshooting section.  I think it makes sense to surface this higher in the page (i.e. remove from the trouble shooting section) since it's important to know....

So as to not delay this PR. Let's ship this one, and then I'll create a new PR to surface this up.

2024-08-06 20:45 UTC, noaleetz reviewed
still can't figure how to approve lol but this is good to merge :)

2024-08-06 21:11 UTC, merged