Registry migration page
wandb/docs pull request #781
Opened 2024-07-31 05:07 UTC by ngrayluna

## Description

 Communicate a centralized document with the details that we are already aligned on to point users to, rather than repeat different variations in customer slack threads. I want this information to be as transparent as possible as early as possible .

Preview the page here:
[Model Registry end of life _ Weights & Biases Documentation.pdf](https://github.com/user-attachments/files/16436519/Model.Registry.end.of.life._.Weights.Biases.Documentation.pdf)

## Ticket

https://wandb.atlassian.net/browse/DOCS-914

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-07-31 05:09 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +:::info Team visibility to organization visibility
Let's make this super visible and make it's own section about team -> org visibility?

2024-07-31 18:06 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +:::info Team visibility to organization visibility
that sounds good!

2024-07-31 18:09 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +| `wandb.init.link_model` | Model Registry specific API | No longer supported |
```suggestion
| `wandb.init.link_model` | Model Registry specific API | currently only compatible with legacy model registry |
```

2024-07-31 18:09 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +# Model Registry end of life
we s
```suggestion
# Legacy Model Registry end of life
```

2024-07-31 18:18 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +W&B will migrate assets from [W&B Model Registry](../model_registry/intro.md) to [W&B Registry](./intro.md) in mid-October 2024.By the end of 2024 you will no longer be able to access W&B Model Regis
```suggestion
W&B will migrate assets from the legacy [W&B Model Registry](../model_registry/intro.md) to [W&B Registry](./intro.md) in mid-October 2024. By the end of 2024 you will no longer be able to access W&B Model Registry. An exact date will be shared at least 3 weeks in advance to all W&B Model Registry users. 
```

2024-07-31 18:30 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +W&B will migrate [registered models](../model_registry/create-registered-model.md) and the [artifact versions](../model_registry/link-model-version.md) that are in your current W&B Model Registry, to
```suggestion
W&B will migrate [registered models](../model_registry/create-registered-model.md) (now called collections) and the [artifact versions](../model_registry/link-model-version.md) that are in your current W&B Model Registry, to W&B Registry as collections. More specifically, your registered models (now called collections) will be stored within within a registry called **Model**.
```

2024-07-31 18:44 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +<!-- *  Service accounts: Team Service accounts will temporarily not be able to interact programmatically with Registry. This feature will be re-introduced before the migration, however.  -->
I see this was commented out but we definitely should keep it in here!

2024-07-31 18:45 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +org_entity = "ReviewCo" # Use organization entity
```suggestion
org_entity = "reviewco" # Use organization entity
```

2024-07-31 18:46 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +### What is migrating?
can we add the diagram into this section? I've shared it with a few customers and they've noted it's a very helpful visual. 
![model-reg-migration-new](https://github.com/user-attachments/assets/fdf70509-08d4-4487-8178-6312446908c4)

2024-07-31 18:48 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +After the migration all artifact versions, collections, descriptions, automations, and tags will be migrated to W&B Registry. However, action history will not be transferred.
```suggestion
After the migration all artifact versions, collections, descriptions, automations, and tags will be migrated to W&B Registry. Action history will be preserved, including a new action that is added to represent that a linked version was migrated, with the ability to navigate to the action history prior to the migration. 
```

2024-07-31 18:51 UTC, noaleetz requested changes
big things to look out for:
- service accounts as a regression
- adding in the diagram - if you want an improved one via Raven we can definitely file a ticket but until then lets add what we do currently have
- I updated the piece on action history per a discussion we had w Ishita on how we're going to support. When she is back from PTO in 6 weeks we can add more details

2024-07-31 22:47 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +<!-- *  Service accounts: Team Service accounts will temporarily not be able to interact programmatically with Registry. This feature will be re-introduced before the migration, however.  -->
Oops. My bad

2024-07-31 22:49 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +<!-- *  Service accounts: Team Service accounts will temporarily not be able to interact programmatically with Registry. This feature will be re-introduced before the migration, however.  -->
Can we add some tentative dates? e.g. Team Service accounts are temporarily unable to interact programmatically with Registry? W&B will enable programmatic access to service account in [INSERT tent. date].

2024-07-31 22:53 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +After the migration all artifact versions, collections, descriptions, automations, and tags will be migrated to W&B Registry. However, action history will not be transferred.
A bit of a run on sentence, broke it down into three: "Action history will be preserved. You will still be able to navigate to the action history prior to the migration. In addition, W&B will add a new action to represent which linked version are migrated."

2024-08-01 19:30 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +run.link_artifact(artifact_or_name = artifact_version)
@ngrayluna we are missing the target path here - link artifact takes in the artifact you want to to link and the path you want to link it to

2024-08-01 19:30 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +### Registered model attributes
```suggestion
### Collection attributes
```

2024-08-01 19:33 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +All organizations should plan to use the new Models registry inside the new W&B Registry. The same capabilities will be supported, including automations, lineage, and aliasing, with new features intr
```suggestion
All organizations should plan to use the new model registry inside the new W&B Registry. The same capabilities will be supported, including automations, lineage, and aliasing, with new features introduced. Please review [the list](###deprecated-features) above for features that are not supported currently. 
```

2024-08-01 19:46 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +[WANDB_BASE_URL]/team_name/model-registry/artifacts/
```suggestion
[WANDB_BASE_URL]/team_entity_name/model-registry/artifacts/
```

2024-08-01 19:47 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +team_name/model-registry/collection:alias
```suggestion
team_entity_name/model-registry/collection:alias
```

2024-08-01 20:33 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +*  Service accounts: Team Service accounts will temporarily not be able to interact programmatically with Registry. This feature will be re-introduced before the migration, however.
```suggestion
*  Service accounts: Existing team service accounts will cannot interact programmatically with Registry as the Registry is at the org level. As a result, Organization Service accounts will be made available (this feature is currently in progress) prior to the migration taking place. Please reach out to support@wandb.com to discuss temporary solutions that we recommend. 
```

2024-08-01 20:56 UTC, noaleetz commented on static/images/registry/eol_migration.png
the registered model ones should say model registry, not registered model

2024-08-01 20:57 UTC, noaleetz requested changes
diagram should say model registry for the blue boxes

2024-08-01 21:03 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +<!-- *  Service accounts: Team Service accounts will temporarily not be able to interact programmatically with Registry. This feature will be re-introduced before the migration, however.  -->
I don't have tentative dates and don't want to commit on any since this is a dependency on the platform team. We're exploring a tentative workaround - see my updated below in the later commit

2024-08-01 21:04 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +run.link_artifact(artifact_or_name = artifact_version)
https://docs.wandb.ai/ref/python/run#link_artifact

2024-08-01 21:51 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +*  Service accounts: Team Service accounts will temporarily not be able to interact programmatically with Registry. This feature will be re-introduced before the migration, however.
"Before the migration, as the Registry is at the org level." what does this mean?

2024-08-01 21:55 UTC, noaleetz commented on docs/guides/registry/model_registry_eol.md
> +*  Service accounts: Team Service accounts will temporarily not be able to interact programmatically with Registry. This feature will be re-introduced before the migration, however.
oh rip sorry I didn't clean that up. Updated

2024-08-02 00:09 UTC, ngrayluna commented
@noaleetz Preview here: 
[Legacy Model Registry end of life _ Weights & Biases Documentation.pdf](https://github.com/user-attachments/files/16463607/Legacy.Model.Registry.end.of.life._.Weights.Biases.Documentation.pdf)

2024-08-02 00:09 UTC, ngrayluna commented
Let me know if it looks good, if yay, I'll merge and deploy 🚢

2024-08-02 04:30 UTC, merged