[WIP] Creates Automation Landing Page
wandb/docs pull request #783
Opened 2024-08-01 14:07 UTC by katjacksonWB

## Description

Adds a new automation landing page to the docs. Also moves current automation pages under the new landing page.

## Ticket

[DOCS-919](https://wandb.atlassian.net/browse/DOCS-919)

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

[DOCS-919]: https://wandb.atlassian.net/browse/DOCS-919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-01 16:47 UTC, ngrayluna requested changes
Doc CI is failing

2024-08-05 17:26 UTC, katjacksonWB commented
> Doc CI is failing

I think it’s just the word “automations” tripping things up?

2024-08-05 17:29 UTC, ngrayluna commented
> > Doc CI is failing
> 
> I think it’s just the word “automations” tripping things up?

Not quite. See the errors here: https://github.com/wandb/docodile/actions/runs/10251554186/job/28359855351

[If you build the docs locally, it'll show the same thing]

2024-08-05 21:04 UTC, ngrayluna commented on docs/guides/automations/model-registry-automations.md
> +3. [This](https://www.youtube.com/watch?v=s5CMj_w3DaQ) demo details how to setup an automation to deploy a model to a SageMaker Endpoint
Full product name is "Amazon SageMaker"

2024-08-05 21:08 UTC, ngrayluna commented
@noaleetz QQ: Is the plan to still combine the two (nearly duplicate) automation pages into one page? https://wandb.atlassian.net/jira/software/projects/DOCS/boards/28/backlog?assignee=712020%3A8919aba2-c842-4c60-9cec-544f9ade575a&selectedIssue=DOCS-880

If yay, we don't need to rename these pages. Instead, we create one new page, and combine content. Then update respecitve doc links.

2024-08-05 21:10 UTC, noaleetz commented
> @noaleetz QQ: Is the plan to still combine the two (nearly duplicate) automation pages into one page? https://wandb.atlassian.net/jira/software/projects/DOCS/boards/28/backlog?assignee=712020%3A8919aba2-c842-4c60-9cec-544f9ade575a&selectedIssue=DOCS-880
> 
> If yay, we don't need to rename these pages. Instead, we create one new page, and combine content. Then update respecitve doc links.

Which 2 docs pages? Here is the new outline for automations [docs](https://www.notion.so/wandbai/Automations-Outline-c813c5fcbff641e8a34a33ba52351a8d?pvs=4).

2024-08-05 21:12 UTC, ngrayluna commented
> > @noaleetz QQ: Is the plan to still combine the two (nearly duplicate) automation pages into one page? https://wandb.atlassian.net/jira/software/projects/DOCS/boards/28/backlog?assignee=712020%3A8919aba2-c842-4c60-9cec-544f9ade575a&selectedIssue=DOCS-880
> > If yay, we don't need to rename these pages. Instead, we create one new page, and combine content. Then update respecitve doc links.
> 
> Which 2 docs pages? Here is the new outline for automations [docs](https://www.notion.so/wandbai/Automations-Outline-c813c5fcbff641e8a34a33ba52351a8d?pvs=4).

legacy model reg https://docs.wandb.ai/guides/model_registry/model-registry-automations 
artifact automations: https://docs.wandb.ai/guides/artifacts/project-scoped-automations

2024-08-05 21:14 UTC, noaleetz commented
> > > @noaleetz QQ: Is the plan to still combine the two (nearly duplicate) automation pages into one page? https://wandb.atlassian.net/jira/software/projects/DOCS/boards/28/backlog?assignee=712020%3A8919aba2-c842-4c60-9cec-544f9ade575a&selectedIssue=DOCS-880
> > > If yay, we don't need to rename these pages. Instead, we create one new page, and combine content. Then update respecitve doc links.
> > 
> > 
> > Which 2 docs pages? Here is the new outline for automations [docs](https://www.notion.so/wandbai/Automations-Outline-c813c5fcbff641e8a34a33ba52351a8d?pvs=4).
> 
> legacy model reg https://docs.wandb.ai/guides/model_registry/model-registry-automations artifact automations: https://docs.wandb.ai/guides/artifacts/project-scoped-automations

I think we can still have a guide or section in registry docs re how to create an automation for a registry and we can link to the relevant automations section. But I'll defer to you and @katjacksonWB and the structure.

2024-08-05 21:15 UTC, ngrayluna commented
Ah, let me clarify. Within the Automations docs, we don't need to rename these existing content:

guides/model_registry/model-registry-automations -> 'guides/automations/model-registry-automations',
'guides/artifacts/project-scoped-automations' -> 'guides/automations/project-scoped-automations'

Since they'll be replaced w/ new content that describe how to accomplish a task specific to Artifacts or Registry.

Once that content goes out (i.e. what is outlined in the Notion doc), we can remove the old pages^^ and add the appropriate redirects to the new content/pages.

2024-08-05 23:44 UTC, noaleetz commented on docs/guides/automations/intro.md
> +## How it works
![Automation_event triggers action  (1)](https://github.com/user-attachments/assets/3858b5e2-99a6-4621-83d7-f0c256015e9d)
can we add this diagram into this landing page

2024-08-06 00:08 UTC, noaleetz commented on docs/guides/automations/intro.md
> +- **Automated model testing and deployment**: When a new model gets linked to a registry, a webhook POST request triggers an action like a GitHub Action workflow or a SageMaker endpoint to consume th
hmmm no not necessarily - for this example the new model getting linked to a registry is what triggers to post request. An event is something that takes place in W&B. The only 2 event options are adding a specific alias and linking a new version. The wording is more like "when event X takes place, action Y is triggered". An event is the one that does the triggering.

2024-08-06 00:12 UTC, noaleetz commented on docs/guides/automations/model-registry-automations.md
> +See [Link a model version](../model_registry/link-model-version.md) for information on how to link model versions and [Create a custom alias](../artifacts/create-a-custom-alias.md) for information an
model registry will be deprecated, we shouldn't be linking to docs in there. This should point to the other section we're working on in this PR on event types - https://github.com/wandb/docodile/pull/785.

2024-08-06 00:14 UTC, noaleetz commented on docs/guides/automations/project-scoped-automations.md
I don't quite understand why we're editing this - please see the [outline](https://www.notion.so/wandbai/Automations-Outline-c813c5fcbff641e8a34a33ba52351a8d?pvs=4#3e0eeda66e2f45d0bc459e82373baff6) we discussed - we want to have a single guide on scope which addresses the stuff I wrote in the outline. The 2 different guides on model reg and artifact automations will be deprecated.

2024-08-06 00:15 UTC, noaleetz commented on docs/guides/hosting/iam/org_team_struct.md
> +Every project is comprised of [Workspaces](../../app/pages/workspaces.md) and [Reports](../../reports/intro.md), and is linked to relevant [Artifacts](../../artifacts/intro.md), [Sweeps](../../sweeps
same with here - the project-scoped-automations guide will no longer exist as part of the outline [here](https://www.notion.so/wandbai/Automations-Outline-c813c5fcbff641e8a34a33ba52351a8d?pvs=4#3e0eeda66e2f45d0bc459e82373baff6)

2024-08-06 00:15 UTC, noaleetz requested changes
v0 changes

2024-08-06 14:38 UTC, katjacksonWB commented on docs/guides/automations/project-scoped-automations.md
I have to edit it to get things to build. In terms of why the pages are there, I decided to move the old automations pages under the new landing page so we could push the landing page even if the other pages in the outline aren't ready yet.

2024-08-06 15:46 UTC, katjacksonWB commented on docs/guides/automations/intro.md
> +## How it works
Is there a figma/original image of this, so I can get the highest quality possible?

2024-08-06 16:01 UTC, katjacksonWB commented on docs/guides/hosting/iam/org_team_struct.md
> +Every project is comprised of [Workspaces](../../app/pages/workspaces.md) and [Reports](../../reports/intro.md), and is linked to relevant [Artifacts](../../artifacts/intro.md), [Sweeps](../../sweeps
The links will be changed when the new content is out. I prioritized getting the landing page out first, but I can pivot if that makes more sense.

2024-08-06 17:25 UTC, ngrayluna commented on docs/guides/automations/project-scoped-automations.md
I think what we're getting at is that we don't need to rename these pages since we'll be removing them. So renaming them will add an extra redirect...

So the action item here is to not move these files from their original location to the automations folder and undoing the filepath changes. 

i.e. focus only on the landing page bit (automations/intro.md). Don't change the other files in this directory.

2024-08-07 04:36 UTC, noaleetz commented on docs/guides/automations/intro.md
> +## How it works
Raven should have the figma link! Feel free to shoot her a dm or start a thread in #visual-design channel

2024-08-07 04:36 UTC, noaleetz commented on docs/guides/hosting/iam/org_team_struct.md
> +Every project is comprised of [Workspaces](../../app/pages/workspaces.md) and [Reports](../../reports/intro.md), and is linked to relevant [Artifacts](../../artifacts/intro.md), [Sweeps](../../sweeps
No no agreed with this - we should get landing page out first!

2024-08-08 17:47 UTC, ngrayluna commented on docs/guides/model_registry/intro.md
> +* [Automate](model-registry-automations.md) downstream processes and model CI/CD.
Missing "./" in this link and next

2024-08-08 17:47 UTC, ngrayluna commented on docs/guides/models.md
> +- Configure custom automations that trigger key workflows for [model CI/CD](../guides/model_registry/model-registry-automations.md).
Remove the "../guides/"

2024-08-08 17:48 UTC, ngrayluna requested changes
Some links are incorrectly formatted.

2024-08-12 19:05 UTC, noaleetz commented on docs/guides/artifacts/project-scoped-automations.md
> +This is in contrast to automations created in the W&B Model Registry. Automations created in the model registry are in scope of the Model Registry; they are triggered when events are performed on mod
this needs to be applicable to Registry - not the legacy model registry

2024-08-12 21:36 UTC, noaleetz commented on docs/guides/automations/intro.md
> +Code is not the only asset deployed in your machine learning project. W&B offers tools to automate model deployment, downstream actions for versioning artifacts, and more.
I'm not following what the first sentence on code is referring to here and how it connects to the story on automated model deployment

2024-08-13 00:06 UTC, noaleetz commented on docs/guides/automations/intro.md
please make sure to adjust mentions of model registry to reflect new generic Registry

2024-08-13 00:06 UTC, noaleetz commented on docs/guides/automations/manage-automations.md
> +# Delete an automation
please make sure to add a gif to any list of numbered steps

2024-08-13 00:08 UTC, noaleetz commented on docs/guides/model_registry/intro.md
> +   * [How to connect the Model Registry to CI/CD processes](model-registry-automations.md).
model registry is being deprecated - we should make sure to link any automation resources in the Registry docs, not in the old model registry docs.

2024-08-13 00:08 UTC, noaleetz requested changes
v1 edits

2024-08-13 16:12 UTC, katjacksonWB commented on docs/guides/automations/intro.md
> +Code is not the only asset deployed in your machine learning project. W&B offers tools to automate model deployment, downstream actions for versioning artifacts, and more.
I just removed it, it was part of a larger paragraph originally.

2024-09-25 11:08 UTC, merged