Creates automation events page
wandb/docs pull request #785
Opened 2024-08-01 16:12 UTC by katjacksonWB

## Description

Creates new automation events page.

## Ticket

[DOCS-920](https://wandb.atlassian.net/browse/DOCS-920)

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

[DOCS-920]: https://wandb.atlassian.net/browse/DOCS-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-01 16:46 UTC, ngrayluna requested changes
Doc CI is failing

2024-08-02 23:15 UTC, noaleetz commented on docs/guides/automations/events.md
> +## Model Registry
Hey @katjacksonWB - plz take a look at my note [here](https://weightsandbiases.slack.com/archives/C05754EPT26/p1722377417289199?thread_ts=1722270837.161739&cid=C05754EPT26). These docs should be in the language of generic Registry. Automations can be added to any Registry. Can you review the Registry docs to make sure you're aligned on the changes and update the model registry specific language in here?

2024-08-02 23:16 UTC, noaleetz commented on docs/guides/automations/events.md
> +See [Link a model version](./link-model-version.md) for information on how to link model versions and [Create a custom alias](../artifacts/create-a-custom-alias.md) for information an artifact aliase
let's break this down into more concrete sections for each event type. For each we should give a brief code snippet on how you trigger this event, and then link them to the docs you have here. But we should be more specific on what exactly needs to be done to trigger the event.

2024-08-02 23:18 UTC, noaleetz commented on docs/guides/automations/events.md
> +## Artifacts
We should be clear here on the differences between this section and the Registry section. I would make the titles specific:
- Event Types for Automations applied to a Registry
- Event Types for Automations applied to Artifacts in a project

Let's make sure to link to the section in the outline on automations scope

2024-08-02 23:21 UTC, noaleetz commented on docs/guides/automations/events.md
Joe created these diagrams to help users visualizations the 2 events - can we add these to the docs? 
<img width="503" alt="Screenshot 2024-08-02 at 4 20 11 PM" src="https://github.com/user-attachments/assets/34daa109-ea10-4b3a-9236-9822e3555b6f">
<img width="539" alt="Screenshot 2024-08-02 at 4 20 22 PM" src="https://github.com/user-attachments/assets/2f85df27-5049-407b-b52e-e466ea1a8df4">

2024-08-02 23:22 UTC, noaleetz requested changes
v0 changes requested

2024-08-05 22:06 UTC, noaleetz commented
<img width="336" alt="Screenshot 2024-08-05 at 3 05 55 PM" src="https://github.com/user-attachments/assets/8cd810e9-a84d-4a45-96a6-249305c16b4a">
Hey @katjacksonWB - please make sure to request changes when you're ready for another review otherwise I won't know when to take a look

2024-09-25 11:06 UTC, merged