[WIP] Adds Automation Webhooks Page
wandb/docs pull request #793
Opened 2024-08-06 18:13 UTC by katjacksonWB

## Description

Seperates webhook information from the automations section and puts it in its own page.

## Ticket

[DOCS-923](https://wandb.atlassian.net/browse/DOCS-923)

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

[DOCS-923]: https://wandb.atlassian.net/browse/DOCS-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-07 04:38 UTC, noaleetz commented on docs/guides/automations/webhooks.md
> +Follow the instructions below to create a webhook:
need a gif of this workflow

2024-08-07 04:39 UTC, noaleetz commented on docs/guides/automations/webhooks.md
> +1. Navigate to the W&B App UI.
need a gif for this workflow

2024-08-07 04:50 UTC, noaleetz commented on docs/guides/automations/webhooks.md
> +* **Access tokens**: Authorize senders to help secure webhook requests
We should explain to the user how we will use those fields inside the post request:

- W&B will construct the POST request based on your inputs for secret and access token. $ACCESS_TOKEN will be passed in as an input to to the bearer token inside the authorization header: `-H "Authorization: Bearer $ACCESS_TOKEN”`

2024-08-07 04:52 UTC, noaleetz commented on docs/guides/automations/webhooks.md
> +* **Secret**: Ensure the authenticity and integrity of data transmitted from payloads
similarly let's explain the same for secret somewhere:

$SECRET will be used to generate a secure HMAC signature of the payload. This signature is passed in the headers of the POST request to ensure the integrity and authenticity of the data being transmitted. It is included as -H "X-Wandb-Signature: $SIGNATURE" where $SIGNATURE is the HMAC of the payload encrypted using $SECRET."

2024-08-07 04:57 UTC, noaleetz commented on docs/guides/automations/webhooks.md
> +
can we add a section here that shares with the user the structure of the post request we will share on their behalf? This is necessary to help them understand where the secret, access token, url, and payload they define will be inserted into the post request. 

Pasting in my proposal:

## Structure of the POST Request 

When you set up a webhook in Weights & Biases, you'll define several key components that are used to construct a secure POST request. Understanding how these components are used in the request can help you configure your webhook correctly and ensure secure data transmission. Below is an outline of how each component you define is utilized in the POST request:

### 1. Access Token (`$ACCESS_TOKEN`)
   - **Purpose:** Authenticates the request to the target API or service.
   - **Location in Request:** The access token is included in the HTTP headers as a bearer token.
   - **Example:** 
     ```
     -H "Authorization: Bearer $ACCESS_TOKEN"
     ```

### 2. Secret (`$SECRET`)
   - **Purpose:** Used to generate a cryptographic HMAC signature that verifies the integrity and authenticity of the payload.
   - **Location in Request:** The secret itself is not transmitted. Instead, it is used to create an HMAC signature of the payload, which is included in the HTTP headers.
   - **Example:** 
     ```
     -H "X-Wandb-Signature: $SIGNATURE"
     ```

### 3. Payload (`$PAYLOAD`)
   - **Purpose:** Contains the data you want to send to the endpoint. This can be customized according to the requirements of the receiving API.
   - **Location in Request:** The payload is included in the body of the POST request.
   - **Example:** 
     ```
     -d "$PAYLOAD" API_ENDPOINT
     ```

### 4. API Endpoint (`$API_ENDPOINT`)
   - **Purpose:** Specifies the URL to which the POST request is sent.
   - **Location in Request:** The API endpoint is the destination URL for the curl command.
   - **Example:** 
     ```
     -d "$PAYLOAD" API_ENDPOINT
     ```

### Example Bash Script 

The following script mimics the POST request that W&B sends on your behalf when the webhook is triggered. Make sure to replace `your_api_key`, `your_api_secret`, the JSON payload, and `API_ENDPOINT` with your actual data:

```bash
#!/bin/bash

# Your access token and secret
ACCESS_TOKEN="your_api_key" 
SECRET="your_api_secret"

# The data you want to send (for example, in JSON format)
PAYLOAD='{"key1": "value1", "key2": "value2"}'

# Generate the HMAC signature
# For security, W&B includes the X-Wandb-Signature in the header computed 
# from the payload and the shared secret key associated with the webhook 
# using the HMAC with SHA-256 algorithm.
SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" -binary | base64)

# Make the cURL request
curl -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H "X-Wandb-Signature: $SIGNATURE" \
  -d "$PAYLOAD" API_ENDPOINT

2024-08-07 05:04 UTC, noaleetz commented on docs/guides/automations/webhooks.md
> +
Note - this serves a different purpose then pasting the script for testing purposes. This section is specifically to show a user where the various fields they define for the webhook will be passed into the request. We have gotten feedback from users that it hasn't been trivial to connect between the bash script for testing to the realization that this same curl request in the bash script can be used to understand the post request structure, so we should just have this separate section which specifically calls out how certain user defined fields will be used in post request

2024-08-07 05:05 UTC, noaleetz commented on docs/guides/automations/webhooks.md
> +Once you have a webhook configured and (optionally) a secret, navigate to the Model Registry App at [https://wandb.ai/registry/model](https://wandb.ai/registry/model).
needs to be updated to reflect Registry instead of model registry

2024-08-07 05:05 UTC, noaleetz commented on docs/guides/automations/webhooks.md
> +### Add a webhook
gif needs to be added

2024-08-07 05:06 UTC, noaleetz commented on docs/guides/automations/webhooks.md
> +6. (Optional) Provide a payload in the JSON expression editor. See the [Example payload](#example-payloads) section for common use case examples.
this can link back to the section above with the post request structure, saying something like: to see where the payload is used inside the post request, see XYZ.

2024-08-07 05:07 UTC, noaleetz requested changes
v0 edits requested

2024-08-07 16:32 UTC, ngrayluna commented on docs/guides/automations/webhooks-payload.md
> +  Send a repository dispatch from W&B to trigger a GitHub action. For example, suppose you have workflow that accepts a repository dispatch as a trigger for the `on` key:
Remove extra space/indent from all paragraphs. E.g. Here we have " Send a..." which should be "Send a..."

2024-08-07 16:33 UTC, ngrayluna requested changes
Missing markdown from sidebar

2024-08-08 14:45 UTC, katjacksonWB commented on docs/guides/automations/webhooks.md
> +
@noaleetz Do we need to define terms like HMAC, or do we except the reader to be aware of that?

2024-08-09 00:41 UTC, noaleetz commented on docs/guides/automations/intro.md
> +# Automation
```suggestion
# Automations
```
should be automations not automation!

2024-08-09 00:43 UTC, noaleetz commented on docs/guides/automations/webhooks.md
> +
No! Good question, I think we can keep this as common knowledge - we're just trying to give some contact on how we keep these token secures but I would describe this as common knowledge for folks who are using a signature in their payload

2024-08-09 20:33 UTC, ngrayluna commented on docs/guides/automations/webhooks-payload.md
> +Verify that your access tokens have required set of permissions to trigger your GHA workflow. For more information, [see these GitHub Docs](https://docs.github.com/en/rest/repos/repos?#create-a-repos
Did a quick Googling, I don't think "GHA" is used colloquially?

2024-08-15 21:38 UTC, noaleetz commented on docs/guides/automations/webhooks-payload.md
> +The following tabs demonstrate example payloads based on common use cases. Within the examples they reference the following keys to refer to condition objects in the payload parameters:
Can we provide a specific example of what all of these fields would look when printed out? Discussed [here](https://weightsandbiases.slack.com/archives/C05UUJ350CA/p1723659297574069?thread_ts=1723048641.458249&cid=C05UUJ350CA). We have gotten feedback that these are super vague and just repeat what is in the name. We should include a better explanation + an example for a dummy setup how those strings would be printed.

2024-08-15 21:39 UTC, noaleetz commented on docs/guides/automations/webhooks-payload.md
> +<Tabs
I do not see the friendli AI payload in here

2024-08-15 21:39 UTC, noaleetz commented on docs/guides/automations/webhooks-payload.md
> +<Tabs
https://weightsandbiases.slack.com/archives/C07B4F51VQ8/p1723663379878689?thread_ts=1721932077.995989&cid=C07B4F51VQ8

2024-09-25 11:06 UTC, merged