[WIP] Adds launch automations page.
wandb/docs pull request #794
Opened 2024-08-06 18:21 UTC by katjacksonWB

## Description

Adds launch automations page.

## Ticket

[DOCS-924](https://wandb.atlassian.net/browse/DOCS-924)

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

[DOCS-924]: https://wandb.atlassian.net/browse/DOCS-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-07 04:29 UTC, noaleetz commented on docs/guides/automations/launch-jobs.md
> +1. From the **Event type** dropdown, select an event type. See the [Event type](#event-types) section for information on supported events.
Can we add a gif to accompany these numbered instructions?

2024-08-07 04:33 UTC, noaleetz commented on docs/guides/automations/launch-jobs.md
> +## Create a launch automation
Before diving into how to create a launch automation we should give more context on (1) what a launch job is and why you want to trigger it via an automation, (2) examples of when you might trigger it - check out this example project with different types of launch automations set up with common workflows, (3) when does it make sense to use launch job as the action - see [this](https://weightsandbiases.slack.com/archives/C01UUUHP153/p1695226956804279?thread_ts=1695166048.027149&cid=C01UUUHP153) thread

2024-08-07 04:33 UTC, noaleetz commented on docs/guides/automations/launch-jobs.md
> +Automatically start a W&B Job.
```suggestion
Automatically trigger a W&B Job. 
```

2024-08-07 04:34 UTC, noaleetz requested changes
see specific comments - needs more context on what launch automations are and why someone would use them

2024-08-09 17:24 UTC, katjacksonWB commented on docs/guides/automations/launch-jobs.md
> +## Create a launch automation
@noaleetz So for that thread, I have a couple of questions:

- what does infra stand for in this case?
- I notice that the conclusion to the statements in the thread seems to be "webhooks are preferred". Should we be surfacing that?
- I did my best to transliterate the comments, is this in the right direction?

> ## Use cases
> - Increased observability: Launch jobs allow you to view and analyze training runs through the W&B platform.
> - Alternate credential storage: Store your credentials on an internal machine instead of a secret store.
> - Infrastructure analysis: Gain increased visibility into your infrastructure usage.

2024-09-25 11:04 UTC, merged