[WIP] Adds Automations Action Types Page.
wandb/docs pull request #795
Opened 2024-08-07 16:18 UTC by katjacksonWB

## Description

Adds Automations Action Types Page, separated from the old automations pages.

## Ticket

[DOCS-921](https://wandb.atlassian.net/browse/DOCS-921)

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

[DOCS-921]: https://wandb.atlassian.net/browse/DOCS-921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-07 16:25 UTC, ngrayluna commented on docs/guides/automations/automations-actions.md
> +
Page is missing a title and intro blurb (describing what the page is for).

You could remove the "## What is an action" and use that as the intro blurb. (With some more context).

2024-08-07 16:25 UTC, ngrayluna commented on docs/guides/automations/automations-actions.md
> +
If approved, ensure to add this to the sidebar, too.  Else, this page won't show up.

2024-08-07 16:29 UTC, ngrayluna commented on docs/guides/automations/automations-actions.md
> + [Launch jobs](../launch/create-launch-job.md) are reusable, configurable run templates that allow you to quickly launch new [runs](../runs/intro.md) locally on your desktop or external compute resou
Extra space before "Launch jobs".

2024-08-07 16:29 UTC, ngrayluna commented on docs/guides/automations/automations-actions.md
> + [Launch jobs](../launch/create-launch-job.md) are reusable, configurable run templates that allow you to quickly launch new [runs](../runs/intro.md) locally on your desktop or external compute resou
It'd be great to define what "run templates" mean

2024-08-07 16:29 UTC, ngrayluna requested changes
Left some comments.

2024-08-12 18:47 UTC, noaleetz commented on docs/guides/automations/automations-actions.md
> +An action is an internal or external responsive mutation that occurs as a result of some trigger. For automations, this trigger is an event configured based on your project's needs.
hmmm im a bit confused what you mean by internal and external. And what responsive mutation means

2024-08-13 00:23 UTC, noaleetz commented on docs/guides/automations/automations-actions.md
> +An action is an internal or external responsive mutation that occurs as a result of some trigger. For automations, this trigger is an event configured based on your project's needs.
An action is more like the resulting behavior when you perform the event

2024-08-13 00:26 UTC, noaleetz commented on docs/guides/automations/automations-actions.md
> +Webhooks communicate with an external web server from W&B with HTTP requests. This is useful for linking your models or artifacts to external tools like GitHub Actions.
I wouldn't say this is used to link a model to an external tool - what do you mean by link here? Webhooks are meant to communicate with external tools like your existing CI pipelines, orchestration tools such as dagster or airflow, etc. 

Webhooks are used to send data to a URL endpoint in a flexible way in response to an event happening in W&B

2024-08-13 00:27 UTC, noaleetz commented on docs/guides/automations/automations-actions.md
can the automations diagram be added here?

2024-08-13 00:29 UTC, noaleetz commented on docs/guides/automations/automations-actions.md
this would be the best section to add an explanation of what use cases are better for webhooks, and which ones are better for launch jobs. You can use the thread I linked in the previous PR

2024-08-13 00:29 UTC, noaleetz requested changes
v0 changes

2024-09-25 11:04 UTC, merged