Update Model Registry -> Registry Migration Docs
wandb/docs pull request #810
Opened 2024-08-22 20:34 UTC by trane293

## Description

This PR updates the documentation to reflect the upcoming migration from the legacy W&B Model Registry to the new W&B Registry. It includes details on new features, migration plans, and FAQs to ensure a smooth transition for users. The document has also been updated to clarify that the migration will occur once full feature parity is achieved.

More information about the context is available here: https://www.notion.so/wandbai/Registry-Aligning-on-Next-Steps-5eba17ed224a4bcda02ac2697c933897 

## Ticket

JIRA Ticket: https://wandb.atlassian.net/browse/WB-20516 

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [x] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [x] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-08-26 20:31 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> -![](/images/registry/eol_migration.png)
Why are we removing the diagram? Is it because we no longer want to highlight organizations?

2024-08-26 20:32 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +## **What is Changing?**
Remove bold from titles (i.e. ** after the pound sign)

2024-08-26 20:34 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +## **Looking Ahead**
Remove this section. We don't date the docs. It's not part of the style guide.  

Why?Dating the docs can get stale if not kept up to date (which happens since we have hundreds of docs) + we write about what exists in the product today.

2024-08-26 20:35 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +For those interested in trying the W&B Registry early, or for new users preferring to start directly with Registry, support is available. Contact support@wandb.com or your Sales MLE to enable this fu
Not sure how this snuck in, but remove "please".

2024-08-26 20:36 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +For more details and to learn about the full range of features in the W&B Registry, visit the [Registry Guide](https://docs.wandb.ai/guides/registry).
For Doc URLs we use relative paths. See the API ref guide links in the diff

2024-08-26 20:37 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +The migration process will be conducted during non-business hours to minimize any disruption. The legacy Model Registry will transition to a read-only state once the migration begins and will remain
What does "non-business hours" mean? (Since we have users all over the world, someone is probably going to be impacted..

2024-08-26 20:38 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +## **What is Changing?**
All titles of sections should use sentence casing.

2024-08-26 20:39 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +In the near future, W&B will be transitioning assets from the legacy [W&B Model Registry](../model_registry/intro.md) to the new [W&B Registry](./intro.md). This migration will be fully managed and t
Remove "In the near future". Re: It dates the docs.

2024-08-26 20:40 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +The transition will take place once full feature parity with all Model Registry functionalities is achieved, ensuring that users have access to all the tools they need. Ample notice will be provided
"Feature parity" is confusing term for customers that are not in the product world. Let's elaborate what we mean.

2024-08-26 20:41 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +## **What is Changing?**
I think having the table in the original version is helpful for a quick "at a glance" view. Let's add it back in and refine it w/ the content you added.

2024-08-26 20:42 UTC, ngrayluna requested changes
Left some comments.

2024-08-26 21:24 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> +The transition will take place once full feature parity with all Model Registry functionalities is achieved, ensuring that users have access to all the tools they need. Ample notice will be provided
Replaced with:

```
The transition will take place once the new W&B Registry includes all the functionalities currently available in the Model Registry, ensuring that users have access to all the tools and features they rely on.
```

2024-08-26 21:26 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> +## **What is Changing?**
Removed boldface from all titles.

2024-08-26 21:26 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> +## **What is Changing?**
Changed all titles to sentence casing.

2024-08-26 21:27 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> +## **Looking Ahead**
This section is important and requested by Product/Customers to get a clear understanding of what's coming, and what's on the roadmap. 

How would you recommended we should go about communicating this information?

2024-08-26 21:29 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> +The migration process will be conducted during non-business hours to minimize any disruption. The legacy Model Registry will transition to a read-only state once the migration begins and will remain
Switched to:

> The migration process will be initiated by W&B and will be conducted in a way to minimze any distruption to the services. The legacy Model Registry will transition to a read-only state once the migration begins and will remain accessible for reference.

2024-08-26 21:29 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> +For those interested in trying the W&B Registry early, or for new users preferring to start directly with Registry, support is available. Contact support@wandb.com or your Sales MLE to enable this fu
Done

2024-08-26 21:30 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> +For more details and to learn about the full range of features in the W&B Registry, visit the [Registry Guide](https://docs.wandb.ai/guides/registry).
Done

2024-08-26 21:32 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> +## **What is Changing?**
The table had incorrect and/or misleading information. We want to keep things intentionally vague for now to keep room for changes in the future.

2024-08-26 21:32 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> +In the near future, W&B will be transitioning assets from the legacy [W&B Model Registry](../model_registry/intro.md) to the new [W&B Registry](./intro.md). This migration will be fully managed and t
Done

2024-08-27 22:09 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> -![](/images/registry/eol_migration.png)
The diagram visualizes the old plan, which is no longer the correct one. We might be migrating in a different way that makes this diagram obsolete.

2024-08-28 21:52 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> +W&B will transition assets from the legacy [W&B Model Registry](../model_registry/intro.md) to the new [W&B Registry](./intro.md) by the end of 2024. This migration will be fully managed and triggere
We have no confirmation whether this will hold up or not. The end of 2024 date is not guaranteed.

2024-08-28 21:56 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> +| Artifact visibility| Team level | Organization level |
This row is something that creates confusion, and we saw that with a client. The artifact visibility will not change to organization level, because users should be able to change visibility settings themselves. 

The way its written right now (and in the past), it suggested that artifacts will be opened up to the whole organization, which led to questions about data privacy and burning through permissions boundaries. 

If we are to keep the table, which is fine by the way, I'll suggest removing the first row.

2024-08-28 21:59 UTC, trane293 commented on docs/guides/registry/model_registry_eol.md
> +After the migration, your model and dataset registry will have organization level visibility. You can restrict who has access to a registry by [assigning roles](./configure_registry.md). This helps e
> your model and dataset registry will have organization level visibility

There is no "dataset registry". Model registry only has "model" registry, with collections within it.

2024-08-28 22:07 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +After the migration, your model and dataset registry will have organization level visibility. You can restrict who has access to a registry by [assigning roles](./configure_registry.md). This helps e
Ah. Oops. Good catch

2024-08-28 22:13 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +| Artifact visibility| Team level | Organization level |
Ah. Yeah, I can see how that might've been confusing. Updated it to: 

|               | Legacy W&B Model Registry | W&B Registry |
| -----         | ----- | ----- |
| Artifact visibility| Only members of team can view or access artifacts | Members in your organization, with correct permissions, can view or access artifacts linked to a registry  |

2024-08-28 22:19 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +W&B will transition assets from the legacy [W&B Model Registry](../model_registry/intro.md) to the new [W&B Registry](./intro.md) by the end of 2024. This migration will be fully managed and triggere
Removed

2024-08-28 22:19 UTC, ngrayluna commented on docs/guides/registry/model_registry_eol.md
> +After the migration, your model and dataset registry will have organization level visibility. You can restrict who has access to a registry by [assigning roles](./configure_registry.md). This helps e
Removed

2024-08-28 22:36 UTC, merged