Registry tags docs
wandb/docs pull request #824
Opened 2024-09-10 06:06 UTC by ngrayluna

## Description

Adds docs on how to add tags to collections and artifact versions within W&B Registry

## Ticket

https://wandb.atlassian.net/browse/DOCS-963

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-09-11 03:33 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
> +## Add a tag to a collection
missing a section for interacting with collection level tags via SDK. Similar to artifact version, we should also show how to programmatically add tags to a collection. As of 0.17.1 you are able to edit registry collection tags programmatically using the api after the creation of the collection, it would look something like this:

import wandb

collection = wandb.Api().artifact_collection("model", "artsiomtest/wandb-registry-model/test-model") 

collection.tags = ["your-tag"]
collection.save()

2024-09-11 03:38 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
> +artifact.tags = ["tag2"] # # Provide one or more tags in a list
can we show an example of 1 of the more common workflows users have:
- adding a tag to an existing list of tags (setting artifact.tags = [...] overrides all existing tags instead of appending new one)

2024-09-11 03:39 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
> +## Remove a tag from an artifact version
missing how to do this programatically

2024-09-11 03:59 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
Can we add a brief section on when to use tags vs. aliases?

- Use aliases when you need to reference a specific artifact version uniquely. For example, use an alias like 'production' or 'latest' to ensure that artifact_name:alias always points to a single, specific version.
- Use tags when you want more flexibility for grouping or searching. Tags are ideal when multiple versions or collections can share the same label, and you don’t need the guarantee that only one version is associated with a specific identifier.

2024-09-11 04:01 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
can we add a section on searching by tags in the UI and show a gif of how search results would look like (searching by tag in the searchbar of a given registry)

2024-09-11 04:02 UTC, noaleetz requested changes
v0 feedback

2024-09-11 17:24 UTC, ngrayluna commented on docs/guides/registry/organize-with-tags.md
> +artifact.tags = ["tag2"] # # Provide one or more tags in a list
@tonyyli-wandb Is there a check that ensures we don't override existing lists? If not, what's the preferred way to update a list? with `+=` or calling a standard `.append`?

2024-09-11 17:26 UTC, ngrayluna commented on docs/guides/registry/organize-with-tags.md
> +artifact.tags = ["tag2"] # # Provide one or more tags in a list
E.g.

```python 
my_tags = artifact.tags 

my_tags.append('new tag')

artifact.tags = my_tags
```

2024-09-11 17:26 UTC, ngrayluna commented on docs/guides/registry/organize-with-tags.md
> +## Remove a tag from an artifact version
@tonyyli-wandb Related to the above. Is the idea here to return that tag attribute, store it as a list, then reassign? e.g.

```python
my_tags = artifact.tags 
my_tags.pop()
artifact.tags = my_tags
```

2024-09-11 20:03 UTC, tonyyli-wandb commented on docs/guides/registry/organize-with-tags.md
> +## Remove a tag from an artifact version
> @tonyyli-wandb Related to the above. Is the idea here to return that tag attribute, store it as a list, then reassign? e.g.
> 
> 
> 
> ```python
> 
> my_tags = artifact.tags 
> 
> my_tags.pop()
> 
> artifact.tags = my_tags
> 
> ```

That's the recommendation, yes -- reassignment is preferred.

Users _can_ do it by either reassignment or in-place updates.  Reassignment is preferable, but to be clear: this is a general Python "best practice", and has less to do with tags themselves.

That said, there's an extra reason reassignment is preferred for tags: they're validated right away, rather than later (when calling `Artifact.save()`).  So if they have an invalid format, the user will know on reassignment.  (The reason for this is fundamentally a quirk of Python lists -- can elaborate if interested offline, but prob less relevant here)

Reassignment examples:
```python3
artifact.tags = [*artifact.tags, "new-tag", "other-tag"]
artifact.tags = artifact.tags + ["new-tag", "other-tag"]

artifact.tags = set(artifact.tags) - set(tags_to_delete)
artifact.tags = []  # deletes all tags
```

In-place examples:
```python3
artifact.tags += ["new-tag", "other-tag"]
artifact.tags.append("new-tag")

artifact.tags.extend(["new-tag", "other-tag"])
artifact.tags[:] = ["new-tag", "other-tag"]
artifact.tags.remove("existing-tag")
artifact.tags.pop()
artifact.tags.clear()
```

2024-09-11 21:26 UTC, ngrayluna commented on docs/guides/registry/organize-with-tags.md
> +## Remove a tag from an artifact version
Right on. Thanks!

2024-09-11 23:59 UTC, tonyyli-wandb commented on docs/guides/registry/organize-with-tags.md
> +## Remove a tag from an artifact version
@ngrayluna PS will try to put together a notebook (I need to do this anyway) + share offline with you this week

2024-09-12 05:07 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
> +artifact = wandb.Api().artifact(name = artifact_name, type = ARTIFACT_TYPE)
```suggestion
artifact = wandb.Api().artifact(name=artifact_name, type=ARTIFACT_TYPE)
```

2024-09-12 05:08 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
> +7. Press **Enter** on your keyboard
do you need to hit enter or can you just click anywhere on the page?

2024-09-12 05:09 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
> +artifact_name = f"{ORG_NAME}/wandb-registry-{REGISTRY_NAME}/{COLLECTION_NAME}:v{VERSION}"
friendly heads up we will have to change these paths to not have org name when the change goes through to no longer require org name.

2024-09-12 05:12 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
> +run = wandb.init(entity = "<entity>", project="<project>", job_type="<job-type>")
nit but I don't think there should be spaces before and after equal sign
```suggestion
run = wandb.init(entity="<entity>", project="<project>")
```

can we remove job type as one of the optional params? It isn't related to the workflow we're trying to teach the users about, and the user might be confused as to what they should put there

2024-09-12 05:13 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
> +artifact = wandb.Api().artifact(name = artifact_name, type = artifact_type)
sim
```suggestion
artifact = wandb.Api().artifact(name=artifact_name, type=artifact_type)
```

2024-09-12 05:13 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
> +run = wandb.init(entity = "<entity>", project="<project>", job_type="<job-type>")
```suggestion
run = wandb.init(entity="<entity>", project="<project>", job_type="<job-type>")
```

2024-09-12 05:13 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
> +artifact = run.use_artifact(artifact_or_name = artifact_name)
```suggestion
artifact = run.use_artifact(artifact_or_name=artifact_name)
```

2024-09-12 05:14 UTC, noaleetz approved these changes
approved but a few nits here in there

2024-09-12 17:30 UTC, ngrayluna commented on docs/guides/registry/organize-with-tags.md
> +artifact = run.use_artifact(artifact_or_name = artifact_name)
Ah. So oddly enough, it's considered "good practice" for readability to keep a space between the argument and field. I personally don't like it, too. 🤷

2024-09-12 17:31 UTC, noaleetz commented on docs/guides/registry/organize-with-tags.md
> +artifact = run.use_artifact(artifact_or_name = artifact_name)
ah gotcha - maybe it is a new thing I haven't seen before but feel free to ignore my similar comments

2024-09-12 17:31 UTC, ngrayluna commented on docs/guides/registry/organize-with-tags.md
> +7. Press **Enter** on your keyboard
Both work

2024-09-12 17:40 UTC, merged