Wandbb operator airgapped installation
wandb/docs pull request #843
Opened 2024-10-01 15:05 UTC by flamarion

## Description

What does the pull request do? If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [x] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [x] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-10-02 15:20 UTC, abhinavg6 requested changes
Great doc, thanks for doing this. Requested some formatting and minor changes.

2024-10-02 15:20 UTC, abhinavg6 commented on sidebars.js
> +                  label: 'W&B Operator',
```suggestion
                  label: 'Kubernetes Operator',
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +# W&B Kubernetes Operator (Airgapped)
```suggestion
# Kubernetes operator for air-gapped instances
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +This guide provides a comprehensive and user-friendly step-by-step process for deploying the Weights & Biases (W&B) Platform in airgapped environments.
```suggestion
This guide provides step-by-step instructions to deploy the W&B Platform in air-gapped customer-managed environments. 
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +Since airgapped environments are isolated from the internet, special configurations are required to ensure the proper deployment of W&B components using
```suggestion
As the air-gapped environments are assumed to be disconnected from the public network, special configuration is required to ensure the successful deployment and functioning of the W&B platform.
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +internal repositories for both Helm charts and container images.
```suggestion
Use an internal repository or registry to host the helm charts and container images.
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +The document assume all commands will be executed in a shell console with proper access to the Kubernetes.
```suggestion
All commands must be executed in a shell console with proper access to the Kubernetes cluster.
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +Although using command line for the matter of documentation, the process also applies to any continuous deliver tooling used to deploy Kubernetes application.
```suggestion
You could utilize similar commands in any continuous delivery tooling that you use to deploy Kubernetes applications.
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +- Kubernetes version >= 1.29
```suggestion
- Kubernetes version >= 1.28
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +- Kubernetes Metrics installed (required for future support of Horizontal Pod Autoscaler support)
I would say if we don't need this today, maybe let's remove this, and then we could add once we've HPA support for the app pod.

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +## Step 2: Prepare Internal Container Registry
```suggestion
## Step 2: Prepare internal container registry
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +
Should we show the versions in here? I mean could it lead to a confusion that these versions are a must? Or maybe worth adding a note that this is just an example and users must get the images with latest versions?

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +## Step 2: Prepare Internal Helm Chart repository
```suggestion
## Step 2: Prepare internal helm chart repository
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +- [Operator W&B](https://github.com/wandb/helm-charts/tree/main/charts/operator-wandb)
```suggestion
- [W&B Platform](https://github.com/wandb/helm-charts/tree/main/charts/operator-wandb)
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +The `operator` chart is used to deploy the W&B Operator (Controller Manager) while the `operator-wandb` chart will be used with the values configured in the CRD to deploy W&B Platform.
```suggestion
The `operator` chart is used to deploy the W&B Operator i.e. the Controller Manager, while the `platform` chart is used to deploy the W&B Platform using the values configured in the custom resource definition (CRD).
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +## Step 3: Set Up Helm Repository
```suggestion
## Step 3: Set up helm chart repository
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +## Step 3: Set Up Helm Repository
I would say, just include this in the Step 2, else "Prepare" and "Setup" can be confusing as two distinct steps

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +## Step 4: Install W&B Operator (Controller Manager)
```suggestion
## Step 4: Install the kubernetes operator aka controller manager
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +The W&B Operator (Controller Manager) is responsible for managing the W&B platform components. To install it in an airgapped environment,
```suggestion
The W&B kubernetes operator i.e. the controller manager is responsible for managing the W&B platform components. To install it in an air-gapped environment, 
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +you need to configure it to use your internal container registry.
```suggestion
you must configure it to use your internal container registry.
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +To do so, uou must override the default image settings to use your internal container registry and set the key `airgapped: true` to indicate this is the deployment type you expect. Update the `values
```suggestion
To do so, you must override the default image settings to use your internal container registry and set the key `airgapped: true` to indicate the expected deployment type. Update the `values.yaml` file as shown below:
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +All supported values can be found in the official W&B Operator [repository](https://github.com/wandb/helm-charts/blob/main/charts/operator/values.yaml).
```suggestion
You can find all supported values in the [official kubernetes operator repository](https://github.com/wandb/helm-charts/blob/main/charts/operator/values.yaml).
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +## Step 5: Configure Custom Resource Definitions (CRDs)
```suggestion
## Step 5: Configure custom resource definitions aka CRD
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +Once the W&B Operator is installed, configure the Custom Resource Definitions (CRDs) to point to your internal Helm repository and container registry.
```suggestion
After installing the W&B kubernetes operator, you must configure the Custom Resource Definitions (CRDs) to point to your internal Helm repository and container registry. 
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +This configuration ensures that all required components are deployed from your internal resources. Below is an example of how to configure the CRD.
```suggestion
This configuration ensures that your internal registry & repository are utilized to deploy the required components of the W&B platform. Below is an example of how to configure the CRD.
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +To deploy the W&B Platform, the W&B Operator will use the `operator-wandb` chart from your internal repository and use the values from your CRD to configure the helm chart.
```suggestion
To deploy the W&B platform, the kubernetes Operator will use the `operator-wandb` chart from your internal repository and use the values from your CRD to configure the helm chart.
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +All supported values can be found in the Operator W&B [repository](https://github.com/wandb/helm-charts/blob/main/charts/operator/values.yaml).
```suggestion
You can find all supported values in the [official kubernetes operator repository](https://github.com/wandb/helm-charts/blob/main/charts/operator/values.yaml).
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +## Step 6: Deploy the W&B Platform
```suggestion
## Step 6: Deploy the W&B platform
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +Finally, after setting up the CRD and W&B Operator, deploy the W&B platform using the following command:
```suggestion
Finally, after setting up the kubernetes operator and the CRD, deploy the W&B platform using the following command:
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +Below are some frequently asked questions (FAQs) and troubleshooting tips to help you during the deployment process:
```suggestion
Refer to the below frequently asked questions (FAQs) and troubleshooting tips during the deployment process:
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +**I have another ingress class, can I use it?**
```suggestion
**We have another ingress class. Can we use that?**  
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +**My certificate bundle has more than one certificate.**
```suggestion
**Our certificate bundle has more than one certificate. Would that work?**  
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +Split the certificates into multiple entries in the `customCACerts` section of `values.yaml`.
```suggestion
You must split the certificates into multiple entries in the `customCACerts` section of `values.yaml`.
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +**I don't want the W&B Operator to apply unattended updates.**
```suggestion
**We would like to prevent the kubernetes operator from applying unattended updates. Is that possible?**  
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +You can disable auto-updates by ensuring you have the latest versions and adjusting the W&B Console settings.
```suggestion
You can disable auto-updates from the W&B console. Reach out to your W&B team for any questions on the supported versions. Also, note that W&B supports platform versions released in last 6 months. W&B recommends performing periodic upgrades. 
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +**What if my environment has no connection to external repositories?**
```suggestion
**Would the deployment work if our environment has no connection to public repositories?**  
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator-airgapped.md
> +As long as the `airgapped: true` configuration is enabled, the W&B Operator will not attempt to reach public repositories and will use your internal resources.
```suggestion
As long as you have enabled the `airgapped: true` configuration, the kubernetes operator will not attempt to reach public repositories and will attempt to use your internal resources.
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator.md
> +For a detailed description of the specification hierarchy, see [Configuration Specification Hierarchy](#configuration-specification-hierarchy) and for configuration options, see [Configuration Refere
```suggestion
Refer to the [configuration specification hierarchy](#configuration-specification-hierarchy) and [configuration reference](#configuration-reference-for-wb-operator) for configuration options.
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/operator.md
>  ## Configuration Specification Hierarchy
```suggestion
## Configuration specification hierarchy
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/self-managed/azure-tf.md
> +You need to add the option `create_redis = true` to the same `main.tf` file we worked on in [Deployment Recommended](#deployment---recommended-20-mins) to enable the cache.
```suggestion
You must add the option `create_redis = true` to the same `main.tf` file that you used in [recommended deployment](#deployment---recommended-20-mins) to enable the cache.
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/self-managed/azure-tf.md
> +The Azure resource that provides the message broker is the `Azure Event Grid`, and to enable it, you will need to add the option `use_internal_queue = false` to the same `main.tf` that we worked on t
```suggestion
The Azure resource that provides the message broker is the `Azure Event Grid`, and to enable it, you must add the option `use_internal_queue = false` to the same `main.tf` that you used in the [recommended deployment](#deployment---recommended-20-mins)
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/self-managed/azure-tf.md
> +The [Terraform Module](https://github.com/wandb/terraform-azure-wandb) provides several options that can be combined along with the standard options and the minimal configuration found in [Deployment
```suggestion
The [Terraform Module](https://github.com/wandb/terraform-azure-wandb) provides several options that can be combined along with the standard options and the minimal configuration found in [recommended deployment](#deployment---recommended-20-mins)
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/self-managed/bare-metal.md
> +W&B recommends a [MySQL 8](#mysql-database) database as a metadata store. The shape of the ML practitioners parameters and metadata will greatly affect the performance of the database. The database i
```suggestion
W&B recommends a [MySQL 8](#mysql-database) database as a metadata store. The shape of the model parameters and related metadata will greatly affect the performance of the database. The database size grows as the ML practitioners track more training runs, and incurs read heavy load when queries are executed in run tables, users workspaces, and reports.
```

2024-10-02 15:20 UTC, abhinavg6 commented on docs/guides/hosting/self-managed/bare-metal.md
> +Additionally, we recommend the following [parameter overrides](#mysql-database) to tune the DB for MySQL 8.
```suggestion
Additionally, W&B recommends the following [parameter overrides](#mysql-database) to tune the DB for MySQL 8.
```

2024-10-02 18:37 UTC, flamarion commented on docs/guides/hosting/operator-airgapped.md
> +- Kubernetes Metrics installed (required for future support of Horizontal Pod Autoscaler support)
Sounds good. I'm going to remove

2024-10-02 18:40 UTC, flamarion commented on docs/guides/hosting/operator-airgapped.md
> +
Yeah, we can refer to WSM to list the necessary images.
For now, I will add a note this is only an example.

2024-10-08 16:58 UTC, abhinavg6 approved these changes
LGTM

2024-10-08 17:52 UTC, ngrayluna approved these changes

2024-10-08 18:04 UTC, merged