Added details on how to configure Entra OIDC
wandb/docs pull request #870
Opened 2024-10-16 13:29 UTC by mkaesz-wandb

## Description
Added details on how to configure Entra OIDC

## Ticket
No

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-10-16 19:03 UTC, johndmulhausen commented on docs/guides/hosting/iam/sso.md
> +3. On the left side, select "App registrations".
```suggestion
3. On the left side, select "App registrations."
```

2024-10-16 19:03 UTC, johndmulhausen commented on docs/guides/hosting/iam/sso.md
> +     {label: 'Entra', value: 'entra'},
```suggestion
    {label: 'Okta', value: 'okta'},
    {label: 'Entra', value: 'entra'},
```

2024-10-16 19:04 UTC, johndmulhausen commented on docs/guides/hosting/iam/sso.md
> +4. On the top, click "New registration".
```suggestion
4. On the top, click "New registration."
```

2024-10-16 19:04 UTC, johndmulhausen commented on docs/guides/hosting/iam/sso.md
> +    On the screen named "Register an application", fill out the values as follows:
```suggestion
    On the screen named "Register an application," fill out the values as follows:
```

2024-10-16 19:04 UTC, johndmulhausen commented on docs/guides/hosting/iam/sso.md
> +    - Specify a name, e.g. "Weights and Biases application".
```suggestion
    - Specify a name, for example "Weights and Biases application".
```

2024-10-16 19:05 UTC, johndmulhausen commented on docs/guides/hosting/iam/sso.md
> +    - Leave the default account type: "Accounts in this organizational directory only (Default Directory only - Single tenant)". Modify if you need to.
```suggestion
    - Leave the default account type: "Accounts in this organizational directory only (Default Directory only - Single tenant)." Modify if you need to.
```

2024-10-16 19:07 UTC, johndmulhausen requested changes

2024-10-16 19:07 UTC, johndmulhausen commented on docs/guides/hosting/iam/sso.md
> +    - Leave the default account type: "Accounts in this organizational directory only (Default Directory only - Single tenant)". Modify if you need to.
@mkaesz-wandb "Leave the default" and "modify if you need to" are contradictory. Which is it?

2024-10-16 19:07 UTC, johndmulhausen commented on docs/guides/hosting/iam/sso.md
> +    - Click "Register".
```suggestion
    - Click "Register."
```

2024-10-16 19:07 UTC, johndmulhausen commented on docs/guides/hosting/iam/sso.md
> +- Make a note of the "Application (client) ID" and "Directory (tenant) ID".
```suggestion
- Make a note of the "Application (client) ID" and "Directory (tenant) ID."
```

2024-10-16 19:07 UTC, johndmulhausen commented on docs/guides/hosting/iam/sso.md
> +- Under "Front-channel logout URL" specify: `https://YOUR_W_AND_B_URL/logout`
```suggestion
- Under **Front-channel logout URL**, specify: `https://YOUR_W_AND_B_URL/logout`
```

2024-10-16 19:07 UTC, johndmulhausen commented on docs/guides/hosting/iam/sso.md
> +5. On the left side, click "Authentication"
```suggestion
5. On the left side, click **Authentication**.
```

2024-10-16 19:08 UTC, johndmulhausen commented
Please finish responding to the Vale comments as I suggested. Also, note that when quoting the text of UI elements you should use `**bold**` text and not quotation marks.

2024-10-21 18:29 UTC, ngrayluna approved these changes

2024-10-21 18:50 UTC, merged