Registry new api landing page updates
wandb/docs pull request #929
Opened 2024-11-19 22:48 UTC by ngrayluna

## Description

Updates Registry landing page to account for API changes that shipped w/ W&B Python SDK 18.6 .

Will add link to notebook once that is approved and merged: https://github.com/wandb/examples/pull/582

Doc preview: https://registry-new-api-landing-pag.docodile.pages.dev/guides/registry

## Ticket

https://wandb.atlassian.net/browse/DOCS-1059

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-11-19 22:55 UTC, noaleetz commented on docs/guides/registry/intro.md
> +The legacy Model Registry is scheduled for deprecation with the exact date not yet decided. See [Migrating from legacy Model Registry](./model_registry_eol.md) for more information about the migratio
I don't think we need to add this detail about deprecation - these landing pages should be mostly focused on updating the APIs. We don't have a schedule for deprecation at this point so would prefer not to mix in updates on that into this PR

2024-11-19 22:56 UTC, noaleetz commented on docs/guides/registry/intro.md
> +- Track an [artifact’s lineage](../model_registry/model-lineage.md) and audit the history of changes.
these links should stay out until we add respective pages for them in registry

Specifically the lineage and automations page. I think we can aim to get those changes in within ~1 week of when this landing page update goes out. Similar to earlier comment we should keep all changes related to this PR just on the api changes

2024-11-19 22:57 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +The legacy Model Registry is scheduled for deprecation with the exact date not yet decided. See [Migrating from legacy Model Registry](./model_registry_eol.md) for more information about the migratio
@noaleetz Those notes are already there, I just moved it up from the bottom of the page/condensed it. (We currently have a lot of call to actions on the landing page).

2024-11-19 22:57 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +- Track an [artifact’s lineage](../model_registry/model-lineage.md) and audit the history of changes.
These pages do exist... (minus the lineage one).

2024-11-19 22:58 UTC, noaleetz commented on docs/guides/registry/intro.md
> +1. Log an artifact version to W&B with `wandb.run.init()`.
hmm what is this api?

2024-11-19 23:01 UTC, noaleetz commented on docs/guides/registry/intro.md
> +Once you have an artifact version in the registry, you can use the Registry App at https://wandb.ai/home to view, download, and manage your artifact versions, create downstream automations, and more.
we should let the user now how they can navigate to this URL in the UI

f"{wandb.api.app_url}/{artifact.entity}/{artifact.project}/artifacts/{artifact.type}/{artifact.name}"

for saas the wandb.api.app_url is just "wandb.ai" but if you are on server you have a unique URL.

2024-11-19 23:02 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +1. Log an artifact version to W&B with `wandb.run.init()`.
That's technically the proper way to write out run.init

2024-11-19 23:02 UTC, noaleetz commented on docs/guides/registry/intro.md
> +The legacy Model Registry is scheduled for deprecation with the exact date not yet decided. See [Migrating from legacy Model Registry](./model_registry_eol.md) for more information about the migratio
ohh ok gotcha. For this specific PR lets just keep it focused on the API updates for the shorthand paths.

2024-11-19 23:02 UTC, noaleetz commented on docs/guides/registry/intro.md
> +- Track an [artifact’s lineage](../model_registry/model-lineage.md) and audit the history of changes.
yes - the lineage and automations once we should keep out until we update those

2024-11-19 23:03 UTC, noaleetz commented on docs/guides/registry/intro.md
> +1. Log an artifact version to W&B with `wandb.run.init()`.
this line is says that this is the code to log an artifact to W&B but the code snippet is to create a run so this is a bit confusing. 

Also I think the best practice way we should be recommending to users: run = wandb.init()

2024-11-19 23:05 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +1. Log an artifact version to W&B with `wandb.run.init()`.
Right. So in the code that's how we'll show it. If you look at other packages like TF, PyTorch, etc. they refer to the long way first and then shorthadn it in the code, etc. 

Note: That this is something I'm going to update for all docs as well.

2024-11-19 23:06 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +- Track an [artifact’s lineage](../model_registry/model-lineage.md) and audit the history of changes.
I'd like to update this landing page as well, I don't think it's serving our current users today TBH. We don't explain how it works, for e.g. 

Dfeinitely can move the Model Registry below again, but the other changes I think should stay.

2024-11-21 00:00 UTC, noaleetz commented on docs/guides/registry/intro.md
> +1. Log an artifact version to W&B with `wandb.run.init()`.
wait - what? where is the run piece coming from? i.e the code wandb.run.init() will not run... there is no run argument

2024-11-21 00:04 UTC, noaleetz commented on docs/guides/registry/intro.md
> +1. Log an artifact version to W&B with `wandb.run.init()`.
The best practice the SDK team wants to enforce run = wandb.init()

2024-11-21 00:05 UTC, noaleetz commented on docs/guides/registry/intro.md
> +    target_path=f"{REGISTRY_NAME}/{COLLECTION_NAME}"
this should be wandb-registry-{registry-name}

2024-11-21 01:29 UTC, noaleetz commented on docs/guides/registry/intro.md
> +run.link_artifact(
Re Estella's note [here](https://weightsandbiases.slack.com/archives/C01DX8LRZEJ/p1731952311506989) needs clarification that: "inform(s) users that this can only be done from version 0.18.6 upwards and there is a caveat where it doesn’t work (user using a personal org and belongs to multiple orgs have to specify what org they are using in the path, a rare case but can happen)"

This applies to any of the apis we are changing to use the shorthand path.

2024-11-21 18:50 UTC, noaleetz commented on docs/guides/registry/intro.md
can we also add this diagram to the landing page to clarify relationship b/w registry, collection, versions?
<img width="832" alt="Registry_Hierarchy_Diagram" src="https://github.com/user-attachments/assets/bb1bf472-a4a3-4f9e-8ef3-a6d697a10689">

2024-11-21 18:52 UTC, noaleetz commented on docs/guides/registry/intro.md
> +1. Log an artifact version to W&B with [`wandb.Run.init()`](../../ref/python/run.md).
I'm still confused by this line because it doesn't actually log an artifact, it creates a run

2024-11-21 18:53 UTC, noaleetz requested changes
left comments inline

2024-11-22 18:30 UTC, ngrayluna commented on docs/guides/registry/intro.md
Sure! Though Anmol asked if we could remove it...also, we'd want to remove "Organization" from the top?

2024-11-22 19:14 UTC, ngrayluna commented
@noaleetz Addressed feedback. Unsure about the image though (see comment)

2024-11-25 04:27 UTC, noaleetz commented
> @noaleetz Addressed feedback. Unsure about the image though (see comment)

do you mind re-requesting a review since I'm not sure how to see the comments you left?

2024-11-25 04:29 UTC, noaleetz commented on docs/guides/registry/intro.md
Hey @trane293 - any more details here on why we can't include this diagram?

2024-11-25 04:29 UTC, noaleetz commented on docs/guides/registry/intro.md
@ngrayluna will defer to you re keeping or leaving Organization, the initial goal was to show that the registry belongs to the Organization, but I am fine w removing it if you think it is better that way!

2024-11-25 16:46 UTC, ngrayluna commented on docs/guides/registry/intro.md
@noaleetz I thought we wanted to remove mention of "organizations" from users?

2024-11-25 18:38 UTC, trane293 commented on docs/guides/registry/intro.md
Hmmm I'm trying to remember or find any old conversations regarding this, but I can't really see a problem with this diagram. It's accurate to what we currently have, no concerns here. We can add it.

2024-11-25 19:08 UTC, ngrayluna commented on docs/guides/registry/intro.md
@noaleetz Can you point me to the figma w/ that diagram? I can't find it...

2024-11-25 19:17 UTC, ngrayluna commented on docs/guides/registry/intro.md
Nvm. I found it. :)

2024-12-03 03:20 UTC, noaleetz commented on docs/guides/registry/intro.md
> +Navigate to the Registry App to view artifact versions that you and other members of your organization publish. To do so, first navigate to W&B. Select **Registry** in the left sidebar below **Applic
Can we include a gif as these are step by step instructions that are mostly visual

2024-12-03 03:21 UTC, noaleetz approved these changes
@estellazx do you want to make a final pass as well (mostly to review the APIs)?

2024-12-03 19:55 UTC, estellazx commented on docs/guides/registry/intro.md
> +    )
nit, follow python black format
```suggestion
)
```

2024-12-03 19:56 UTC, estellazx commented on docs/guides/registry/intro.md
> +    )
nit, follow python black format
```suggestion
)
```

2024-12-03 19:56 UTC, estellazx approved these changes

2024-12-04 16:44 UTC, ngrayluna commented on docs/guides/registry/intro.md
> +Navigate to the Registry App to view artifact versions that you and other members of your organization publish. To do so, first navigate to W&B. Select **Registry** in the left sidebar below **Applic
Can't create .gif right now; W&B is giving me weird permission errors...Will debug and follow up with said .gif.

2024-12-04 16:54 UTC, merged