Updated download and link registry docs
wandb/docs pull request #931
Opened 2024-11-21 20:24 UTC by ngrayluna

## Description

Updates download and link artifact to registry docs.

[Link an artifact doc preview](https://registry-link-download-docs.docodile.pages.dev/guides/registry/link_version)

[Download an artifact from a registry doc preview](https://registry-link-download-docs.docodile.pages.dev/guides/registry/download_use_artifact)

## Ticket

Does this PR fix an existing issue? If yes, provide a link to the ticket here:

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [ ] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [ ] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [ ] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-11-25 04:36 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +If you are not sure about the registry name, collection name, or alias of the artifact version you want to access, you can find this information in the W&B App UI.
can we also note what the registry name is for the (core) Model and Dataset registries - i.e what should the user pass in as registry name for each of the core registries?

2024-11-25 04:38 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +registered_artifact = run.use_artifact(artifact_or_name = artifact_name)
```suggestion
fetched_artifact = run.use_artifact(artifact_or_name = artifact_name)  
```

technically the underlying object for the registered artifact is still just the source artifact (currently) so it isn't exactly accurate to call it registered artifact since it might give the false impression that there is a different artifact object for the source and registered artifact

2024-11-25 04:41 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +# Override personal entity with a team entity
```suggestion
# Ensure you are using your team entity to instantiate the api
```
users might not know what a personal entity is. The goal of passing in this override is so that users who do have personal entity set as their default don't run into trouble, but there might be other users (especially since on saas, new users do not have personal entities) who don't know what a personal entity is.

2024-11-25 04:44 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +# Use org display name or org entity in the path
we should be instructing users to use the shorthand path, not org name (and definitely not org entity name - the goal of the api changes we made was to avoid users needing to know what this is). 

The only time they should pass in org name is if they are in the 2.7% case where they are in multiple orgs, and I don't think this doc should cover this since it is such a low case and the goal of the error message is to redirect users to doing this.

2024-11-25 04:46 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +:::note Users with a personal entity that belong to multiple organizations
I think we should put this at the end of the section, after we've highlighted the more common scenario, it's pretty distracting to start sharing edge cases before we finish explaining the happy path for how you do something

2024-11-25 04:51 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +Users with a personal entity that belong to multiple organizations must also specify either the name of their organization or use a team entity when accessing artifacts linked to a registry.
we can just say users that belong to multiple orgs - it doesn't matter if you have a personal entity or not because either way the main issue is that with multiple orgs we won't know which org you want us to fetch from. 

We should make the options more clear:
user can either:
- passing in an override with team-entity when creating API object
api = wandb.Api(overrides={"entity": "my-team-entity"})
- making sure their path specifies the org name
api.artifacts(type_name="model", name="my-org-name/wandb-registry-model/Artifact Demo Models")

https://weightsandbiases.slack.com/archives/CT4901KC5/p1731438804105999?thread_ts=1731104446.327269&cid=CT4901KC5

2024-11-25 04:52 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +Users with a personal entity that belong to multiple organizations must also specify either the name of their organization or use a team entity when accessing artifacts linked to a registry.
but similar to note above these details should go after we share the basic workflow

2024-11-25 04:52 UTC, noaleetz requested changes
comments inline!

2024-11-25 19:50 UTC, ngrayluna commented on docs/guides/registry/download_use_artifact.md
> +:::note Users with a personal entity that belong to multiple organizations
It is! It's at the bottom of the programmatic section. Since it doesn't apply to the programmatic way...(I assume)

Actually, to confirm, the code snippet that W&B generates in the Usage tab (i.e. the interactive way to download a registered artifact)  accounts for the use case of personal entity w/ multiple orgs?

2024-11-25 19:53 UTC, ngrayluna commented on docs/guides/registry/download_use_artifact.md
> +# Use org display name or org entity in the path
This is the code snippet that still relates to users to multiple orgs w/ personal entities.  i.e. it's still w/in the note 
<img width="586" alt="Screen Shot 2024-11-25 at 11 53 01 AM" src="https://github.com/user-attachments/assets/c2b3949b-5874-423b-9497-42febab34405">

2024-11-25 19:53 UTC, ngrayluna commented on docs/guides/registry/download_use_artifact.md
> +# Use org display name or org entity in the path
PS I took these code snippets from Estella's doc: https://www.notion.so/wandbai/Guide-to-fetching-linking-Registry-artifacts-in-the-SDK-13ee2f5c7ef38064a45cc83e1792bfad?pvs=4#13ee2f5c7ef380b49c96ccaf1a153023

2024-11-25 19:55 UTC, ngrayluna commented on docs/guides/registry/download_use_artifact.md
> +Users with a personal entity that belong to multiple organizations must also specify either the name of their organization or use a team entity when accessing artifacts linked to a registry.
Just to clarify, that note about personal entity comes from Estella's doc: https://www.notion.so/wandbai/Guide-to-fetching-linking-Registry-artifacts-in-the-SDK-13ee2f5c7ef38064a45cc83e1792bfad?pvs=4#13ee2f5c7ef3800593b1f9c2f34bb5f0

2024-11-25 19:56 UTC, ngrayluna commented
@noaleetz Left some comments on your comments.

2024-12-03 03:25 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +artifact_name = f"{ORG_ENTITY}/wandb-registry-{REGISTRY}/{COLLECTION}:{VERSION}"
```suggestion
artifact_name = f"{ORG_NAME}/wandb-registry-{REGISTRY}/{COLLECTION}:{VERSION}"
```

2024-12-03 03:27 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +# Use org display name or org entity in the path
Oh sorry I didn't understand that. Thanks for the screenshot.

2024-12-03 03:28 UTC, noaleetz commented on docs/guides/registry/link_version.md
> +If you want to link an artifact version to the Model registry or the Dateset registry, set the artifact type to `"model"` or `"dataset"`, respectively.
typo here

2024-12-03 03:32 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +Note that by using the `use_artifact` method, you are marking the artifact as an input to your run for lineage tracking. This allows you to track the lineage of the artifact in the W&B App UI. You ca
can we make a note to update this to link to the new lineage tracking section that will be added once available?

2024-12-03 03:34 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +:::note Users with a personal entity that belong to multiple organizations
Yes! Re Usage Tab, we will make sure it reflects the correct code snippet for the user. 

Sounds good re location. I see now it is under the programmatic section

2024-12-03 03:35 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +# Use org display name or org entity in the path
```suggestion
# Use org display name in the path
```

2024-12-03 03:37 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +artifact_name = f"{ORG_ENTITY}/wandb-registry-{REGISTRY}/{COLLECTION}:{VERSION}"
@estellazx - for non-saas users should we just instruct users that their ORG_NAME is "server"?

2024-12-03 03:39 UTC, noaleetz commented on docs/guides/registry/link_version.md
>  run.link_artifact(artifact = artifact, target_path = target_path)
optional but if we want we can include a gif to show users how to find instructions for linking 
<img width="1187" alt="Screenshot 2024-12-02 at 7 39 28 PM" src="https://github.com/user-attachments/assets/3f3e6456-dc90-478b-b0f5-38ae1a51d32c">

2024-12-03 03:45 UTC, noaleetz approved these changes
@estellazx want to make a pass at the APIs in here as well?

2024-12-03 20:00 UTC, estellazx commented on docs/guides/registry/download_use_artifact.md
> +# Use org display name or org entity in the path
I'm actually ok with keeping `or org entity`. The reality is that the org entity will be the best identifier for registry artifacts. Its a "canonical" name that won't change unlike the org display name

2024-12-03 20:01 UTC, estellazx commented on docs/guides/registry/download_use_artifact.md
> +artifact_name = f"{ORG_ENTITY}/wandb-registry-{REGISTRY}/{COLLECTION}:{VERSION}"
^ I'm worried about doing that if identity team has plans on creating multiple orgs on server. that might change in the future :/

Maybe we can teach users how to find the `org entity`?

2024-12-03 20:02 UTC, estellazx commented on docs/guides/registry/link_version.md
> +  )
nit
```suggestion
)
```

2024-12-03 20:02 UTC, estellazx commented on docs/guides/registry/link_version.md
> +If you want to link an artifact version to the Model registry or the Dateset registry, set the artifact type to `"model"` or `"dataset"`, respectively.
```suggestion
If you want to link an artifact version to the Model registry or the Dataset registry, set the artifact type to `"model"` or `"dataset"`, respectively.
```

2024-12-03 20:03 UTC, estellazx approved these changes

2024-12-03 23:43 UTC, ngrayluna commented on docs/guides/registry/download_use_artifact.md
> +artifact_name = f"{ORG_ENTITY}/wandb-registry-{REGISTRY}/{COLLECTION}:{VERSION}"
Silly question: How do we find the org entity now that we are hiding it from the Full Path in the UI?

2024-12-03 23:45 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +artifact_name = f"{ORG_ENTITY}/wandb-registry-{REGISTRY}/{COLLECTION}:{VERSION}"
@estellazx users have no way to know what org entity is - our goal for this project was to keep this internal and not expose it.

2024-12-03 23:50 UTC, ngrayluna commented on docs/guides/registry/download_use_artifact.md
> +artifact_name = f"{ORG_ENTITY}/wandb-registry-{REGISTRY}/{COLLECTION}:{VERSION}"
Not to further complicate things, but if someone changes the name of the org, that'll break their code if they use their org name in the path and not org entity (the latter of which we are hiding)?

2024-12-04 00:09 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +artifact_name = f"{ORG_ENTITY}/wandb-registry-{REGISTRY}/{COLLECTION}:{VERSION}"
Not a silly question at all - there isn't a way to get this now, we don't expose it to users. 

I think what we can do is tell users to on saas how to find their org display name, and tell sever users to confirm w their account administrator.

2024-12-04 00:13 UTC, noaleetz commented on docs/guides/registry/download_use_artifact.md
> +artifact_name = f"{ORG_ENTITY}/wandb-registry-{REGISTRY}/{COLLECTION}:{VERSION}"
Yes that is definitely a good point - however I'm going to leave the decision to platform identity team on exposing the internal concept. And for now the route should be that we tell users (1) how to find their org name i the docs and (2) there should be a warning added when org name is changed to let whoever is changing it know that paths will break. 

Let me know what you guys think. 

Reminder that this only affects 2.7% of users.

2024-12-04 17:29 UTC, ngrayluna commented on docs/guides/registry/download_use_artifact.md
> +artifact_name = f"{ORG_ENTITY}/wandb-registry-{REGISTRY}/{COLLECTION}:{VERSION}"
Added how to find org display name

2024-12-04 17:33 UTC, merged