Added WSM tool to airgapped guide
wandb/docs pull request #936
Opened 2024-12-02 13:41 UTC by mkaesz-wandb

## Description

Added WSM tool to airgapped guide

## Ticket

N/A

## Checklist

Check if your PR fulfills the following requirements. Put an `X` in the boxes that apply.

- [X] Files I edited were previewed on my local development server with `yarn start`. My changes did not break the local preview.
- [X] Build (`yarn docusaurus build`) was run locally and successfully without errors or warnings.
- [X] I merged the latest changes from `main` into my feature branch before submitting this PR.

2024-12-02 13:55 UTC, flamarion requested changes

2024-12-02 13:55 UTC, flamarion commented on docs/guides/hosting/operator-airgapped.md
> +To download all images in the latest versions, execute:
Worth to mention this requires `docker`

2024-12-02 13:55 UTC, flamarion commented on docs/guides/hosting/operator-airgapped.md
> +helm upgrade --install operator wandb/operator -n wandb-cr --create-namespace -f values.yaml
The `wandb-cr` is usually used to deploy the CR instance.
Unless you want to deploy the Operator in the same namespace, I'd pick `wandb-system` or simply `wandb`

2024-12-02 14:04 UTC, mkaesz-wandb commented on docs/guides/hosting/operator-airgapped.md
> +helm upgrade --install operator wandb/operator -n wandb-cr --create-namespace -f values.yaml
ok, changed it. But this was the namespace that we were using in past for all dedicated installations.

2024-12-02 15:31 UTC, flamarion approved these changes

2024-12-03 23:04 UTC, ngrayluna approved these changes

2024-12-04 13:47 UTC, merged